// Package agent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package agent

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fltc9s2Ev4rO7ibuXhKvdhxk1bfXCdp3El7ntidfrB9HghcUmhJAAFAybqM/vvNAqRIiXTi9MWXzuST",
	"TRLAvj/7LPSeCV0arVB5x2bvmeGWl+jRhqeTHJU/S8+5X9Bjik5YabzUis3Yz0q+qxBkisrLTKIFnYFf",
	"IHDaxRImaZWhvQlTvEQ2YzweyBJm8V0lLaZs5m2FCXNigSUnKSW/e4MqJ5HPniaslKp5PEyYXxs6x3kr",
	"Vc42m02zs9W3r+mrqiiiVmDR6coKBIvGokPleViUMGO1QeslhpPC6luZ9g+7QLtEO8pRoeUeU6j2/cAS",
	"hne8NEWw+HB+JJ6mxyP8Ons2ev7Nt9MRn4t0hNnh0dPjr5/Rm+AOnv5bFevGHXt2JkxoN2DZWyy4l0sE",
	"+gwrlPnCQ6YtmIILLMniFIV0UitHaqmqZLMrVugVS1iJqazKUfehfbuQOcUt/LnpGrRd2FfRIvd46yWF",
	"el/TS1mi87w0sFqgavMEVtxBJq2j2OTSeaSkSFimbck9m7GUexyFMx/gJVRLabUqB9PgZfsRCj7HIniq",
	"m7GtlcbqtBJ1avTELJAXfnHrPPeV6ws6rawlIXEZxGX71dHEgmxaMwqwytH5YHyl+JLLgs8L3HV+s/ij",
	"jii487cL5NbPkfsPhUNnQIthuxgsCpTLPxCFWOz34AV97PliayCq5Si8Ha3Q+dHhkPcd2qUUeEsfBrz/",
	"RjpPAuplEJaBX0hXZ5zgCozVS5liV/YVW5YxDp5LhZY8Lz2WQURPifoFt5avw7M2UtwOW/7TyeUFhAXR",
	"+ph2jT479qeiHIe344d4ojLp76y4EPK4/ffGuXWCnv+KwpNCAYApAH11znkuVQDMog5Q0MYNQ2/4b+v9",
	"f1rM2Iz9Y9I2q0kN+5OI+QMRUXjnbw3P8dbr31ANOIheh2BY9FbiUqo8uIl2Au0kLS26qghqPtT+twHH",
	"bGgsb/FdhcPIHT7AXKfroEPTn9q9Pc/8DXrAIwHwF4T5FISBJ2XlPPUh62El/QJamDl4OPwY7j1aEvef",
	"VJTX13Hl9fV4/NVgdbQU7yoGbDc9diza93lNeG4GauyltdoOlMGrU3j+zfQ5EEYUkisPSCupgI1WDnvl",
	"lKLnsuif9LoquRoR+lEDBrwzBVehIsEZFDKTAryO/tVChGYvcCiPpHKe07d+qr49A4sZhq1tuLbnR9V3",
	"Tt9idGXlaLt3MH3v4SWvLy/PGzYidNrZK5XHHG1IM+mLAYUvFtp6WOy6xlVlye26KTZj9bzAQVyILz7s",
	"hZpBrxsYjj4IOx9u/V7e1bujUUPZ9LqhPZ+K1C256sO0clWJ9rbg+UCpVuU8zkqVMlYLdA5TKNE5nqMD",
	"2enU/3IQCrs5sFuq045LpPLPju8JZs0BPsIAQ/K1DPBJRTqRraVW2mslhfRrEAsUvx3cRxc+HIgdp3QV",
	"6wclALCorPTrC2ry0atz5BbtSRVH0fj0qtHjh18uWbJn4A+/XELo/KDnAW9TyKwug3uFVpnMK4sp0Ilw",
	"HsGaPBx4BakTRbSGLbw3ceKUKtN1oD0XlDKbfeEvTn+EQAbg5PwMRtDlBMBVCiVXPI/dWWfQ7Yxhmxtf",
	"q/jPdiyKyF1r760uqMErDKc5VCkYtFKnUrSBpFNYwgopkABw9r6Zw08MFwuEozHNnpUtavPcbDJZrVZj",
	"Hj6Ptc0n9V43eXN2+vKni5ejo/F0vPBl0cEKtrWUJWyJ1kUfLA95YRb8kFZqg4obyWbs6Xg6Po7dZBEC",
	"O2kJX46D9ecrqxzwLXFsB8WaQ0bX6LCDF5DJwmPIwiA4ev0srTv3yZZ2du46rnp3BuGM5vz5eneYa243",
	"3lVo1+31xu5c2L3U+IRpr1dH+6r9yO9kWZWgtkhSc1TKgMBb71Gv5HeREDv5X9xRL8WMV4Vns8PpNKF1",
	"JKB5kqp+6iNMX7mWVJtI+CODG1Knw827uuzbf0NAElt4SJKj6bQpvpplcmMKKYKoya9OB6rfnvfR4SHM",
	"K6Gw91peJQids6qAbRZRLh9/UIG6CX71aYpEUjOgxHc8BVu3pvCxDtRjyf9Z4Z1BQXMb1msSVvf9hgrz",
	"5notTEk8p3qKYxy72STM3DO21LDGQeGqbqra1kMpcAV4J50nMqAVjq/VDoRKR3ShNJpcQOVJOTW7ViM4",
	"yyIFTjU6UNrHY5IdMai8XdMZ8coqhSdH08OD7u6wySWRhzSr63k5IG7bLCVBtENPh0wPAuDugs5pEHJS",
	"TyJ1ML/T6frPTeOhsXOz24Zpjt/81eU0lEWxQTT+e2Jx1B10Dyizj6aHj6XHNuqUET1FHrW8z9SSFzIF",
	"qUzlo/RvH096dEdIeJoVi9Cduu019FUOqcwC4fbQjmwJFWsYf6nj888RnFqIUduLgH142iQNAZm8r3+d",
	"2NxLRb5Hvz2LQEd611z/n73o1f336Jui36MaQ8a2Sybdn13++vb32ba+pjbOXoCrSAymUYfjR68Q7SHT",
	"lUo/xyzvJuUDE3yy88sAIU8v1evh477BArwGiybcCURiTE2xGfKg4Pn4Wm1na9iOew64xXaqnBGfLnD/",
	"u8yVtpiOB5pp0Ot1d/b+g6X153fj3pXC59KF23hwIdD4pp7+v/3uSzV3q/mCCq5/w9Sr6s4lScj77vXI",
	"1Q2ltgs/VMeqiCP+hBs5aafym+2xg8W/c0XR1KDb+y2fbW42/wsAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
