// Package agent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package agent

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fptc9u4Ef4rGLQzTeZISXacXK1vOttJdOM4HtvptWO7HohckrgjAQQAJasZ/ffOAnyTSCfOvbjpzH2K",
	"SQKLfX32WSifaCQLJQUIa+j0E1VMswIsaPc0S0HYeXzObIaPMZhIc2W5FHRKPwj+sQTCYxCWJxw0kQmx",
	"GRCGu2hAOa5SuDegghVAp5R5gTSgGj6WXENMp1aXEFATZVAwPKVg96cgUjzy1YuAFlzUj3sBtWuFcozV",
	"XKR0s9nUO1t9+5q+LvPca0U0GFnqCIgGpcGAsMwtCqjSUoG2HJwkt/qOx31hl6CXoMMUBGhmISblrh9o",
	"QOGeFSp3Fu8t9qMX8UEIL5NX4fd/P5yEbBHFISR7+y8OXr7CN84dLH4v8nXtjh07AxpJM2DZBeTM8iUQ",
	"/ExWwNPMkkRqonIWQYEWxxBxw6UwqJYoCzq9prlc0YAWEPOyCLsP7duMpxg3989t16BmYV9FDczCneUY",
	"6l1Nr3gBxrJCkVUGos0TsmKGJFwbjE3KjQVMioAmUhfM0imNmYXQyXyEl0AsuZaiGEyDk/YjydkCcuep",
	"bsa2Viot4zKqUqN3TAYst9mdscyWpn/QUak1HuKXEb9stzrqWKBNa4oBFikY64wvBVsynrNFDtvOrxd/",
	"0RE5M/YuA6btApj9XDhkQnAxaRYTDRHw5W+Igi/2B/ACP/Z80RgIYhm6t+EKjA33hrxvQC95BHf4YcD7",
	"p9xYPKBaRtwyYjNuqoyLmCBKyyWPoXv2NV0WPg6WcQEaPc8tFO6InhLVC6Y1W7tnqXh0N2z52ezqkrgF",
	"3nqfdrU+W/bHUTFyb0eP8USp4l9ZcS7kfvuvjXPrBLn4GSKLCjkAxgD01TlnKRcOMPMqQE4bMwy97q/G",
	"+3/VkNAp/cu4bVbjCvbHHvMHIiLg3t4plsKdlb+AGHAQvnbB0GA1hyUXqXMT7iS4E7XUYMrcqflY+y8c",
	"jmnXWC7gYwnDyO0+kIWM106Huj+1e3ue+T/oAU8EwH8izNcgDHlWlMZiH9KWrLjNSAszzx8PP4pZCxqP",
	"+3ccFTc3fuXNzWj03WB1tBTv2gdsOz22LNr1eUV4bgdq7ERrqQfK4PUROTx4+T1BjMg5E5YArsQCVlIY",
	"6JVTDJbxvC/pbVkwESL6YQMmcK9yJlxFEqMg4gmPiJXevzKKXLOPYCiPuDCW4bd+ql7MiYYE3NY2XI18",
	"r/qW9AajS83DZu9g+j7AS95eXZ3XbCSSLjcLds8LBISXh4eOa/unvcmkkcuFhRS0S0Fu8wFjLjOpLcm2",
	"3WbKomB6XRei0nKRwyBm+Bef91DFrtc1RHv/uJ0tpGXWKjMdj+OoCJWWmDCjlNusXIy4HFcamDEXS5bz",
	"OGQ6LatMfOROIW2YyFLEj9/CcsfZQrjnxnWRRyuJtcZyLIFHRj6g9yG6IlwyjUVl0Cfzs3/MTufHs4s3",
	"H96dnF3RgJ69v3r9/sPZMQ3o7PTiZHb8r5N/zi+vLmlA52dXJxdns1N6u1u/lad9AgxV5duaPn5tx2tJ",
	"ar/dCVMWoO9ylg5AXlks/MxZCqVlBMZATAowhqVgCO8wnr8Z4gCyFtiFvEnHvVzYVwd0OPErLvUFJu2K",
	"uGXSz0rUCW0tpJBWCh5xuyZRBtEvzx+iXZ8H0i2ndBXrB8U1sqjU3K4vkSx5ry6AadCz0o/0/ul1rceP",
	"P2GGbBv4409XxDEoIheub8Uk0bJw7o2kSHhaaogJSiTnvumhhx0/Q3X8Ea1hWAB+cucikVWgLYswZTa7",
	"hx8fvSOOVJHZ+ZyEpMutCBMxKZhgqWc5MiFdhuG2mdGN8H8046XvgJX2VssciZIAJ82AiIkCzWXMozaQ",
	"KIUGNOcRYCOZfqrvM2aKRRmQ/RHO8KXOK/Owvler1Yi5zyOp03G114xP50cnZ5cn4f5oMspskXdwlTaW",
	"0oAuQRvvg+Uey1XG9nClVCCY4nRKX4wmowPflTMX2HFLnFMYrD9bamEIawh4O3BXXNy7RrodLCcJzy1U",
	"0IKF6bw+jysGNGvoe+fO6Lp39+Jk1PIX6+2huL4l+liCXrfXRNvzdfdy6Cum5l4d7ar2zvc+Ihokqbg+",
	"ZoDj/w+oV7B7P1gY/h/YUi+GhJW5rRpo01z9U9Nc+wjTV64dTpQfnDwTHlKnM+N0ddm1/xaBxFMhlyT7",
	"k0ldfBVbZ0rlPHJHjX820o1MrbwvDmFu7nOFvUMPygjROSlz0mQR5vLBZxWoOuF3X6eIJ4cDSvzAYqKr",
	"1uQ+VoF6qvM/CLhXEOH8C9WagFYcqR4pWH1N6aZNlroG7ieY201A1QPjXwVrjAhYVU1V6mq4J0wQRz2Q",
	"OEkBoxuxBaHcILUqlEQXYHliTk1vREjmiR8lYgmGCGm9mGDrGBBWr1GGv/qLybP9yd7z7m5PewLP2erV",
	"1b2DQ9y2WXKEaAMWhUyeO8DdBp0jd8ismuiqYP4g4/Xvm8ZD4/tmuw1bXcLmjy6noSzyDaL23zMNYffC",
	"4Dlm9v5k76n0aKKOGdFT5EnLe+45PeFCldaffvh0p3t3uITHmdtT/m57dX2VkZgnjrxb0o6+ARaru0bA",
	"js++RXBqIUY0Fyq78LQJagIy/lT9yrN5kIq8AdvIQtDh1tQ/o8yPe3X/Bmxd9DtUY8jYdsm4+/PVH9/+",
	"vtnWV9fG/JiYEo+B2Otw8OQVIi3x8/M3mOXdpHxkgo+3fmFB5OmlejV8PDRYECuJBuXuTzwxxqZYD3kk",
	"Z+noRjSzNWnGPUOYhnaqnCKfzmH3O0+F1BCPBpqp0+ttd/b+jaX1+3fj3pXCt9KF23iwKAJl63r63/a7",
	"P6u5W82XWHD9G6ZeVXcuSVzed69Hrm8xtY37wd9XhR/xx0zxcTuV3zZiB4t/64qirkGz838i6OZ2898A",
	"AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
