// Package agent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package agent

import (
	"time"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AgentCost.
const (
	AgentCostHigh       AgentCost = "high"
	AgentCostLow        AgentCost = "low"
	AgentCostMedium     AgentCost = "medium"
	AgentCostMediumHigh AgentCost = "medium-high"
	AgentCostMediumLow  AgentCost = "medium-low"
)

// Valid indicates whether the value is a known member of the AgentCost enum.
func (e AgentCost) Valid() bool {
	switch e {
	case AgentCostHigh:
		return true
	case AgentCostLow:
		return true
	case AgentCostMedium:
		return true
	case AgentCostMediumHigh:
		return true
	case AgentCostMediumLow:
		return true
	default:
		return false
	}
}

// Defines values for AgentHealthStatus.
const (
	AgentHealthStatusCongested   AgentHealthStatus = "congested"
	AgentHealthStatusReady       AgentHealthStatus = "ready"
	AgentHealthStatusUnavailable AgentHealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the AgentHealthStatus enum.
func (e AgentHealthStatus) Valid() bool {
	switch e {
	case AgentHealthStatusCongested:
		return true
	case AgentHealthStatusReady:
		return true
	case AgentHealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for AgentRegistrationRequestCost.
const (
	AgentRegistrationRequestCostHigh       AgentRegistrationRequestCost = "high"
	AgentRegistrationRequestCostLow        AgentRegistrationRequestCost = "low"
	AgentRegistrationRequestCostMedium     AgentRegistrationRequestCost = "medium"
	AgentRegistrationRequestCostMediumHigh AgentRegistrationRequestCost = "medium-high"
	AgentRegistrationRequestCostMediumLow  AgentRegistrationRequestCost = "medium-low"
)

// Valid indicates whether the value is a known member of the AgentRegistrationRequestCost enum.
func (e AgentRegistrationRequestCost) Valid() bool {
	switch e {
	case AgentRegistrationRequestCostHigh:
		return true
	case AgentRegistrationRequestCostLow:
		return true
	case AgentRegistrationRequestCostMedium:
		return true
	case AgentRegistrationRequestCostMediumHigh:
		return true
	case AgentRegistrationRequestCostMediumLow:
		return true
	default:
		return false
	}
}

// Defines values for ListAgentsParamsHealthStatus.
const (
	ListAgentsParamsHealthStatusCongested   ListAgentsParamsHealthStatus = "congested"
	ListAgentsParamsHealthStatusReady       ListAgentsParamsHealthStatus = "ready"
	ListAgentsParamsHealthStatusUnavailable ListAgentsParamsHealthStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the ListAgentsParamsHealthStatus enum.
func (e ListAgentsParamsHealthStatus) Valid() bool {
	switch e {
	case ListAgentsParamsHealthStatusCongested:
		return true
	case ListAgentsParamsHealthStatusReady:
		return true
	case ListAgentsParamsHealthStatusUnavailable:
		return true
	default:
		return false
	}
}

// Agent Full agent resource representation
type Agent struct {
	// AgentId Server-generated unique identifier
	AgentId *string `json:"agent_id,omitempty"`

	// Cost Relative cost weight for placement decisions
	Cost *AgentCost `json:"cost,omitempty"`

	// CreateTime Timestamp when the agent was first registered
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Environment Environment label for the agent
	Environment *string `json:"environment,omitempty"`

	// HealthStatus Current health status of the agent
	HealthStatus *AgentHealthStatus `json:"health_status,omitempty"`

	// LastHeartbeat Timestamp of last heartbeat received
	LastHeartbeat *time.Time `json:"last_heartbeat,omitempty"`

	// Name Unique name of the agent
	Name *string `json:"name,omitempty"`

	// ServiceTypes List of service types this agent can provide
	ServiceTypes *[]string `json:"service_types,omitempty"`

	// TopicName NATS topic name for this agent
	TopicName *string `json:"topic_name,omitempty"`

	// UpdateTime Timestamp when the agent was last updated
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// AgentCost Relative cost weight for placement decisions
type AgentCost string

// AgentHealthStatus Current health status of the agent
type AgentHealthStatus string

// AgentList Paginated list of agents
type AgentList struct {
	Agents *[]Agent `json:"agents,omitempty"`

	// NextPageToken Token for retrieving the next page of results
	NextPageToken *string `json:"next_page_token,omitempty"`
}

// AgentRegistrationRequest Request body for agent registration
type AgentRegistrationRequest struct {
	// Cost Relative cost weight for placement decisions
	Cost AgentRegistrationRequestCost `json:"cost"`

	// Environment Environment label for the agent
	Environment string `json:"environment"`

	// Name Unique name of the agent
	Name string `json:"name"`

	// ServiceTypes List of service types this agent can provide
	ServiceTypes []string `json:"service_types"`

	// TopicName NATS topic name for this agent (must start with dcm.agent.)
	TopicName string `json:"topic_name"`
}

// AgentRegistrationRequestCost Relative cost weight for placement decisions
type AgentRegistrationRequestCost string

// Error RFC 7807 compliant error response
type Error struct {
	// Detail Human-readable explanation specific to this occurrence
	Detail *string `json:"detail,omitempty"`

	// Instance URI reference for this specific error occurrence
	Instance *string `json:"instance,omitempty"`

	// Status HTTP status code
	Status *int `json:"status,omitempty"`

	// Title Short human-readable summary of the problem
	Title string `json:"title"`

	// Type URI reference identifying the error type
	Type string `json:"type"`
}

// HeartbeatRequest Request body for agent heartbeat
type HeartbeatRequest struct {
	// ConsumerLag Number of unprocessed messages in the agent's NATS consumer
	ConsumerLag int64 `json:"consumer_lag"`

	// Timestamp Timestamp of this heartbeat (used for monotonicity check)
	Timestamp time.Time `json:"timestamp"`
}

// AgentIdPath defines model for AgentIdPath.
type AgentIdPath = string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListAgentsParams defines parameters for ListAgents.
type ListAgentsParams struct {
	// HealthStatus Filter agents by health status
	HealthStatus *ListAgentsParamsHealthStatus `form:"health_status,omitempty" json:"health_status,omitempty"`

	// MaxPageSize Maximum number of results per page
	MaxPageSize *int `form:"max_page_size,omitempty" json:"max_page_size,omitempty"`

	// PageToken Token for pagination
	PageToken *string `form:"page_token,omitempty" json:"page_token,omitempty"`
}

// ListAgentsParamsHealthStatus defines parameters for ListAgents.
type ListAgentsParamsHealthStatus string

// CreateAgentJSONRequestBody defines body for CreateAgent for application/json ContentType.
type CreateAgentJSONRequestBody = AgentRegistrationRequest

// AgentHeartbeatJSONRequestBody defines body for AgentHeartbeat for application/json ContentType.
type AgentHeartbeatJSONRequestBody = HeartbeatRequest
