// Package network provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package network

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// Defines values for NetworkPortProtocol.
const (
	TCP NetworkPortProtocol = "TCP"
	UDP NetworkPortProtocol = "UDP"
)

// Valid indicates whether the value is a known member of the NetworkPortProtocol enum.
func (e NetworkPortProtocol) Valid() bool {
	switch e {
	case TCP:
		return true
	case UDP:
		return true
	default:
		return false
	}
}

// Defines values for NetworkSpecRoutingLevel.
const (
	Application NetworkSpecRoutingLevel = "application"
	Network     NetworkSpecRoutingLevel = "network"
)

// Valid indicates whether the value is a known member of the NetworkSpecRoutingLevel enum.
func (e NetworkSpecRoutingLevel) Valid() bool {
	switch e {
	case Application:
		return true
	case Network:
		return true
	default:
		return false
	}
}

// KubernetesProviderHints Kubernetes-specific settings supplied under
// provider_hints.kubernetes in requests.
type KubernetesProviderHints struct {
	// ClusterIp Specific ClusterIP address, "None" for headless service,
	// or omit for automatic allocation.
	ClusterIp *string `json:"cluster_ip,omitempty"`

	// NodePorts Port name to NodePort value mapping (30000-32767).
	// Presence triggers NodePort or LoadBalancer type inference.
	NodePorts *map[string]int `json:"node_ports,omitempty"`

	// Selector Label selector for pod routing
	Selector *map[string]string `json:"selector,omitempty"`
}

// NetworkPort Network service port specification
type NetworkPort struct {
	// Name Port name for identification.
	// Must be unique within the ports list.
	Name *string `json:"name,omitempty"`

	// NodePort Allocated node port (response-only).
	// Present for NodePort and LoadBalancer types.
	NodePort *int `json:"node_port,omitempty"`

	// Port The port exposed by the service
	Port int `json:"port"`

	// Protocol Transport protocol
	Protocol *NetworkPortProtocol `json:"protocol,omitempty"`

	// TargetPort Port on the backend receiving traffic
	TargetPort           int                    `json:"target_port"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NetworkPortProtocol Transport protocol
type NetworkPortProtocol string

// NetworkSpec defines model for NetworkSpec.
type NetworkSpec struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// Ports Ports to expose on the service
	Ports []NetworkPort `json:"ports"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// RoutingLevel Routing tier for the service.
	//
	// - network: L4 (TCP/UDP) routing
	// - application: L7 (HTTP/gRPC) routing
	//
	// The provider infers the backend service type from this field
	// combined with provider_hints (e.g. presence of node_ports).
	RoutingLevel NetworkSpecRoutingLevel `json:"routing_level"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime           *time.Time             `json:"update_time,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// NetworkSpecRoutingLevel Routing tier for the service.
//
// - network: L4 (TCP/UDP) routing
// - application: L7 (HTTP/gRPC) routing
//
// The provider infers the backend service type from this field
// combined with provider_hints (e.g. presence of node_ports).
type NetworkSpecRoutingLevel string

// Getter for additional properties for NetworkPort. Returns the specified
// element and whether it was found
func (a NetworkPort) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NetworkPort
func (a *NetworkPort) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NetworkPort to handle AdditionalProperties
func (a *NetworkPort) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &a.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["node_port"]; found {
		err = json.Unmarshal(raw, &a.NodePort)
		if err != nil {
			return fmt.Errorf("error reading 'node_port': %w", err)
		}
		delete(object, "node_port")
	}

	if raw, found := object["port"]; found {
		err = json.Unmarshal(raw, &a.Port)
		if err != nil {
			return fmt.Errorf("error reading 'port': %w", err)
		}
		delete(object, "port")
	}

	if raw, found := object["protocol"]; found {
		err = json.Unmarshal(raw, &a.Protocol)
		if err != nil {
			return fmt.Errorf("error reading 'protocol': %w", err)
		}
		delete(object, "protocol")
	}

	if raw, found := object["target_port"]; found {
		err = json.Unmarshal(raw, &a.TargetPort)
		if err != nil {
			return fmt.Errorf("error reading 'target_port': %w", err)
		}
		delete(object, "target_port")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NetworkPort to handle AdditionalProperties
func (a NetworkPort) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.NodePort != nil {
		object["node_port"], err = json.Marshal(a.NodePort)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'node_port': %w", err)
		}
	}

	object["port"], err = json.Marshal(a.Port)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'port': %w", err)
	}

	if a.Protocol != nil {
		object["protocol"], err = json.Marshal(a.Protocol)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'protocol': %w", err)
		}
	}

	object["target_port"], err = json.Marshal(a.TargetPort)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'target_port': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for NetworkSpec. Returns the specified
// element and whether it was found
func (a NetworkSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for NetworkSpec
func (a *NetworkSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for NetworkSpec to handle AdditionalProperties
func (a *NetworkSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["ports"]; found {
		err = json.Unmarshal(raw, &a.Ports)
		if err != nil {
			return fmt.Errorf("error reading 'ports': %w", err)
		}
		delete(object, "ports")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["routing_level"]; found {
		err = json.Unmarshal(raw, &a.RoutingLevel)
		if err != nil {
			return fmt.Errorf("error reading 'routing_level': %w", err)
		}
		delete(object, "routing_level")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for NetworkSpec to handle AdditionalProperties
func (a NetworkSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.Ports != nil {
		object["ports"], err = json.Marshal(a.Ports)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'ports': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["routing_level"], err = json.Marshal(a.RoutingLevel)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'routing_level': %w", err)
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
