// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp7c+M2kv8qKCZVM8mSEvW0raurK42t8ejKln2WnNpkPKeFyCaFCQkwAGhbmdJ3vwJAUuLDljPrJHeX",
	"/c8W8Wh0//rXD+CL5bE4YRSoFNboi5VgjmOQwPV/50TeQMIEkYxvpv41lmv1sw/C4ySRhFFrZN1S8ksK",
	"iPhAJQkIcBQwjuQaUEgk4sV8y7bgEcdJBNbISjjzU0+t4OAkEZZtEbVWonawLYpjNSgsb2/ZFodfUsLB",
	"t0aSp2BbwltDjI3gUgJXa/z3R+z86jonn95mfzifvrj2sLPNf//uP761bEtuErWHkJzQ0Nput2p1kTAq",
	"QJ99HHHA/mbySIRRjceoBCrVnzhJIuJhJX77s1Ba+LI7m9KPxCSyRmX9oQci14j46E3l8G8QNnshMJsp",
	"ZQiJqacEdL3hUbgerp0jOBk6RwMPHOitjx3ohMPj3jronxwrlQmJZSqsUd89sS1JpNbyDQiWcg/qG2Sn",
	"H1/cTMZnPy4nf5/OF3Nru6/RbzkE1sj6pr1DSNt8Fe0J54wbpZXBkGkNZWrb2tY77N/ALykI+ZVKfE8g",
	"8tEbkYDXSnn0BsWpkIgyiVaAIE7kpqywo5Ne3w964PRXw57T756snJUbDJzVsd8buOB1hgMoKczdKWxK",
	"73FEfMSNxGjPHQqdTWc/jC+mZ8vxzfnt5WS2eAWtvcM+ypW0ta33jK+I7wP9So3dCuDIZyC0ltb4HlAC",
	"PCZCEEaRZAh7HgiB5JoIxDOMlJV4jPsDCPqBM/CO+s6ghz3H6wRDxzuB/rAT+N2jYVBSYm+nxLFZPShO",
	"UajuenJzOZ3Pp1ez5dlkNp2cvYLudsra2taUKhLA0Rz4PXAz5+t0OKYopfCYgCfBR6BWQszzUs7BRw9r",
	"EgFKOFMHJTTUbJdhpqzHLhyfkM/Hn52TsHPsnBxB6ISDz64T9sixO/i8Hnbcz3t6HJTBaA6DhD6NEWIf",
	"h4vJzWx88Qo6LHYyekPZQNuaMfmepdR/Ff6r816BUc1LZc2drAbDIByEztA/HjjD/sp3/G545PhuMDjq",
	"htA7PgpLCOw38J5aO9AHKNQ2u1os31/dzl4DezMmkdHP1rZuKU7lmnHyK3ytvn7Q5KOWUbHUTEAeBx1a",
	"cSQQ5gZnKga+zJGHXrfnQ9d3enjQdfrdY+zgoTtw8JHf7bv+yh30/ZIaO3uOXBakCL6FLm9n49vFh8ls",
	"MT0dL17Fm0tK3Bbr6QBcuHN5iv4Z5bEbBSyK2INyypv3p+jo2D1C15ytIojRmdazZib0YbG4RuPrqbij",
	"mPpoPLl2Oic9g3x0kycCSEUdEmQaaN0pLks4S4BLYtKE3HZVqT6kMaaOCoZ4FQGCxyTC1OgxX1MZUFsu",
	"4xXqAWKB5hLt6ma7Xc70okBYSWv2sfDSxI3sjl0mPupBVaYXBtuA8RhLa2SlnDgcAtCLNYmbA7GmT2Uv",
	"8xF5zAf0NsbSW4PIuDezvhnx3b6MOsAXAhAqe93dxoRKCEFzXYb66sbzNePSRuuyPUUax5hvSvZCas2q",
	"gl6SUexOb36oinCJvTWhsIcmvZ1SQ7YdTWNr9LGemtg1F7X3CNCu5n92Q4S2rffj6cXkbHl9Mzm9mp1N",
	"F9OrmWXvwo/e44fx9GL87mJifSodvi7PS5Gw3U/2P5qvBTpyY30qprHVZ/B08lSKOboyKPkrTsjyHrgg",
	"hoXLiv7BfMitWg5fhonQW2iFLRvdd3CUrHHnu9YdncZxKrVhcCCBK8be44udOvI5ikR25cr9R1WU/E1V",
	"J5/+Zv7+tgkbelVYShI3QGRBYhASxwl6WAPNfcIEwQcsjEjgo7eKFHu93knJRayu2x067tDpuIuOO+q5",
	"I9f9ad9YPpbg6J2VWbB/RaNNXoPVBPWJSCK8WZoqrsY6ArgTcALUjzYoG4vU2CfqRuQxGpAw5Y06vS5y",
	"CjQ2hWSMHy+AhqpUHfZsKyY0/7fTIGzSWNMWCYT6jIhRqNHGSInnFOIREO0vlUJ1W5GxNqFe/e7hoTb6",
	"ZfXsQbMoTj8Ul0uIn6sJJUp++VQzZWtbKfG/vmXQQgsVjQId+FSgTGWSSofRaIMw9e8oecrz0GINaHqG",
	"PExVdGR6ZxxFmzy0gY/uCb6jv6TANztWRibh0ov8GyKBDq8JZ/fEB9/WImbZeAgUOJYgEEa3t9Oz1h29",
	"o+918iFMOtHt7nxQicLovTovo6IK4joengXxb+51HMRGmvhfzy0RFhLFzDdafQHDdEf9wT/BMJXQsM/o",
	"FfLJQF8LE7b16GBInCJl3jWQhFqy0cOXO1wuib9VqyZRynHU4OFqZ0LDNMK8+nUvSQuJZIlwYkxxCLzl",
	"e3GLsHZl9LYa0y6IaaWU4xqFR7lMcAhLyX6Ghti2UD9rP+MgOYH7vG5VM5GaqcIeB5FGUgF0ohJKZHSO",
	"CPVVDgxZqUFM1qUNr2ZW8Qyb/7z/Kf7p15/+/l/k6vPk4fKD++9NIS3brS7smHOsk6tKKMgNpgS8xJsi",
	"8TWemkuPdGqoRdTubcQjEuLfxmK7jMzCSqAa9HL57Zr6D2Ym84yNK8nmfrmhjYUboiEF76lyROWz/B5H",
	"SwEeo36m2gCnkbRGQ7dabl2zKDL2NdNUqMtmorcxoSROY9RxxXcVCw+bUupsvDXquE359S7SZuJYLasq",
	"zxnh4BXNUpKTTcJaSBEC+nF8eYECEoFAvh6qAoHUoLyjOlZzxmRWJmMfvVX0LdKVn61LoHYUVZzvR+R2",
	"M1A9Rj0SESwbE8eb0ne0gjW+JzpFr6UuZXspX9wsExYRryFZXWHvZxYEjcbsufUuoh6NViAfAGjm52LP",
	"ppWj9563YpMRY/y4zNYtS2PXapZHDR6axisVVoNCHFUBp6uYSBRgEqW8yh6954RqQNa25mrbBufTPl81",
	"27l2rawGUeX4gyKOJjutOKZeBb4xJrSG4Hd6YGWtHdiyOfWIVhM45dFTAhdccHtzUd1gLWUiRm0VRVrZ",
	"ry2PxW0JOG77XqwTjFZIpHUgNa5QnRLnMKk9UbzPN9TLi/cmUmvSuAouS7Gh3sGsJKvWdDRSE5CK5HEi",
	"91KRqpZ+SzZSI4NCMvCXHotjIhukM+UjMt/R/MMYyTWWu3xJpLp1F6Q6J9WL1Yhp5XW6PR+C/mDYJEcM",
	"QuAQDvaesnEIr1gqtapMN0dmJmnd0cUmIZ5Ojz1GJSZUZD0GP2uZ6cxPW0PNAZUBTG5urm6qMo8jFUNM",
	"x0lk5yqdtbHnU6xbP8tpLmoOIUUXDrqezM6ms/MRmlIiCY7MJ1slAXrkGotdu34DUk+a/zg7nZyN0Nnp",
	"pRmP8h6SMhWW2jJzLfOptpueNZ0tr2+uzm8m8/kIXZAAvI0XAfLWmIYgUMBZbOZzQCtQ0VS3e7U9HaOl",
	"EdIeoPhOZcg4lWsbUZAPjP9sq+JDZD2dIjplDZ3smJZtGdl136UQx7ItvXy56VKMPEgyW90eDFjercae",
	"QnKtJ6uwrFR2TuRVItClSVfR+HqaV0a75rPx7zzsKWWcE+n4nNwDvaOnWOKIhVMJ8TQDCYoKjZo8OAYq",
	"dS31zTcoL8OF+t9B33+/zzYExPffj9BpthfsZUZC8W+JK1XgyaBNaHhHEWqSRacXPgREgUrVaWiMBKji",
	"UAL6h2JPk7L/I7/7QQmLIqGWy48MfnlTTNUPJjsAsYOesXNEPKBCwz678x4n2FsD6rZcK4sBBaU/PDy0",
	"sP7cYjxsZ3NF+2J6OpnNJ0635bbWMo72mplWs90s2yp6YLuu1Na2WAIUJ8QaWb2W2+qbxsRa83G7VuOM",
	"vlghyKZkSNcXujJOcEio7jxFRMiGjL6UISkqmqdJwrgUSk3Ux9zP11CJVapv23SxovPsLKNRcUMPmPrW",
	"yFIFUgUo+iC7lw0f/9ni6GqlkAS+8f584F4BkPUsWKB0wOGesFQUXeqsHlEb6/pk9+Jhr4LYv0qpefKX",
	"g9mWrnaUG3CQKacoAZ6XalPT1SgaITbKcho9vuO6T8un0j8toyC/QknEIi3qNLbbYyOg/uw+n2RuP1Ve",
	"YnRd9wX3aS+7eKpX0g2XUPMiXhUmU87RN3I0LV/I29577qCndA5PKd95qUm9w5NK196Dl0jWdDeub9jM",
	"VUbmOGX/VK6jSjcmGvz8VPeUlZdTeDjUtN1z7FQAd3ZtuOmZQPcEay96Q/w3qNqSU25JfIgTJoF6G4Ng",
	"afp7RDzdoXsgUVS06RCj0EQW5hDlsv8AWVxlzcT6QZ5qY97Ry1TI7GoSnc3mTqfT7aEIryDK2srobcQe",
	"gHtYANJ8TNMYOPHMq6H1JlkD1dnBNEAsJlI+3Y6kSHcjX/LequLexLeeeVP1Gx9UfTIFBAj5jvmb38eD",
	"83db+6/CtjX66Pyemz9boOXXLqUMeEclryLTM686ylePK+ZvEONI/2riKeQPPf4gouq7J4dnlF/evR69",
	"GVevFZ96VPvwpY4hwAiaqpQz/bto7NZVG0Bl/jEzD/BP08l3Q9pNzzQbomj/YD/BHK8Jrn8QOvqHZxRP",
	"kl4PGMYGDcCwDye4KiGNnr+yRKsNIlIUrFwGwDnIP8T67p9GgkFurv/nMDoH2YihJG3EUBJh76so41Zf",
	"1v1eoPlfEbH/PLCam9B/Rew/25kMyL86WLd3jxYOUHipH/qiPvXz/D3Pnyj9X2Lx/L1GQy28p5KsNwJ/",
	"FTKvEPMeOl4Kw5Gao0upxgp6wUkYAtc1G4lj8InCfPmysRGI9h1dbRK8e3yeVC5ym5CqTPmHpBrdPwWk",
	"0ijzL4HODDh7oNFA06oxDQFjT9NAbuOEtHdt3k/b/wkAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
