// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp7b+O2lv8qhG6BmfZKtvxM4sVi4Uk8GS8SJxsnxW0ns760eGRzKpEqSSVxB/7uC5KSbD0yTuem7WKx",
	"/yUWH4fn8Tu/c8gvTsDjhDNgSjqjL06CBY5BgTD/nVN1AwmXVHGxmZJrrNb6ZwIyEDRRlDNn5Nwx+msK",
	"iBJgioYUBAq5QGoNaEUVEsV8x3XgCcdJBM7ISQQnaaBX8HCSSMd1qF4r0Tu4DsOxHrQqb++4joBfUyqA",
	"OCMlUnAdGawhxlZwpUDoNf77I/Z+872TT2+zP7xPX3x32Nnmv3//H985rqM2id5DKkHZytlut3p1mXAm",
	"wZx9HAnAZDN5otKqJuBMAVP6T5wkEQ2wFr/9WWotfNmdTetHYRo5o7L+0CNVa0QJelM5/BuE7V4I7GZa",
	"GVJhFmgB/WB4tFoP194RnAy9o0EAHvTWxx50VsPj3jrsnxxrlUmFVSqdUd8/cR1FldHyDUieigDqG2Sn",
	"H1/cTMZnPy0m/5jOb+fOdl+j3wkInZHzt/bOQ9r2q2xPhODCKq3sDJnWUKa2reu8w+QGfk1Bqm9U4nsK",
	"EUFvZAJBKxXRGxSnUiHGFVoCgjhRm7LCjk56fRL2wOsvhz2v3z1Zeks/HHjLY9Ib+BB0hgMoKczfKWzK",
	"HnBECRJWYrQXDoXOprMfxxfTs8X45vzucjK7fQWtvcME5Uraus57LpaUEGDfqLE7CQIRDtJoaY0fACUg",
	"Yiol5QwpjnAQgJRIralEIvORshKPcX8AYT/0BsFR3xv0cOAFnXDoBSfQH3ZC0j0ahiUl9nZKHNvVw+IU",
	"hequJzeX0/l8ejVbnE1m08nZK+hup6yt60yZBgEczUE8gLBzvk2HY4ZSBk8JBAoIAr0S4kGQCgEEPa5p",
	"BCgRXB+UspVBu8xnynrswvEJ/Xz82TtZdY69kyNYeavBZ99b9eixP/i8Hnb8z3t6HJSd0R4GSXMaK8S+",
	"H95Obmbji1fQYbGT1RvKBrrOjKv3PGXkVfCvjnuFjxpcKmvuZDkYhqvByhuS44E37C+JR7qrI4/44eCo",
	"u4Le8dGq5IH9BtzTa4fmAIXaZle3i/dXd7PX8L0ZV8jqZ+s6dwynas0F/Q2+VV8/GvDRy+hcaiegQIBJ",
	"rTiSCAvrZzoHviyQh0G3R6BLvB4edL1+9xh7eOgPPHxEun2fLP1Bn5TU2NkL5LIgRfItdHk3G9/dfpjM",
	"bqen49tXieaSErfFeiYBF+FcnmJ+RnnuRiGPIv6og/Lm/Sk6OvaP0LXgywhidGb0bJAJfbi9vUbj66m8",
	"Z5gRNJ5ce52TnvV8dJMTAaSzDg0zDbTuNZYlgicgFLU0IbddVaoPaYyZp5MhXkaA4CmJMLN6zNfUBjSW",
	"y3CFBYB4aLDEhLrdbseZXpQIK7Rm3xdeStzo7thl4GMBVGV6YbKtSZX7W01t2iz2Iwo4AfQ2xipYg8wg",
	"NjOyHfH9vigmj4dcxFg5I4cy1evuNqZMwQoMpGXOXd14vuZCuWhdNptM4xiLTcksSK9Z1cNLiMPu9PaH",
	"qgiXOFhTBntOY7bTasi2Y2nsjD7WGYhbi0R3D+fcKs1zGxKx67wfTy8mZ4vrm8np1exseju9mjnuLsuY",
	"PX4cTy/G7y4mzqfS4evyVNn1PnX/aL8WTpDb5FMxjS8/Q2CoUCmDGJ5fij6c0MUDCEktppb1+aP9kBuv",
	"nIwsrqC30Fq1XPTQwVGyxp3vW/dsGsepMvrHoQKh8Xcv+nenzudoSNgVHw8fdYnxd11rfPq7/fu7Jhcw",
	"q8JC0bjBE25pDFLhOEGPa2C569uU9oilFQkIeqshrtfrnZQiwen63aHnD72Of9vxRz1/5Ps/O3vBQbAC",
	"z+yszYLJFYs2eUVVE5RQmUR4s7A1WQ1DJAgvFBQYiTYoG4v02GeqQBRwFtJVKhp1el0wBDS2ZWGMny6A",
	"rXThOey5TkxZ/m+nQdiksUIt6ID+jKhVqNXGSIvnFeJRkO0vlbJzW5GxNqFey+75Q230y6rTg2bRCH0o",
	"y5Y8fq4nlJD35VPtlK3rpJR8ewOghW51bglNGtNpL1VJqjzOog3CjNwz+lzkods1oOkZCjDTuY6bnXEU",
	"bfJEBQQ9UHzPfk1BbHbgiyx9Mov8G6KhSZaJ4A+UAHGNiBm3XgEDgRVIhNHd3fSsdc/u2XtDJaQlB93u",
	"Lga1KJw96PNyJqtOXPeHrzrx7+5cHPSNNCHfji0RlgrFnFitvgBhuqP+4F9AmEpq2Ef0CvhkTl9LE67z",
	"5GFIvIIA79pBUi/ZGOGLnV8uKNnqVZMoFThqiHC9M2WrNMKi+nWPcq2o4on0YszwCkSLBHGL8nZl9Laa",
	"0y6obYyU8xqDJ7VI8AoWiv8CDbntVv9s4kyAEhQe8ipUz0R6pk57AmQaKe2gE00PkdU5ooxoRgtZ4UAt",
	"uTKG1zOr/gyb/3z4Of75t5//8V/06vPk8fKD/+9NKS3brS7sWAhsOFQlFeQG0wJe4k1BY22k5tIjwwCN",
	"iCa8rXhUQfz7UGxHvBysBaq5Xi6/W1P/QWYyz9C4win3iwdjLNyQDRkEzxUXmraKBxwtJASckUy1IU4j",
	"5YyGfrV4uuZRZO1rp+lUl81Eb2PKaJzGqOPL7ysWHjYx52y8M+r4TTR6l2kzcZyWU5XnjAoIitYnzcEm",
	"4S2kAQH9NL68QCGNQCJihupEoIxT3jOTqwXnKit6MUFvNXzLdEmydSnUjqJL7f2M3G521ICzgEYUq0bi",
	"eFP6jpawxg/UMPEadSnbS8fiZpHwiAYNZHWJg194GDYas+fXe4JmNFqCegRgWZzLPZtWjt77uhWbjBjj",
	"p0W2blkat1aaPBnnYWm81Gk1LMTR9Wy6jKlCIaZRKqro0fuaUA2eta2F2rYh+EzMV812bkIrBFtJK44e",
	"NXA02WkpMAsq7htjymoe/M4MrKy1c7ZsTj2j1QRORfScwAUW3N1cVDdYK5XIUVtnkVb2ayvgcVsBjtsk",
	"iA3BaK2ocg5Q4wrUaXEOg9ozNfp8w4K8Rm8CtSaN6+SykBsWHGQlWbVmspGegHQmjxO1R0WqWvo9bKQG",
	"BoVkQBYBj2OqGqSz5SOy39H8wxipNVY7viRT04gLU8NJzWI1YFoGnW6PQNgfDJvkiEFKvIKDnaRsHMJL",
	"niqjKtubUZlJWvfsdpPQwNDjgDOFKZNZK4FkDTDD/Iw19BzQDGByc3N1U5V5HOkcYvtHMjtX6ayNrZ1i",
	"3fpZTnNRcxfScOGh68nsbDo7H6Epo4riyH5yNQkwI9dY7prvG1Bm0vyn2enkbITOTi/teJS3irSpsDKW",
	"mRuZT43dzKzpbHF9c3V+M5nPR+iChhBsgghQsMZsBRKFgsd2vgC0BJ1NTfPW2NOzWhohEwEa7zRDxqla",
	"u4iBeuTiF1cXHzJr3RTZKevbZMd0XMfKbtorhTiO65jly72VYuRBkNmaZl/I894zDrQn1zqs2pe1ys6p",
	"ukokurR0FY2vp3lltGsl2/jO055WxjlVHhH0Adg9O8UKR3w1VRBPMydBUaFRy4NjYMrUUn/7G8rLcKn/",
	"99APP+yjDQX5ww8jdJrtBXvMSGr8LWGlTjyZa1O2umcINcli6AWBkGqn0nUaGiMJujhUgP6p0dNS9n/m",
	"Nzko4VEk9XL5kYGUN8VM/2DZAcid61k7RzQAJo3bZzfY4wQHa0Ddlu9kOaCA9MfHxxY2n1tcrNrZXNm+",
	"mJ5OZvOJ1235rbWKo72epdNsN8d1ih7Yriu1dR2eAMMJdUZOr+W3+rYxsTZ43K7VOKMvzgpUExky9YWp",
	"jBO8osx0niIqVQOjLzEkDUXzNEm4UFKriREsSL6GJlapuTszxYrh2Rmj0XnDDJgSZ+ToAqniKOYgu3cK",
	"H//V4uhqqT0JiI3+fOBeAZD1LHiodSDggfJUFs3orB7RG5v6ZPd+Ya+C2L8YqUXyl4Nsy1Q7OgwEqFQw",
	"lIDIS7Wp7WoUjRAXZZzGjO/4/vPyafpnZJT0NyiJWNCiTmNXPbYCms/+10nm9lPlXUXX919wO/aya6R6",
	"Jd1wpTQv8lVhMh0cfStH0/KFvO29xwtmSufwlPINlp7UOzypdIk9eIlkTTfd5r7M3lhkgVOOTx06unTj",
	"siHOT01PWUc5g8dDTdu9wE4lCG/XhpueSfRAsYmiN5S8QdWWnA5LSiBOuAIWbKwHK9vfo/L5Dt0jjaKi",
	"TYc4gyawsIcol/0HwOIqaybWD/JcG/OeXaZSZReN6Gw29zqdbg9FeAlR1lZGbyP+CCLAEpDBY5bGIGhg",
	"3wCtN8kamGEH0xDxmCr1fDuSIdONfMnrqUp4U+J85YXU73we9ckWECDVO042f0wE56+w9t94bWvw0fkj",
	"N/9qgZZfu5QY8A5KXkWmr7zRKN8wLjnZIC6Q+dXmU8ifbfxJQNX3Tw7PKL+jez14s6FeKz7NqPbhSx0L",
	"gBE0VSln5nfZ2K2rNoDK+GNnHsCfppPvhrSbHl02ZNH+wX6CPV6Tu/5J3tE/PKN4YPR6jmFt0OAY7mGC",
	"qwlp9PUrS7TcIKpkgcplBzgH9adY3//LQDDMzfV/3I3OQTX6UJI2+lAS4eCbIOPOXNb9UU7zvyJj/3XO",
	"am9C/z9j/9XBZJ28KVnrYWaadXTbI2njhLZ3nYxP2/8JAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
