// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp7b+O2lv8qhFpgpr2SLT+TeLFYuIkn40XiZG2nuO1k1peWjmROJVIlqSTuwN99QVKSrUfG6dy0Xeze",
	"/xKLj8Pz+J3fOeRny2NxwihQKazRZyvBHMcggev/LomcQ8IEkYxvp/4tlhv1sw/C4ySRhFFrZN1R8msK",
	"iPhAJQkIcBQwjuQGUEgk4sV8y7bgCcdJBNbISjjzU0+t4OAkEZZtEbVWonawLYpjNSgsb2/ZFodfU8LB",
	"t0aSp2BbwttAjI3gUgJXa/z3B+z85jpnH99mfzgfP7v2sLPLf//uP761bEtuE7WHkJzQ0Nrtdmp1kTAq",
	"QJ99HHHA/nbyRIRRjceoBCrVnzhJIuJhJX77k1Ba+Lw/m9KPxCSyRmX9oUciN4j46E3l8G8QNnshMJsp",
	"ZQiJqacEdL3hSbgZbpwTOBs6JwMPHOhtTh3ohMPT3ibon50qlQmJZSqsUd89sy1JpNbyHARLuQf1DbLT",
	"j6/mk/HFT6vJ36eL5cLaHWr0Ww6BNbK+ae89pG2+ivaEc8aN0srOkGkNZWrb2dYP2J/DrykI+ZVKfEcg",
	"8tEbkYDXSnn0BsWpkIgyidaAIE7ktqywk7Ne3w964PTXw57T756tnbUbDJz1qd8buOB1hgMoKczdK2xK",
	"H3BEfMSNxOggHAqdTWc/jq+mF6vx/PLuejJbvoLWfsA+ypW0s613jK+J7wP9So3dCeDIZyC0ljb4AVAC",
	"PCZCEEaRZAh7HgiB5IYIxDMfKSvxFPcHEPQDZ+Cd9J1BD3uO1wmGjncG/WEn8Lsnw6CkxN5eiWOzelCc",
	"olDd7WR+PV0spjez1cVkNp1cvILu9sra2daUKhDA0QL4A3Az5+t0OKYopfCUgCfBR6BWQszzUs7BR48b",
	"EgFKOFMHJTTUaJf5TFmPXTg9I59OPzlnYefUOTuB0AkHn1wn7JFTd/BpM+y4nw70OCg7ozkMEvo0RohD",
	"P1xO5rPx1SvosNjJ6A1lA21rxuQ7llL/VfCvjnuFj2pcKmvubD0YBuEgdIb+6cAZ9te+43fDE8d3g8FJ",
	"N4Te6UlY8sB+A+6ptQN9gEJts5vl6t3N3ew1fG/GJDL62dnWHcWp3DBOfoOv1dePGnzUMiqXmgnI46BT",
	"K44Ewtz4mcqBLwvkodft+dD1nR4edJ1+9xQ7eOgOHHzid/uuv3YHfb+kxs5BIJcFKZJvocu72fhu+X4y",
	"W07Px8tXieaSEnfFejoBF+FcnqJ/RnnuRgGLIvaognL+7hydnLon6JazdQQxutB61siE3i+Xt2h8OxX3",
	"FFMfjSe3TuesZzwfzXMigFTWIUGmgda9wrKEswS4JIYm5LarSvU+jTF1VDLE6wgQPCURpkaP+ZrKgNpy",
	"Ga5QDxALNJboUDfb7TnTixJhhdYc+sJLiRvZH7sMfNSDqkwvTLYB4zGW1shKOXE4BKAXaxI3d8SaPpW9",
	"zEfkMR/Q2xhLbwMiw97M+mbEd4cy6gRfCECo7HX3GxMqIQSNdZnXVzdebBiXNtqU7SnSOMZ8W7IXUmtW",
	"FfQSRrE/vfmhKsI19jaEwoE36e2UGrLtaBpbow91amLXQtQ+AEC7yv/shgxtW+/G06vJxep2Pjm/mV1M",
	"l9ObmWXv04/e48fx9Gr8w9XE+lg6fF2el3rC7pDsfzBfC+/IjfWxmMbWn8DT5KmUc3RlUIpXnJDVA3BB",
	"DAqXFf2j+ZBbtZy+DBKht9AKWzZ66OAo2eDOd617Oo3jVGrD4EACV4h9gBd7deRzFIjsy5WHD6oo+Zuq",
	"Tj7+zfz9bZNv6FVhJUnc4CJLEoOQOE7Q4wZoHhMmCT5iYUQCH71VoNjr9c5KIWJ13e7QcYdOx1123FHP",
	"Hbnuz4fG8rEER++szIL9Gxpt8xqsJqhPRBLh7cpUcTXUEcCdgBOgfrRF2Vikxj5TNyKP0YCEKW/U6W3B",
	"KdDYFJIxfroCGqpSddizrZjQ/N9Og7BJY01bEAj1GRGjUKONkRLPKcQjINqfK4XqriJjbUK9+j3wh9ro",
	"l9WzR82iMP1YXi55/EJNKEHyy6eaKTvbSon/9S2DFlqqbBToxKcSZSqTVDqMRluEqX9PyXORh5YbQNML",
	"5GGqsiPTO+Mo2uapDXz0QPA9/TUFvt2jMjKESy/yb4gEOr0mnD0QH3xbi5ix8RAocCxBIIzu7qYXrXt6",
	"T99p8iEMneh29zGoRGH0QZ2XUVF14ro/fNGJf3ev46hvpIn/9dgSYSFRzHyj1RcgTHfUH/wTCFNJDYeI",
	"XgGfzOlracK2nhwMiVNQ5n0DSaglGyN8tffLFfF3atUkSjmOGiJc7UxomEaYV78ekLSQSJYIJ8YUh8Bb",
	"vhe3CGtXRu+qOe2KmFZKOa9ReJKrBIewkuwXaMhtS/WzjjMOkhN4yOtWNROpmSrtcRBpJJWDThShREbn",
	"iFBfcWDISg1iWJc2vJpZ9WfY/ufDz/HPv/389/8iN58mj9fv3X9vSmnZbnVhx5xjTa4qqSA3mBLwGm8L",
	"4msiNZceaWqoRdThbcQjEuLfh2J7RmZhJVDN9XL57Zr6jzKTRYbGFbJ5WG5oY+GGbEjBe64cUXyWP+Bo",
	"JcBj1M9UG+A0ktZo6FbLrVsWRca+ZppKddlM9DYmlMRpjDqu+K5i4WETpc7GW6OO28Sv95k2E8dqWVV5",
	"LggHr2iWkhxsEtZCChDQT+PrKxSQCATy9VCVCKR2ynuqczVnTGZlMvbRWwXfIl372boEakdRxflhRm43",
	"O6rHqEcigmUjcZyXvqM1bPAD0RS9Rl3K9lKxuF0lLCJeA1ldY+8XFgSNxuy59S6iHo3WIB8BaBbn4sCm",
	"laP3vmzFJiPG+GmVrVuWxq7VLE/aeWgar1VaDQpxVAWcrmMiUYBJlPIqevS+JFSDZ+1qobZrCD4d81Wz",
	"XerQymoQVY4/KuBostOaY+pV3DfGhNY8+Ac9sLLW3tmyOfWMVhM45dFzAhdYcDe/qm6wkTIRo7bKIq3s",
	"15bH4rYEHLd9L9YEoxUSaR2hxhWoU+IcB7VnivfFlnp58d4Eak0aV8llJbbUO8pKsmpNZyM1AalMHify",
	"gIpUtfR72EgNDArJwF95LI6JbJDOlI/IfEeL92MkN1ju+ZJIdesuSDUn1YvVgGntdbo9H4L+YNgkRwxC",
	"4BCO9p6ycQivWSq1qkw3R2Ymad3T5TYhnqbHHqMSEyqyHoOftcw089PWUHNAMYDJfH4zr8o8jlQOMR0n",
	"kZ2rdNbGnk+xbv0s57mouQspuHDQ7WR2MZ1djtCUEklwZD7ZigTokRss9u36LUg9afHT7HxyMUIX59dm",
	"PMp7SMpUWGrLLLTM59puetZ0trqd31zOJ4vFCF2RALytFwHyNpiGIFDAWWzmc0BrUNlUt3u1PR2jpRHS",
	"EaDwTjFknMqNjSjIR8Z/sVXxIbKeTpGdsoZOdkzLtozsuu9SiGPZll6+3HQpRh4FmZ1uDwYs71ZjT3ly",
	"rSerfFmp7JLIm0Sga0NX0fh2mldG++azie887SllXBLp+Jw8AL2n51jiiIVTCfE0cxIUFRo1PDgGKnUt",
	"9c03KC/DhfrfQd9/f4g2BMT334/QebYXHDAjofC3hJUq8WSuTWh4TxFqkkXTCx8CopxK1WlojASo4lAC",
	"+odCT0PZ/5Hf/aCERZFQy+VHBr+8KabqB8MOQOxdz9g5Ih5Qod0+u/MeJ9jbAOq2XCvLAQWkPz4+trD+",
	"3GI8bGdzRftqej6ZLSZOt+W2NjKODpqZVrPdLNsqemD7rtTOtlgCFCfEGlm9ltvqm8bERuNxu1bjjD5b",
	"IcgmMqTrC10ZJzgkVHeeIiJkA6MvMSQFRYs0SRiXQqmJ+pj7+RqKWKX6tk0XK5pnZ4xG5Q09YOpbI0sV",
	"SBVH0QfZv2z48M8WRzdr5Ungm+jPBx4UAFnPggVKBxweCEtF0aXO6hG1sa5P9i8eDiqIw6uUWiR/Psq2",
	"dLWjwoCDTDlFCfC8VJuarkbRCLFRxmn0+I7rPi+fon9aRkF+g5KIBS3qNLbbYyOg/ux+mWTuPlZeYnRd",
	"9wX3aS+7eKpX0g2XUIsiXxUmU8HRN3I0LV/I2z547qCndI5PKd95qUm945NK196Dl0jWdDeub9jMVUYW",
	"OOX4VKGjSjcmGuL8XPeUVZRTeDzWtD0I7FQAd/ZtuOmFQA8E6yh6Q/w3qNqSU2FJfIgTJoF6W+PB0vT3",
	"iHi+Q/dIoqho0yFGoQkszCHKZf8RsLjJmon1gzzXxryn16mQ2dUkupgtnE6n20MRXkOUtZXR24g9Avew",
	"AKTxmKYxcOKZV0ObbbIBqtnBNEAsJlI+346kSHcjX/LeqhLexLe+8Kbqdz6o+mgKCBDyB+Zv/5gIzt9t",
	"Hb4K29Xgo/NHbv7FAi2/dikx4D2UvIpMX3jVUb56XDN/ixhH+leTTyF/6PEnAVXfPTs+o/zy7vXgzYR6",
	"rfjUo9rHL3UMAEbQVKVc6N9FY7eu2gAq44+ZeQR/mk6+H9JueqbZkEX7R/sJ5nhN7voneUf/+IziSdLr",
	"OYaxQYNj2McJriKk0ZevLNF6i4gUBSqXHeAS5J9iffcvA8EgN9f/cTe6BNnoQ0na6ENJhL2vgow7fVn3",
	"RznN/4qM/dc5q7kJ/VfG/quDyTj5VyfrkdhSfb/WXLosOQlD4JoskzgGn6jNyrc8jZ1q+56utwnev/pN",
	"KjdoTQG72FLvT8H47h8TNvlrjoZKeUs9JI0y4f8DxmeOc+A02tG0akwlZuxpOndtnJD2vr/2cfc/AQAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
