// Package servicetypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package servicetypes

import (
	"time"
)

// Defines values for ServiceType.
const (
	Cluster          ServiceType = "cluster"
	Container        ServiceType = "container"
	Database         ServiceType = "database"
	ThreeTierAppDemo ServiceType = "three-tier-app-demo"
	Vm               ServiceType = "vm"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case Cluster:
		return true
	case Container:
		return true
	case Database:
		return true
	case ThreeTierAppDemo:
		return true
	case Vm:
		return true
	default:
		return false
	}
}

// CommonFields Common fields included in all service type specifications.
// These provide versioning, extensibility, and provider-specific configuration.
type CommonFields struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ProviderHints Optional provider-specific configuration.
//
// Allows platform-specific settings without breaking portability.
// Providers use hints they recognize and ignore unknown hints.
//
// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
// Values are provider-specific configuration objects.
type ProviderHints map[string]map[string]interface{}

// ServiceMetadata Resource metadata for identification and governance.
// Used by all service type specifications.
type ServiceMetadata struct {
	// Labels Key-value pairs for tagging and filtering.
	// Both keys and values must be strings.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier.
	// Must be unique within the namespace.
	Name string `json:"name"`
}

// ServiceType Service type identifier.
// Makes the payload self-describing and enables routing/validation.
type ServiceType string
