// Package servicetypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package servicetypes

import (
	"time"
)

// Defines values for ServiceType.
const (
	Cluster          ServiceType = "cluster"
	Container        ServiceType = "container"
	Database         ServiceType = "database"
	Network          ServiceType = "network"
	Storage          ServiceType = "storage"
	ThreeTierAppDemo ServiceType = "three-tier-app-demo"
	Vm               ServiceType = "vm"
)

// Valid indicates whether the value is a known member of the ServiceType enum.
func (e ServiceType) Valid() bool {
	switch e {
	case Cluster:
		return true
	case Container:
		return true
	case Database:
		return true
	case Network:
		return true
	case Storage:
		return true
	case ThreeTierAppDemo:
		return true
	case Vm:
		return true
	default:
		return false
	}
}

// CommonFields Common fields included in all service type specifications.
// These provide versioning, extensibility, and provider-specific configuration.
type CommonFields struct {
	// CreateTime Timestamp when the resource was created (RFC 3339)
	//
	// Example: 2026-01-13T10:30:00Z
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Id Unique identifier for the resource.
	//
	//
	// Example: vm-abc123
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	//
	//
	// Example: /production/us-east/compute
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	//
	//
	// Example: {"aws":{"instanceType":"t3.xlarge"},"kubevirt":{"instanceType":"u1.large"},"vmware":{"vmxVersion":"17"}}
	ProviderHints *ProviderHints `json:"provider_hints,omitempty"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	//
	//
	// Example: vm
	ServiceType ServiceType `json:"service_type"`

	// Status Current status of the resource.
	//
	//
	// Example: running
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	//
	// Example: Resource is running normally
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	//
	// Example: 2026-01-13T15:45:30Z
	UpdateTime *time.Time `json:"update_time,omitempty"`
}

// ProviderHints Optional provider-specific configuration.
//
// Allows platform-specific settings without breaking portability.
// Providers use hints they recognize and ignore unknown hints.
//
// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
// Values are provider-specific configuration objects.
//
// Example: {"aws":{"instanceType":"t3.xlarge"},"kubevirt":{"instanceType":"u1.large"},"vmware":{"vmxVersion":"17"}}
type ProviderHints map[string]map[string]interface{}

// ServiceMetadata Resource metadata for identification and governance.
// Used by all service type specifications.
type ServiceMetadata struct {
	// Labels Key-value pairs for tagging and filtering.
	// Both keys and values must be strings.
	//
	//
	// Example: {"environment":"production","owner":"platform-team"}
	Labels *map[string]string `json:"labels,omitempty"`

	// Name Resource name identifier.
	// Must be unique within the namespace.
	//
	//
	// Example: my-dev-vm
	Name string `json:"name"`

	// Namespace Provider administrative namespace or equivalent where the
	// resource was provisioned (response-only).
	//
	// Providers map their native grouping concept into this field,
	// for example Kubernetes namespace, GCP project, OpenStack
	// project, or Azure resource group.
	//
	//
	// Example: production
	Namespace *string `json:"namespace,omitempty"`
}

// ServiceType Service type identifier.
// Makes the payload self-describing and enables routing/validation.
//
// Example: vm
type ServiceType string
