// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FpZc9s4Ev4rXdypmqRWp61xJn7Z8lhOhinb8fpIKht5HYhsSkhAgAFAS5qU/vtWAyR1UYozu/HmYd5M",
	"4egD3V9/3cmXIFJppiRKa4LDL0HGNEvRonZfoTSWyQjD+ILZMf0So4k0zyxXMjgMbiT/nCPwGKXlCUcN",
	"KgE7RuDFwaAR4JSlmcDgMOju7WPvl4NnTfz1+bDZ3Yv3m6z3y0Gzt3dw0O11n/U6nU7QCDjdnJG8RiBZ",
	"Sid5pUfQCDR+zrnGODi0OsdGYKIxpoyUS9n0FOWIND3YbwQpl+Vnt0E3WtR097/fs+Yfnebz2yfFH83b",
	"L53GQXde/v70Hz8FjcDOMpJtrOZyFMzn81KUc82J1kpveuTyxTE8+7XzDMitgjNpAWknaDSZkoY8kmmV",
	"obYcjT9vGRebN/2ep0w2NbKYDQUCTjPBJKNFMBlGPOERWAV2zA2oKMq1xnWHX48RfiYX/gwJRxEDN1B6",
	"D4a5hQkzIJWFTKt7HmO8aXWj8n3N61+GoDFBJxgSpb0ylXbe8C26td2qaT8wKBKlU2aDwyDXvFkJrdPX",
	"WGZzU+PP6+sL8IsQqXhFm16nU93EpcURarrKcitq7L4aK21hvPo+Jk9TpmdlAmRaDQWmKyaH8p4JHkMo",
	"s9zWqe5/2O3mItdmXI6cIO9kd3JZ1tjazBy223GUtopfW5FKS69zr0qTF6o81L3z5fR7HxRivZ9uq91q",
	"+BEjSxZdob7nEV7PMgy3xtGLXAgwfqezpIIPyhqVa/dHptGgtC4DNpIo0sgs3lme1tx/zVM0lqUZTMYo",
	"V/DJZUDCtbHgr4iXnREzi013J5nN4tdSzErU2Xi8GAWSwLttAdgvNpRBSAkTk6spG8vTpgVHQ7LTLbPI",
	"8nscyFJd04Kr499P+jenJ33gMuYRs2hWLeIGPueYY+xuiAQymWetgXxxFG6eKpZhzAzgNEKMMYaUTXma",
	"p6DRao6mNZAXJ+f98Pzl3cXl6zdh/+Ryh+wJ45Zik4RzawaywBZNYDXESKUIY2TCjmcwxETphRIOnUhk",
	"3BrQE6PMU4qyyuSgEXgrgkawrhKF31ffiMcPqWEeyRCK4AWKXgj/i4r2v61LX7Uyq63Vl2Uq0fKSuSsG",
	"FVnYpDub5bM+FKO/rlgRCne+rK9reM5SXMJPt3VFu0/5EO+5ts3u3n4t9GcY0bUsjjndycTFEkp4pdag",
	"vHjismb5+pooIdSEoljJSiOTZ5nSFuMVqBrIghPAkzdnVxlGDThW0jIuUfvPPrNsyAz6L6XhWOTG+tWn",
	"PtA3YHMbhFx55NhFsi5PjvrvHvIYeRb/ecgUzFjwN/xZxFwrJauxUbzlRklpBNMmw6xZ1gVPWV0CGbql",
	"Nn5N+0v55x2P53RrJnLNxLaAJ/FcjnLB9I4tpT1+udS/RRWXq3b9qXl9TTzlxm4+wgUbcUkeBsGNpVev",
	"LNoogIsV+rCYuj9+0pgEh8Hf2guS3y7itV1XmisOEjCt2Yy+JU7tXcZGeGfVJ5Q1oUI/O8z04H1fMhM6",
	"CXSSNNdocmHNSqji7FX2r+PwIPx4Mjvbu+mcX7/bP31703v9NrRn168+nc264/P+zd7p9T9n5x/fTc/7",
	"J/vn/aPJ2fGr57XUZC2P5o69JsoRBErKiJw8X8eA/vEZXF1AhY9nTLIRplSDjy5CaMIxMQPCBSapOFar",
	"KqlKxAproYp5TUyYjnMylrab7TUFEqEmwAzRAS4xBu5SbiBJNZRj2uMk0psrw4SHDcEjpI7i8EvZJx1l",
	"LBoj7LUIjnMtlojgZDJpMbfcUnrULs6a9ml4fHJ+ddLca3VaY5uKJd5boeNFEdtPri6ebvNT0AjuURvv",
	"0vsuE9mYdekylaFkGQ8Og/1Wp9ULfH1y4VmfJG5phLauhNlcSwOsSoha1mhgwu0YVOZrACRcWHRB4rTR",
	"7jHDODgMKO/C5Zxa6n7fb9BUd00lcqlCuY71c456tmhZl5YXDepGyG6RsbBkOFuxcYuwYstdseUbBIYJ",
	"OHQGoxLbdCzUxV8pn2nyayTyuArLMpcHkgklR4bHWBDVpQyAPiaMdhHtS5gw6GO2VvuxmtwVole0j/0d",
	"waG7oMrvoVLEGOvMOSuoq8zToZ9GFMpChtqB0RYdUjb1KGf4H1ivRJeaxIIbl19cFl+b7eOmcgukzDyy",
	"+06mNnoWgLvrOR3n9XMFlzV7nU4JdihdArEsEwWtaX80yuH34r5vrA+uTDlYXaMleRShMUkuoMovSv3e",
	"TnWKFvnv36aWn7vUKPEbi91wA4317VjxbI8l/0biNMOI0geLPY2gmAoUUANsW6NL4GPZyHGYiizcEmVW",
	"dczAVSQEBhInC2KmEmAr17cG8nUBgmJWcNwZMIgER2mbzBg+onIT9gfynjOX3B94/AFcNEKFhi0Ik5U5",
	"UcOXJ5KFGiZcCBihpJdHYBLCvk/2VbD1Si/1UTvRtlQcwr5LmVq3bckevgoj33cseOt5LBr7m4pn3zP9",
	"fNStjj/nGwjQ/f4qrJWQMv7KCcpjZ345V/PDLCe993jSz5WFROWysPv540k+VjIRPLLQrBIi7AMT1HjN",
	"qFjnxlH63t7e4yn1hp7C02WcRpiVteBHw+MSQuUO/KwH5XljG3Fd9JlhPPeoTaSmjsim6n5FeAveUqP9",
	"oRwIfgBuCmZWjgYhYVzk2pOygdQYKV2wMlbN0NzozzUqnqk5YKLOzBFn4wt1C1x7ws1A5gZjiHPCMtA4",
	"nsW6GIEINXHcjd0rHsNQqOiTH4hUxNe71dRBvRt17oD6ugddbGmv/bPTJpNyvtrhncVclSxYdY6fpiKL",
	"PTskx5BhTHp7WnCzyyXbWWwp8tsY7CaD622GS4WwJT83FeESs/8b3IZ9NxMTvIT83mPqUHhELqPvj4Yx",
	"Pg2W03wbzattd1+iXcGn4Qy4NZD7gXXY30i7l2i/X849pFP06VT8XKRYr9NrDeSjtIOP3A79sK3QXxn6",
	"0AxdT7G1kdIWAkBXuNbHZ5YftLVZxtuLwddtdXRjiF8/a6zCxWz+v4dgfjv/TwAAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
