// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fptc9u2sv4rGNzONJ2rV1t1Gn2541pKy4zt+MZyMz2RjwORSwkpCDAAKFnN6L+fWYCkSIly3Ezjkznn",
	"mykCi93F7rPPLv2JhipJlQRpDR1+oinTLAEL2j0F0lgmQwiiK2YX+EsEJtQ8tVxJOqQ3kn/MgPAIpOUx",
	"B01UTOwCCM830haFe5akAuiQ9o+OYfDjyfM2/PRi1u4fRcdtNvjxpD04OjnpD/rPB71ej7YoR8kpntei",
	"kiW4k5d60BbV8DHjGiI6tDqDFjXhAhKGyiXs/hzkHDU9OW7RhMvisd9CiRY0yv7nO9b+s9d+cfss/6N9",
	"+6nXOulvit9/+L/vaIvadYpnG6u5nNPNZoNHm1RJA845L5We8SgCiQ+hkhakxT9ZmgoeMnRR94NR7nXp",
	"BPSgZVyg8wxoEikwRCpLFmwJJAWdcGO4ksQqwsIQjCF2wQ3RYFSmnUONZTYzdDjoHbeo5db59tSvjUud",
	"Sv2vxm8uguvr4PXl3Wh8GYxHdFP12XcaYjqk/9PdxkHXvzXdsdZKe8vr9741fdOiN5JldqE0/xPv5Itc",
	"8RsTPCIoBgPJbyChBhdXTBjCNJDi3h/lmn7FNXWxZfiUHrq5PL2Z/Dq+nARnp5O/xT81l2xKeS5s/Ka9",
	"VHrz8ow8/6n3nOA5gjNpCeBKUsQcbdFUqxS05T7+Cu/tSvo1S5hsa2ARmwkgcJ8KJr3tJoWQxzxEFzrf",
	"qTDMtIbdTJ0sgHyPufc9iTmIiDg35+6fZZasmI/aVKslj6rOLNKlVSZtA2y8CYiGGNzBGLNemVI7b/gB",
	"3brurek+Ek1ipRNm6ZBmmrfLQ5v0LYJnz5+TyRXxL0moopo2g16vlMSlhTloFJWH3q6k64XSlizq92Oy",
	"JGF6XSBnqtVMQFIzOZBLlyCBTDPbpLr/4WE35yC95nLuDvJOdjurZy2sTc2w243CpJP/2glVUnide1Xa",
	"PFflse7dVHH7Hc2P9X66LVer2QcILVp0DXrJQ5isUwgOxtHLTAhi/EpnSVl3SlAgGlINBqR1GbCXRGwO",
	"0t4tgAm7uDsUAWcuDi3xy4pYyC/MSSAJk2zuXctNqUaHTBbcTKUXNwOTr/aCWsQA1lsLYk1irRInL7ec",
	"oOmksH0qBY8hXIcYMO74DjmdoVlEaSLRD6sFyFrtJQuXpIQZo0LOLERT6Y7vTNEPILMErwIDcU1bCNtz",
	"MNblcibZknGB8Ym3g/Ld33nFxS2vpVgXz3vx6L3qi/euMy9ZAo/z3QEDp7K0EGEo1IC2kRW3C5XZXKZW",
	"meVynptaRjfIZdstaK/A2HaffoFx/sA7y5usm/AEjGVJ2nAfqG3MtbGFztX8iZiFtpP5CBUiEIAHHozY",
	"Ub6giFXE2AizEwG82L2NIXzNQsuXFeeaDrk++3U8ujkfjwiXEdZPMHWLuCEfM8ggchJCAUxmaWcqX54G",
	"+7vy1y4s4T4EiCAiCbvnSZYQDVZzMJ2pHI3Px5Pa5mKjq4yAd/1syQ1H8HROFtzgXXu7MMpLE36oh3pp",
	"D21RryJt0fw8jPPP+p1Hj+HAvqAdyOQvYcR/L6/9rJVpI9d/UyAqvq6YWzMoB+M2ymyX1/DYWv1ZzZAh",
	"ONSOIo5qMXFVQXO/aafk5ndQcAvPg2IlhFphzChZgpHJ0lRpDK9qSZnKnLuRZ79dXKcQtsiZkpZxCdo/",
	"jphlM2bAPylNzkRmrH+bB+BeeTuUt9e10tLYRb0Zn45+f4yzsjT6cpwSzFjiJXwpTO2UfHd3e6W+Re/b",
	"DNJ2SeJdD+oi2rhdzQH1qfjzjkcblJqKTDNxMAKxN+ByngmmD62pcBb/Oue2uoNUiKtu865NM1k558bu",
	"e/0K65yrVohZeM1VDevMZPsGHywk5nPtSBNnKskhZVqzNT5LuLd3KZvDnVV/+O51JzbwZ4diHpWXBWXE",
	"nQR3ouYaTCasqZfX9av0H2fBSfBhvL44uuldTn4/Pn97M3j9NrAXk1d/XKz7i8vRzdH55P/Xlx9+v78c",
	"jY8vR6eri7NXLxo5407iYOZAmGlu19dotHfODJgGjW3e9ullEbCv3k7oLii8ejshznaiZi6Toy39CpWM",
	"+TzDOokSyVUeBTRv4lAdf8RWYeTMvg3kMlZFD8xCjIC93nB0dkGur0gJpxfIfiDBMnx6FZA2OUNygCjF",
	"ZOS5kX+r4rKi1LguFk2kmW47x5vA5eZwCSKxUCvCDDICZzzPeRWqBnKBa9yJGJDKMOFBTPAQsA8dfirG",
	"MqcpCxdAjjoI3pkWlfZhtVp1mHvdUXrezfea7nlwNr68HrePOr3Owiai0i2VWF24/Nn11Q+H/ERbdAna",
	"eJcu+0ykC9ZHYSoFyVJOh/S40+sMqC9nLk66B7Bh+InOwTZVPJtpaQgrs7Wx1zCOehKV+opEYi4suAh2",
	"2mh3mUFEhxRBIagmfGXY9m6vuXFiKqfM1rXzi0nZxwz0ejsqy5fc5Uu2g4y95HrMgY0k3XWnTWdXaP9f",
	"OjmIiasgxKjYtnMaV1GEafR2KLKoDNYCfqaSCSXnhkeQM9hKXpARxAxXEatIzIQBH8mNfluo1V1+dE37",
	"yMugQyegzPmZUkhLm8y5yDmtzJKZH4nmypIUtMPPAzok7N4Ds+F/QrMS/V7P8UE8oHjiMn/aH0XsK7cF",
	"99QXI98VN6lTqREPXeftzlz0qNd7xBjwcRO2Q5W1YeZ2nbmZYJwJUmYdAsLgQXXyccv//jW1Dg7+fmaR",
	"G5SBsf7s/iFRpcu69WEhbjr+/KbaBLaMjqcy80bCfQohZinka1o0H2TlOEfYodkMIp9lc0fvShp1i32H",
	"auJMrhwCYUTCastRVUxYTXxnKl/nCCzWOd1fE0ZCwbHdZ8bwOda6YDSVS84chrzn0Xvigp6UUNwhQVwb",
	"bbZ8bcSzQJMVF4LMQWKAAWGSBCOPKXWk90pXer4Hob5QnAQjl5mNbjuQpLyOVl/3E8itp/Rg7M8qWn/N",
	"LC++t1Q/9Wz2gKb/9VXYqVRF/BUTnKcGmGIU7OevTwcxg97g6Yy8VJbEKpO5ri+e7uQzJWPBQ0vaZd4F",
	"I8KEG5Ii9ciM66kGR0dPp5T7OuZbArgPIS0q24/+Fp9GiYKcV0bDpF0MW8tPQ+ucmzmMgIikguW9xCyz",
	"bhjtNhirdLXV+haLWFF35ANFp7mSbVqHWo3t3CKINr7UIeFsaj0Stawd3iFvFyDJ+2KK+55wk7PmYp5L",
	"YsZFpj1hnkoNodI5Y2blENXNa11rWbkpbPRdq2M8ifLfLQg3U5kZiEiUYQEgGhbrSOcjNKFWjlezpeIR",
	"mQkV/uEHakXl1N6tpqk+uvn0A/Wx6UK3S7o7/5ewz3Kdrx7wznYYjhbUnePnx8Aiz9zRMWgYk96eDrl5",
	"yCWHO4ziyL/WXeyz68F+uJRlqeidTEmGxfrfVqOCkZupCl4Unf+8SlU6XtZK1lNWBzctMVy5IPUfddsu",
	"1n1wp9lMcLNw2e6jo0x6908AeX//LSKwB4kqCB7qHBrHN7+AraH3bE24NSTz32uC0R4o/QL26yHSY2Yc",
	"Hmzyn3MAGvQGnal8kkHGEzfy32wT/1+PX98aEOxm8s4k9gALq3wscBlc/Uzw7haj3ff0Pr/9+LrLUt7d",
	"jpNvS8l7H+qaJ/hl0Jr9f16km9vNvwIAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
