// Package resource_manager provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package resource_manager

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"5Fpvc9s28v4qO/x1pun89NdWncZvblxLaZmxHV8sN9OLfQ5EriSkIMAAoGQ1o+9+swBJkRLluL3Gl7l7",
	"Z4r4s1jsPs+zS38KIpWkSqK0Jjj+FKRMswQtavcUSmOZjDCML5md0y8xmkjz1HIlg+PgWvKPGQKPUVo+",
	"5ahBTcHOEXg+MWgFeM+SVGBwHPQPDnHw/dHzNv7wYtLuH8SHbTb4/qg9ODg66g/6zwe9Xi9oBZxWTmm/",
	"ViBZQjN5aUfQCjR+zLjGODi2OsNWYKI5JoyMS9j9GcoZWXp02AoSLovHfotWtKhp7X++Y+3fe+0Xt8/y",
	"P9q3n3qto/66+P27v30TtAK7SmlvYzWXs2C9XtPWJlXSoHPOS6UnPI5R0kOkpEVp6U+WpoJHjFzU/WCU",
	"e106gTxoGRfkPIMaYoUGpLIwZwuEFHXCjeFKglXAogiNATvnBjQalWnnUGOZzUxwPOgdtgLLrfPtiR87",
	"LW0q7b8cvTkPr67C1xd3w9FFOBoG66rPvtE4DY6D/+tu4qDr35ruSGul/cnr9745+roVXEuW2bnS/He6",
	"kz/lil+Y4DHQMhRIfgJEGl1cMWGAaYTi3h/lmn7FNfVly/ApPXR9cXI9/nl0MQ5PT8Z/iX9qLlmX67mw",
	"8ZN2UunNy1N4/kPvOdA+gjNpAWkkFDEXtIJUqxS15T7+Cu9tr/RzljDZ1shiNhEIeJ8KJv3ZTYoRn/KI",
	"XOh8p6Io0xq3M3U8R/iWcu9bmHIUMTg35+6fZBaWzEdtqtWCx1VnFunSKpO2ATbehKBxim5jillvTGmd",
	"P/ge27rurek+Ek2mSifMBsdBpnm73LTJ3iJ4dvw5Hl+CfwmRimvWDHq9ciUuLc5Q01J56G2vdDVX2sK8",
	"fj8mSxKmVwVyplpNBCa1I4dy4RIklGlmm0z3Pzzs5hykV1zO3EbeyW5mda+5tak57nbjKOnkv3YilRRe",
	"596UNs9Neax711Xcfhfk23o/3Zaj1eQDRpZOdIV6wSMcr1IM98bRy0wIMH6kO0nJOyUogMZUo0FpXQbs",
	"JBGbobR3nma2l79gCRbX4sZBwiSbeQdyU27WgZMJ7QBKgySTlnOUNOtGlvZQwkQamcUYltzOVWbzNbXK",
	"LJezzo2s3QPKRdsNaC/R2HafyDATgkKmID4KoddSrIrnnbDwG95Z3nS6MU/QWJakpblQs3bKtbGFzdWb",
	"jpnFtlvzESbEKJA2vNuXXcN8QJFhhAYxxRFBTTHblC6m1yyyfFFxrunA1enPo+H12WgIXMaE9GjqJ+IG",
	"PmaYYexWiAQymaWdG/nyJNydlb+GOTOA9xFijDEk7J4nWQIareZoOjdyODobjWuTi4kOw5Hu+tmCG05p",
	"7pwsuKG79ufCuHKE7/L7l1lC+VGeJ2gF3sSgFeT7Ub581u88foxa89CLkGcbULpB+G9ot79WgX32lGmj",
	"Kn1T5D69rhy3dqAcNtq0Zru8hseyymctIy5z+BLHnMxi4rKCO37SFjnkd1CwoGfsqRJCLSlmlCzByGRp",
	"qjSFVxX8bmSuMuDZL+dXKUYtOFXSMi5R+8chs2zCDPonpeFUZMb6t3kA7gDxvry98un6kN5/MzoZ/voY",
	"Z2Vp/OdxSjBjwa/wZ2Fqi5zc3e2QUiu4bzNM26XcdNWSi2jjZjUH1Kfizzser2nVVGSaib0RSCqWy1km",
	"mN43psKu/nWuwnSHSJurbvOsdTOtnnFjd71+STzn2Iowi665amGdQzdv6MFiYj4nnJvYvZQxAdOarehZ",
	"4r29S9kM76z6zddZW7FBPzsU86i8KMQNzQSaSZZrNJmwpk6vq1fpP07Do/DDaHV+cN27GP96ePb2evD6",
	"bWjPx69+O1/15xfD64Oz8d9XFx9+vb8Yjg4vhifL89NXLxrVzVbiUOZglGluV1d0aO+cCTKNmgqSzdPL",
	"ImBfvR0H26Dw6u0Y3NlBTVwmxzDVKvEspeSUzzLiSVoRLvMoCPJyg8zxW2wMJnXnCxYup6qo1lhEEbBT",
	"xQxPz+HqEko4PSf1gwnR8MllCG04JXFAKMVk7LWRf6umJaPUVBmR5piUE03ndBM03OynIJgKtQRmSBG4",
	"w/NcV5FpKOc0xu1IAakMEx7EBI+QKqbjT0UD4SRl0RzhoEPgnWlREbrL5bLD3OuO0rNuPtd0z8LT0cXV",
	"qH3Q6XXmNhEVXV9ideHyZ1eX3+3zU9AKFqiNd+miz0Q6Z31aTKUoWcqD4+Cw0+sMAk9nLk66e7Dh+FMw",
	"Q9vEeDbT0gArs7VRFRsnPUGlnpFgyoVFF8HOGu0uM4yD44BAIawmfKUt9G5HhrtlKrtMVrX9i57Oxwz1",
	"atPUyYfc5UM2JfdOcj1mw0aR7uqopr0rsv8P7RxOwTEIGDW17VzGVQxhmrwdiSwug7WAnxvJhJIzw2PM",
	"FWwlL2CIU0ajqDKfMmHQR3Kj3+ZqeZdvXbM+9msEx26BMucnSpEsbTrOea5pZZZMfPMuNxZS1A4/99iQ",
	"sHsPzIb/js1G9Kk0zkVz8cRl/rRbNO8atwH31JORr9+azKlwxEPXebvVwTvo9R7RsHpcL2gfszZ0h64y",
	"172aZgLKrCNAGDxoTt4Y+P8/ZtbeFtWPLHYtHTTW793ft1Tpsm69rUWTDj8/qdYrLKPjqY55LfE+xYiy",
	"FPMxrSBvueQ4B2xfF4GQz7KZk3eljLqlukM1aSZHhwgMJC43GlVNgdWW79zI1zkCi1Uu91fAIBKcyn1m",
	"DJ8R14XDG7ngzGHIex6/Bxf0UEJxB8JprQnX8txIe6GGJRcCZigpwBCYhHDoMaWO9N7oSs33INQXhkM4",
	"dJnZ6LY9ScrraPVlm/W3XtKjsT+qePUls7z4MlD9KLHeAZr+lzdhi6mK+Cs6OE8NMEXT0ncKnw5iBr3B",
	"0x3yQlmYqkzmtr54up1PlZwKHllol3kXDoEJKnVXJD0y42qqwcHB0xnlvuP4kgDvI0wLZvve3+LTGFGI",
	"80yyBeOuYwrtotlafsRY5drMYQTGkAqW1xKTzIJU+QRjla6WWl8jiRW8Ix8gnWYmW7f2lRqbvkUYrz3V",
	"keBsKj0Staht3oG3c5TwvujivgductVc9HNhyrjItBfMN1JjpHSumFnZRHX9WldaVm6KCn1X6hgvojrg",
	"CkpubmRmMIY4IwIAjfNVrPMWmlBLp6vZQvEYJkJFv/mGWsGc2rvVNPGj608/wI9NF7oZ0t36gr6rcp2v",
	"HvDOphlOJ6g7x/ePkcVeuZNj6GBM+vN04Pohl+yvMIot/1h1sauuB7vhUtJSUTuZUgyL1X+Mo8Kh66kK",
	"XpDOfx9TlY6XNcp6SnZw3RLDlQtS//mx7WLdB3eaTQQ3c5ftPjrKpHefq/P6/mtEYA8SVRDcVzk0tm9+",
	"QltD78kKuDWQ+e814XAHlH5C++UQ6TE9Dg82+c85AA16g86NfJJGxhMX8l9tEf8/j19fGxBsZ/JWJ3aP",
	"Cqt8LHAZXP1M8O6Wot3X9D6/ffu6y1Le3bSTb8uVdz7UNXfwy6A1u/9mF6xv1/8KAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
