// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	. "github.com/dcm-project/control-plane/api/policy/v1alpha1"
	"github.com/oapi-codegen/runtime"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListPolicies List policies
	//
	// Lists policies with support for pagination, filtering, and ordering.
	//
	// ## Filtering
	// Use the `filter` parameter with CEL-style expressions:
	// - `policy_type='GLOBAL'`
	// - `enabled=true`
	// - `policy_type='USER' AND enabled=true`
	//
	// ## Ordering
	// Use the `order_by` parameter:
	// - `priority asc` (default)
	// - `priority desc`
	// - `display_name asc`
	// - `create_time desc`
	//
	// Corresponds with GET /policies (the `ListPolicies` operationId).
	ListPolicies(ctx context.Context, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePolicyWithBody Create a new policy
	//
	// Creates a new policy resource. The caller may optionally specify a
	// client-assigned ID via the `id` query parameter. If not provided, the
	// server will generate a UUID.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /policies (the `CreatePolicy` operationId).
	CreatePolicyWithBody(ctx context.Context, params *CreatePolicyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePolicy Create a new policy
	//
	// Creates a new policy resource. The caller may optionally specify a
	// client-assigned ID via the `id` query parameter. If not provided, the
	// server will generate a UUID.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /policies (the `CreatePolicy` operationId).
	CreatePolicy(ctx context.Context, params *CreatePolicyParams, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePolicy Delete a policy
	//
	// Deletes a policy. This operation is immediate and cannot be undone.
	//
	// Returns 204 No Content on successful deletion. The operation provides
	// strong consistency - attempting to read the resource immediately after
	// deletion will return 404 Not Found.
	//
	// Corresponds with DELETE /policies/{policyId} (the `DeletePolicy` operationId).
	DeletePolicy(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPolicy Get a policy
	//
	// Retrieves a single policy by its ID.
	//
	// This method implements AEP-131 Get standard method.
	//
	// Corresponds with GET /policies/{policyId} (the `GetPolicy` operationId).
	GetPolicy(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdatePolicyWithBody Update a policy
	//
	// Updates an existing policy using partial update (merge).
	//
	// This method implements AEP-134 Update standard method. It uses PATCH
	// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
	// omitted fields are left unchanged. Use `null` to clear optional fields.
	//
	// ## Partial Update (Merge)
	// Send only the fields you want to change. The server merges the patch
	// onto the existing resource. Content-Type must be
	// `application/merge-patch+json`.
	//
	// ## Immutable Fields
	// The following fields cannot be updated (ignored if sent):
	// - path
	// - id
	// - policy_type (cannot be changed after creation)
	// - create_time
	// - update_time
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
	UpdatePolicyWithBody(ctx context.Context, policyId PolicyIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdatePolicyWithApplicationMergePatchPlusJSONBody Update a policy
	//
	// Updates an existing policy using partial update (merge).
	//
	// This method implements AEP-134 Update standard method. It uses PATCH
	// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
	// omitted fields are left unchanged. Use `null` to clear optional fields.
	//
	// ## Partial Update (Merge)
	// Send only the fields you want to change. The server merges the patch
	// onto the existing resource. Content-Type must be
	// `application/merge-patch+json`.
	//
	// ## Immutable Fields
	// The following fields cannot be updated (ignored if sent):
	// - path
	// - id
	// - policy_type (cannot be changed after creation)
	// - create_time
	// - update_time
	//
	// Takes a body of the `application/merge-patch+json` content type.
	//
	// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
	UpdatePolicyWithApplicationMergePatchPlusJSONBody(ctx context.Context, policyId PolicyIdPath, body UpdatePolicyApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPolicies List policies
//
// Lists policies with support for pagination, filtering, and ordering.
//
// ## Filtering
// Use the `filter` parameter with CEL-style expressions:
// - `policy_type='GLOBAL'`
// - `enabled=true`
// - `policy_type='USER' AND enabled=true`
//
// ## Ordering
// Use the `order_by` parameter:
// - `priority asc` (default)
// - `priority desc`
// - `display_name asc`
// - `create_time desc`
//
// Corresponds with GET /policies (the `ListPolicies` operationId).
func (c *Client) ListPolicies(ctx context.Context, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPoliciesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePolicyWithBody Create a new policy
//
// Creates a new policy resource. The caller may optionally specify a
// client-assigned ID via the `id` query parameter. If not provided, the
// server will generate a UUID.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /policies (the `CreatePolicy` operationId).
func (c *Client) CreatePolicyWithBody(ctx context.Context, params *CreatePolicyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePolicy Create a new policy
//
// Creates a new policy resource. The caller may optionally specify a
// client-assigned ID via the `id` query parameter. If not provided, the
// server will generate a UUID.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /policies (the `CreatePolicy` operationId).
func (c *Client) CreatePolicy(ctx context.Context, params *CreatePolicyParams, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePolicyRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeletePolicy Delete a policy
//
// Deletes a policy. This operation is immediate and cannot be undone.
//
// Returns 204 No Content on successful deletion. The operation provides
// strong consistency - attempting to read the resource immediately after
// deletion will return 404 Not Found.
//
// Corresponds with DELETE /policies/{policyId} (the `DeletePolicy` operationId).
func (c *Client) DeletePolicy(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePolicyRequest(c.Server, policyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetPolicy Get a policy
//
// Retrieves a single policy by its ID.
//
// This method implements AEP-131 Get standard method.
//
// Corresponds with GET /policies/{policyId} (the `GetPolicy` operationId).
func (c *Client) GetPolicy(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPolicyRequest(c.Server, policyId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdatePolicyWithBody Update a policy
//
// Updates an existing policy using partial update (merge).
//
// This method implements AEP-134 Update standard method. It uses PATCH
// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
// omitted fields are left unchanged. Use `null` to clear optional fields.
//
// ## Partial Update (Merge)
// Send only the fields you want to change. The server merges the patch
// onto the existing resource. Content-Type must be
// `application/merge-patch+json`.
//
// ## Immutable Fields
// The following fields cannot be updated (ignored if sent):
// - path
// - id
// - policy_type (cannot be changed after creation)
// - create_time
// - update_time
//
// Takes any type of body and a specified content type.
//
// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
func (c *Client) UpdatePolicyWithBody(ctx context.Context, policyId PolicyIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequestWithBody(c.Server, policyId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdatePolicyWithApplicationMergePatchPlusJSONBody Update a policy
//
// Updates an existing policy using partial update (merge).
//
// This method implements AEP-134 Update standard method. It uses PATCH
// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
// omitted fields are left unchanged. Use `null` to clear optional fields.
//
// ## Partial Update (Merge)
// Send only the fields you want to change. The server merges the patch
// onto the existing resource. Content-Type must be
// `application/merge-patch+json`.
//
// ## Immutable Fields
// The following fields cannot be updated (ignored if sent):
// - path
// - id
// - policy_type (cannot be changed after creation)
// - create_time
// - update_time
//
// Takes a body of the `application/merge-patch+json` content type.
//
// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
func (c *Client) UpdatePolicyWithApplicationMergePatchPlusJSONBody(ctx context.Context, policyId PolicyIdPath, body UpdatePolicyApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdatePolicyRequestWithApplicationMergePatchPlusJSONBody(c.Server, policyId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPoliciesRequest constructs an http.Request for the ListPolicies method
func NewListPoliciesRequest(server string, params *ListPoliciesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PageToken != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page_token", *params.PageToken, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.MaxPageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "max_page_size", *params.MaxPageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.OrderBy != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "order_by", *params.OrderBy, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePolicyRequest calls the generic CreatePolicy builder with application/json body
func NewCreatePolicyRequest(server string, params *CreatePolicyParams, body CreatePolicyJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePolicyRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreatePolicyRequestWithBody constructs an http.Request for the CreatePolicy method, with any body, and a specified content type
func NewCreatePolicyRequestWithBody(server string, params *CreatePolicyParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Id != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "id", *params.Id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePolicyRequest constructs an http.Request for the DeletePolicy method
func NewDeletePolicyRequest(server string, policyId PolicyIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPolicyRequest constructs an http.Request for the GetPolicy method
func NewGetPolicyRequest(server string, policyId PolicyIdPath) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdatePolicyRequestWithApplicationMergePatchPlusJSONBody calls the generic UpdatePolicy builder with application/merge-patch+json body
func NewUpdatePolicyRequestWithApplicationMergePatchPlusJSONBody(server string, policyId PolicyIdPath, body UpdatePolicyApplicationMergePatchPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdatePolicyRequestWithBody(server, policyId, "application/merge-patch+json", bodyReader)
}

// NewUpdatePolicyRequestWithBody constructs an http.Request for the UpdatePolicy method, with any body, and a specified content type
func NewUpdatePolicyRequestWithBody(server string, policyId PolicyIdPath, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "policyId", policyId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/policies/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPatch, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListPoliciesWithResponse List policies
	//
	// Lists policies with support for pagination, filtering, and ordering.
	//
	// ## Filtering
	// Use the `filter` parameter with CEL-style expressions:
	// - `policy_type='GLOBAL'`
	// - `enabled=true`
	// - `policy_type='USER' AND enabled=true`
	//
	// ## Ordering
	// Use the `order_by` parameter:
	// - `priority asc` (default)
	// - `priority desc`
	// - `display_name asc`
	// - `create_time desc`
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /policies (the `ListPolicies` operationId).
	ListPoliciesWithResponse(ctx context.Context, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*ListPoliciesResponse, error)

	// CreatePolicyWithBodyWithResponse Create a new policy
	//
	// Creates a new policy resource. The caller may optionally specify a
	// client-assigned ID via the `id` query parameter. If not provided, the
	// server will generate a UUID.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /policies (the `CreatePolicy` operationId).
	CreatePolicyWithBodyWithResponse(ctx context.Context, params *CreatePolicyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePolicyResponse, error)

	// CreatePolicyWithResponse Create a new policy
	//
	// Creates a new policy resource. The caller may optionally specify a
	// client-assigned ID via the `id` query parameter. If not provided, the
	// server will generate a UUID.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /policies (the `CreatePolicy` operationId).
	CreatePolicyWithResponse(ctx context.Context, params *CreatePolicyParams, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePolicyResponse, error)

	// DeletePolicyWithResponse Delete a policy
	//
	// Deletes a policy. This operation is immediate and cannot be undone.
	//
	// Returns 204 No Content on successful deletion. The operation provides
	// strong consistency - attempting to read the resource immediately after
	// deletion will return 404 Not Found.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /policies/{policyId} (the `DeletePolicy` operationId).
	DeletePolicyWithResponse(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*DeletePolicyResponse, error)

	// GetPolicyWithResponse Get a policy
	//
	// Retrieves a single policy by its ID.
	//
	// This method implements AEP-131 Get standard method.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /policies/{policyId} (the `GetPolicy` operationId).
	GetPolicyWithResponse(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error)

	// UpdatePolicyWithBodyWithResponse Update a policy
	//
	// Updates an existing policy using partial update (merge).
	//
	// This method implements AEP-134 Update standard method. It uses PATCH
	// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
	// omitted fields are left unchanged. Use `null` to clear optional fields.
	//
	// ## Partial Update (Merge)
	// Send only the fields you want to change. The server merges the patch
	// onto the existing resource. Content-Type must be
	// `application/merge-patch+json`.
	//
	// ## Immutable Fields
	// The following fields cannot be updated (ignored if sent):
	// - path
	// - id
	// - policy_type (cannot be changed after creation)
	// - create_time
	// - update_time
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
	UpdatePolicyWithBodyWithResponse(ctx context.Context, policyId PolicyIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePolicyResponse, error)

	// UpdatePolicyWithApplicationMergePatchPlusJSONBodyWithResponse Update a policy
	//
	// Updates an existing policy using partial update (merge).
	//
	// This method implements AEP-134 Update standard method. It uses PATCH
	// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
	// omitted fields are left unchanged. Use `null` to clear optional fields.
	//
	// ## Partial Update (Merge)
	// Send only the fields you want to change. The server merges the patch
	// onto the existing resource. Content-Type must be
	// `application/merge-patch+json`.
	//
	// ## Immutable Fields
	// The following fields cannot be updated (ignored if sent):
	// - path
	// - id
	// - policy_type (cannot be changed after creation)
	// - create_time
	// - update_time
	//
	// Takes a body of the `application/merge-patch+json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
	UpdatePolicyWithApplicationMergePatchPlusJSONBodyWithResponse(ctx context.Context, policyId PolicyIdPath, body UpdatePolicyApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePolicyResponse, error)
}

type ListPoliciesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PolicyList
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPoliciesResponse) GetJSON200() *PolicyList {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r ListPoliciesResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r ListPoliciesResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListPoliciesResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r ListPoliciesResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r ListPoliciesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPoliciesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPoliciesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPoliciesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreatePolicyResponse201Headers the declared response headers of an HTTP 201 response for CreatePolicy
type CreatePolicyResponse201Headers struct {
	Location *string
}

type CreatePolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *Policy
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *AlreadyExists
	// JSON422 the response for an HTTP 422 `application/json` response
	JSON422 *ValidationError
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
	// Headers201 the parsed response headers for an HTTP 201 response
	Headers201 *CreatePolicyResponse201Headers
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePolicyResponse) GetJSON201() *Policy {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreatePolicyResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreatePolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreatePolicyResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreatePolicyResponse) GetJSON409() *AlreadyExists {
	return r.JSON409
}

// GetJSON422 returns the response for an HTTP 422 `application/json` response
func (r CreatePolicyResponse) GetJSON422() *ValidationError {
	return r.JSON422
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r CreatePolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r CreatePolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeletePolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeletePolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeletePolicyResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeletePolicyResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r DeletePolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r DeletePolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeletePolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeletePolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetPolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Policy
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPolicyResponse) GetJSON200() *Policy {
	return r.JSON200
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetPolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetPolicyResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetPolicyResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r GetPolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r GetPolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdatePolicyResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *Policy
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *BadRequest
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *Unauthorized
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Forbidden
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *NotFound
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *AlreadyExists
	// JSON500 the response for an HTTP 500 `application/json` response
	JSON500 *InternalServerError
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdatePolicyResponse) GetJSON200() *Policy {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdatePolicyResponse) GetJSON400() *BadRequest {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UpdatePolicyResponse) GetJSON401() *Unauthorized {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpdatePolicyResponse) GetJSON403() *Forbidden {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpdatePolicyResponse) GetJSON404() *NotFound {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdatePolicyResponse) GetJSON409() *AlreadyExists {
	return r.JSON409
}

// GetJSON500 returns the response for an HTTP 500 `application/json` response
func (r UpdatePolicyResponse) GetJSON500() *InternalServerError {
	return r.JSON500
}

// GetBody returns the raw response body bytes
func (r UpdatePolicyResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdatePolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdatePolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdatePolicyResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPoliciesWithResponse List policies
//
// Lists policies with support for pagination, filtering, and ordering.
//
// ## Filtering
// Use the `filter` parameter with CEL-style expressions:
// - `policy_type='GLOBAL'`
// - `enabled=true`
// - `policy_type='USER' AND enabled=true`
//
// ## Ordering
// Use the `order_by` parameter:
// - `priority asc` (default)
// - `priority desc`
// - `display_name asc`
// - `create_time desc`
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /policies (the `ListPolicies` operationId).
func (c *ClientWithResponses) ListPoliciesWithResponse(ctx context.Context, params *ListPoliciesParams, reqEditors ...RequestEditorFn) (*ListPoliciesResponse, error) {
	rsp, err := c.ListPolicies(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPoliciesResponse(rsp)
}

// CreatePolicyWithBodyWithResponse Create a new policy
//
// Creates a new policy resource. The caller may optionally specify a
// client-assigned ID via the `id` query parameter. If not provided, the
// server will generate a UUID.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /policies (the `CreatePolicy` operationId).
func (c *ClientWithResponses) CreatePolicyWithBodyWithResponse(ctx context.Context, params *CreatePolicyParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePolicyResponse, error) {
	rsp, err := c.CreatePolicyWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePolicyResponse(rsp)
}

// CreatePolicyWithResponse Create a new policy
//
// Creates a new policy resource. The caller may optionally specify a
// client-assigned ID via the `id` query parameter. If not provided, the
// server will generate a UUID.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /policies (the `CreatePolicy` operationId).
func (c *ClientWithResponses) CreatePolicyWithResponse(ctx context.Context, params *CreatePolicyParams, body CreatePolicyJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePolicyResponse, error) {
	rsp, err := c.CreatePolicy(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePolicyResponse(rsp)
}

// DeletePolicyWithResponse Delete a policy
//
// Deletes a policy. This operation is immediate and cannot be undone.
//
// Returns 204 No Content on successful deletion. The operation provides
// strong consistency - attempting to read the resource immediately after
// deletion will return 404 Not Found.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /policies/{policyId} (the `DeletePolicy` operationId).
func (c *ClientWithResponses) DeletePolicyWithResponse(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*DeletePolicyResponse, error) {
	rsp, err := c.DeletePolicy(ctx, policyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePolicyResponse(rsp)
}

// GetPolicyWithResponse Get a policy
//
// Retrieves a single policy by its ID.
//
// This method implements AEP-131 Get standard method.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /policies/{policyId} (the `GetPolicy` operationId).
func (c *ClientWithResponses) GetPolicyWithResponse(ctx context.Context, policyId PolicyIdPath, reqEditors ...RequestEditorFn) (*GetPolicyResponse, error) {
	rsp, err := c.GetPolicy(ctx, policyId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPolicyResponse(rsp)
}

// UpdatePolicyWithBodyWithResponse Update a policy
//
// Updates an existing policy using partial update (merge).
//
// This method implements AEP-134 Update standard method. It uses PATCH
// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
// omitted fields are left unchanged. Use `null` to clear optional fields.
//
// ## Partial Update (Merge)
// Send only the fields you want to change. The server merges the patch
// onto the existing resource. Content-Type must be
// `application/merge-patch+json`.
//
// ## Immutable Fields
// The following fields cannot be updated (ignored if sent):
// - path
// - id
// - policy_type (cannot be changed after creation)
// - create_time
// - update_time
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
func (c *ClientWithResponses) UpdatePolicyWithBodyWithResponse(ctx context.Context, policyId PolicyIdPath, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdatePolicyResponse, error) {
	rsp, err := c.UpdatePolicyWithBody(ctx, policyId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePolicyResponse(rsp)
}

// UpdatePolicyWithApplicationMergePatchPlusJSONBodyWithResponse Update a policy
//
// Updates an existing policy using partial update (merge).
//
// This method implements AEP-134 Update standard method. It uses PATCH
// with JSON Merge Patch per RFC 7396. Only provided fields are updated;
// omitted fields are left unchanged. Use `null` to clear optional fields.
//
// ## Partial Update (Merge)
// Send only the fields you want to change. The server merges the patch
// onto the existing resource. Content-Type must be
// `application/merge-patch+json`.
//
// ## Immutable Fields
// The following fields cannot be updated (ignored if sent):
// - path
// - id
// - policy_type (cannot be changed after creation)
// - create_time
// - update_time
//
// Takes a body of the `application/merge-patch+json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PATCH /policies/{policyId} (the `UpdatePolicy` operationId).
func (c *ClientWithResponses) UpdatePolicyWithApplicationMergePatchPlusJSONBodyWithResponse(ctx context.Context, policyId PolicyIdPath, body UpdatePolicyApplicationMergePatchPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdatePolicyResponse, error) {
	rsp, err := c.UpdatePolicyWithApplicationMergePatchPlusJSONBody(ctx, policyId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdatePolicyResponse(rsp)
}

// ParseListPoliciesResponse parses an HTTP response from a ListPoliciesWithResponse call
func ParseListPoliciesResponse(rsp *http.Response) (*ListPoliciesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPoliciesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PolicyList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreatePolicyResponse parses an HTTP response from a CreatePolicyWithResponse call
func ParseCreatePolicyResponse(rsp *http.Response) (*CreatePolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Policy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest AlreadyExists
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest ValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	switch {
	case rsp.StatusCode == 201:
		var headers CreatePolicyResponse201Headers
		if values := rsp.Header.Values("Location"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Location", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uri"}); err != nil {
				return nil, err
			}
			headers.Location = &value
		}
		response.Headers201 = &headers
	}

	return response, nil
}

// ParseDeletePolicyResponse parses an HTTP response from a DeletePolicyWithResponse call
func ParseDeletePolicyResponse(rsp *http.Response) (*DeletePolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPolicyResponse parses an HTTP response from a GetPolicyWithResponse call
func ParseGetPolicyResponse(rsp *http.Response) (*GetPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Policy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseUpdatePolicyResponse parses an HTTP response from a UpdatePolicyWithResponse call
func ParseUpdatePolicyResponse(rsp *http.Response) (*UpdatePolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdatePolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Policy
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Unauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Forbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest AlreadyExists
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
