// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7D3pcts4mq+C4kxV7B5S1m1bW1NbbkvpaDo+xkemtyOvByI/SUhIgA2ActQp/90H2EfcJ9kCwFuUJflI",
	"+sg/mcTx3Rc+0J8tlwUho0ClsHqfrRBzHIAErv86xhL7bDqUEAy9cyxn6qEHwuUklIRRq2ddU/JLBIh4",
	"QCWZEOBowjiSM0CumYyIhMCyLfiEg9AHq2eJAPu+M1cPiVoiVAvbFsWBeuvm97Rsi8MvEeHgWT3JI7At",
	"4c4gwAZWKYGrFf77PXZ+rTuHNzvxD+fmc93uNu6T57v/+VfLtuQi1PtLTujUur+3CwhSITF14WmIIhIv",
	"80iMUyBeGvNL4HPiwtUifATGwkxGetk8oqtQFPndXha1e7W6CBkVoGX4yOeAvcXgExFGxF1GJVCpfuIw",
	"9ImLFb57H4RC+nOGjCKHxMS3enlioTsiZ4h46NU8cBSzPMy9VwibXRCYbRQRYjnoWXvAOeNir+5296ez",
	"7szZh8Ous99xwYHW7MCBxrR70JpN2ocHimRCYhkJq9euH9qWJFIT9gIEi7gLyxvF+M+kDEVvb89zg1qM",
	"Qs1lQbJ3PM2Jp93nSf5XDhOrZ/1lLzMFe+at2Buo6YaqReGIyYoG6YLfY+8CfolAyEdS+TUB30OvYlm5",
	"VYi9QkEkJKJMojEgCEK5qKbt/mGr7U1a4LTH3ZbTbh6OnXF90nHGB16rUwe30e1Agbb1jLZDOsc+8RA3",
	"0KOcDdyUvMQs4WA+jQKF9tMJ/D32UELPe9t6zfiYeB7QRxL3WgBHHgOhiTnDc0Ah8IAIQRhFkiHsuiAE",
	"kjMiEI+lrZrWB7jdgUl74nTc/bbTaWHXcRuTruMeQrvbmHjN/e6kQOtWRusjs8skxWZTCmfAOh5QAt4z",
	"kDij6b1tvcEisb6PNRM5b1IyDzMsUs/wktahvM9mtJ1g4oPnhBxcRj2iqfN06r7BAmUUvbetIVWWHfvK",
	"mgI38x5H6COKIgqfQnAleEhjgZjrRpyDh+5mxAcUcqYkjdCp9lixbleTvgkHh+TDwQfncNo4cA73YepM",
	"Ox/qzrRFDuqdD7Nuo/4hR/pO0XgYpLRPBG6A2cJumNnPQO4UEENeFA+0rVMmX7OIes/g+4pCnVoT7VSq",
	"SXs47nQn087U6XoHHafbHnuO15zuO1590tlvTqF1sD8tSHW7QqrVHhONwqZ0pUw6ZsbTCXvKJHqdrHXO",
	"fOIu+hAC9YC6i0cS1SyDYI79SI9GInJdAA88NI4kwiiJkJCX7oXusKG3wJKIibKBlTRvue2OB92Jsz89",
	"OHTqjRlxPjRbbedjx+/uHwT0sN5geZo3czSPAcs2/cpGJIYnR/CUCRfwQev/I1kQ+1bE42XQeIHi3QZ0",
	"SugK59fAzdbYbXtOB7r7zsHhZOrM6o2mQ1of2p3uR3//4DAoCHR3ibjJjr8N0qZkVITlbE68p9nmy/OL",
	"E2V99UKpOayyuuNW2/U64HQn+wfOYX06c0ij2XI+tD92uvt+cHBYpwUxbeYoWV7/qxIyASY1udcUR3LG",
	"OPn10eL5ToekahmVfZkJyOWgkzHsC4Q5ZEZiq/it6zZbHjQ9p4U7TafdPMAO7tY7Dt73mu26N6532l5B",
	"hBu5+K0IUJrHbcqBiOZQepYgrkDr+3S9cv1C55achcAlMQEeDsntHLgghgnFVd+ZF4hNdPiQj+zM+ohI",
	"Af4E7UBtWrPRvIH9cIYbu7URHQZBJPHYB4QnErjimqZWbUSLyXI8x7LzWe/8vcpt/6aS3Ju/md8Vaa5t",
	"6VXhVpIAlsG/IgEIiYMQ3c2ALlcplCcxC3ho5+L1MWq1Woe7Beia9WbXqTecRuuq0e416716/WfLtiaM",
	"B1haPcvDEhy9u0q4sXdG/UWSzi8B6xER+nhxa8oBS4UGAdyZcALU8xcoHovU2MoaS21ETxICUy8LQygY",
	"TRgDinTpokzwywD7PurDHHwWqjQNvTuxbCvAn94CncqZ1eu2bCsgNPmzUYFKWFkrSWMV9RoRQ3JDq14C",
	"vKOAF3ufCxWu+xKMxbG5wlFORIpjNiuTrGWRCMFdp4Q5NbhUw+9tKyLeY2tlNXSljNVEp/1EIBbJMJIO",
	"o/5CMXZEySpFQlczQMM+cjFV3GZ6X+z7C6SwUDt6aE7wiP4SAV9kCT0yNlQv8h+ITLTYxL7Ks9PSFnA0",
	"BQocSxAIo+vrYb82oiP6mvk+uxPoaHDuNJrN1MxqUBidK2wZFWWx63bqcNCu1x1oHo6ddsNrO3i/0XXa",
	"7W6302m36/V6Y50Ybl0WW8vvKPSeZj98LCQKmGfIvYEV6fQaT7Ei9+kTNlYhi2VbnxwMoZN6u6x8KKze",
	"e6ta7W7Vn7fEu7dubCv0I479stop50foNPIxL73KDHHyNMAUT4HXlL8jbK8weEWF+dlcUbLgN5f0tV1S",
	"WnT5XfsmJy0dFZ1UeijxkLPKTV7vtXKDv477SnB6BjeW8f6bP/vmz7byZ9kx2PuCDyhZp1i6b57iACt0",
	"O/aE8fMHXaKTLyqv8I1O7uhzcyeZzVrhLd8Sc6BU9JgUPsnbEE/hVrKPUOE1r9Rjra8cJCcwTyrBaiZS",
	"M2sjOghCuUCGIYhQTyelcQ5NhB6upSIeXpAEWPxj/nPw868///RPcvbh+m7yz7//vcopchCRb04eSydo",
	"nOOF8uqVxiRVRn1coKOS7a2blcVMWO22JHQJcPYSQZeErZo7l7HZLaJ2aaxWXCRQTMDVWNrIgwmhCW8K",
	"YzhMgAN1YUSVKzVm1WV0QqYRxznLVJSMUphXIRlZEGU2GvYNx1fxIQZDbBNHKd+3xlknDL4lntjG96RW",
	"Ovbk5z52QUcMJ7GajeiDjggJkGi8yLsHL9IqUEQnlbqtTH9zCfO1pnvFgFhkbSsSwG/n2I/gITVSo5AZ",
	"FdNqFU9L6D2kVCoOfKfWXKtKZbkrgr1Gnf5kRu4ptu3lbNrjbFkNDeYqKCsg6IHrYw5iRBkFxDgKGAed",
	"PngZ8mjn3+nvf9soIBQ1dmvoCCkH60Pq1keUTSag2RcJECg3y3SjqD2ASr6osocZrZdQOy3CU0MD7M7M",
	"SikGCBe6few0OB3R3MkU454G0EYPm+ptmJ2kLYpLAaFDM7Wxnvsxug9w+yIXMJXktcQkTWBCyzyvoLNG",
	"+iENqKJKZqiSDZXCKi4UxhkvCUI9FZJjQqUw+SVMsBJ2vY6BYERjv5BnW5JHuFXm/SFe6J6c4zwsy/qX",
	"dHlt6sJy2CbkLTv/EY2LGFqwRH9sIxyGu2XzlLzdxNlqERG3a9RBKE4xOVO+PYYn01c5w9I0JHFQPLrQ",
	"HVBCYgkjOoaJ0vEiekSYdExF9eCVwH+fwX+TY8caTMq0z7dLVQc7l3lBqBK4B6KanXlgK6mTmFDgNvKw",
	"xGMswEauHwmpHgnJOJ6CjSjIO8Y/7m4fDJV0OEl68phVaXN6TFnEWT9GSRMgmugsV1lPldLtH9T30Tln",
	"Yx8C1NenbUZ73lxdnaOj86Ew4abOiQ9b5kwPXSQdhVWKVLQDyQleGao3UYCpo0IdTWn4FPqYxmf/8ZpI",
	"MsObuJdFhZ9x1U8fn9VG9AQvEnYkPS1OOt2L0ZEMzcAPkQfjyMQDRIjlktPG/XZLMkhylcySzl8Ms4g5",
	"E7YUxEKvjo7tCyBt2c6Xpt0RJ066bRXEyWHmElcU181L5DIP0E6ApTsDkYTaRobMiEIpQLcQpgAQKlvN",
	"bGNCJUxBnwXHJ6dLYcWMcWmjWVEqRBQEmC8KXNd6WxvRyxmLfE/xRXkBIqQK+bHLmcgLjEjmChyUFihQ",
	"epOmx7LReZjZsZ1fJDFotrfZmkaBUu5tOyntbY+U7c2bg+wt22bt7bsU105J7LADn2ZYmdQN5lT1MazH",
	"Zcz4RqszlStOHI7pFDYhP1GPFK82WTzteNuEr3NMfKUX6wd7gD2fUEVF00alHEYm7dsL3YamxbY+OUqy",
	"nTnmym3putvw9N3R22H/6OKH65PB6ZVlW9enR9dXbwanV8Pjo6tB37Kt07Or12fXp+rn0duLwVH/vwY/",
	"DS+vLi3bOh9cnAwvL4dnp/3B6VCPvhhcnl1fHA8GP705ur40K7w+Gr4d9M8vBsdnp/3h1fDsVK31/dmF",
	"eX12fXX2+uLo9IeB3n94cv52oKDRL4enV4OL06O3BrR3R8O3R9+/VQP7g6P+2+HpYPDT8WDQH/Stm7Jz",
	"jnv+Y4Oa2Lcq91wROy6luHEAu2xb+uaFSegzR6Jj3NqI6nZEk4AIxOIjDfXulUhOw3biarrhlI1oFIxV",
	"vDJmzAdMbWQgtZEOpfQp2QSBR3Qk9PcJ9lWUk8+SJ+QTeAag0mBdtiiMJZRIgv09EU2noJQ6nZe3wk3b",
	"opFvRFzXPnR3i0bq1lBru9jctMmJM7rpARd2lbX28Rj8Eo0Roeh6uHf8dmhwZQGREjwbqURvDh6acBZo",
	"VPWpUhyuj6y5G0Y1l0VUjiz0f//zv2hkvXPDCB2bR0vB4fH5tXm3fGKw5IUSehcExzCqhN2/ZqBjeKCe",
	"rgsJfbSii/uLPJJGuvSZQOwIFT3iiEgYzFNJgKyiZkRBh2uQJGGVHC4UtGLJW31S12fSoUyaqFDTVTKE",
	"M4asTesGtWmvxATFlAACxhc1QX6F2+k4eSaxiuZrmvuiJgnwkVUO3dOF1qdY2oRqQG6zli7sGfeE/fOc",
	"3huqFHH/x+XZKbo0qptPc5VYJkvryCJl3o7H8USiZr1ZdxpNJVlnusJpOuxUOKUZW9BSFUdFYci4FCjp",
	"ZEb5rT/C4o5xT/TickdAKAmiwEYB/qR/jGh8xGIjZfj1CEMWPSb5CdLVZ2wXievoocQJfRCMOoZENcan",
	"exqNvRiN/FsnI2mRL0uZqzZtKvJT6uQyDgLtNJxGd9dolQLc6jW6mofxH7YVRL4koQ9nkzxD86Fr0aKX",
	"HIEW4c3sfmaXlkA/TgIY7KeKpDKE0FSNckeqr0Ssrjmzj6nJ1RO34KDXuhCitNOUQ3oIq/QPPF3FFe9/",
	"vElMdLKbFpLc/Ykf03USyVm7FE5qPDHYlWtegGC+spyuT4BKRxAPkMqlPYWJrl4L8MFdebIR756rhFdr",
	"1+e0llBRLihS/wSHxpDHsOat4k5cMv4IC/TjrrJECXZL3ng4yZlHLI3pgl8i7Asz3c6NfyXShTAHNbyI",
	"2PsfbxIHTwQKcPjeAHLz/gbTRU8taGaax8JOiv56NYWnzoEwXRivlIzTYqWFVMReaElyt7DKGb4mY6d5",
	"uaw9ZEYfrn3E9yZLvK5Ss9zFjKd1FBU9Shw8FXuI1K8xSPPjt9tQlJUVt2smqvdaT2smSpzpMiOMd31I",
	"WZc7kwpo/ggLxyhkiAk3yqcS3Snj5Fcjk6bm7ktdgq+N6PdMzmI1oV5eO2JNqJW9SbzewupZcRGvWGzM",
	"eYANdebBnqNY4By1ltj7XLgcfB8fXsaW1cWUUeJi/6GT0LLQFdfP3VkqSmFx2HP1IT1Yjj32sRDZaVKF",
	"AtZG9JgFAaMJ3wh1/ciDHtq+Elsb0SNPeXwVTEnGlTVdxGcJyI2EVBG8Qh6NYcGoMmUgoLJ8u7LfavMA",
	"L7ZXWbmyeMSRGJ7EGO7WMknAFLEQ/6J8P9H+EfO0DJoL2DUy2frGa+sobGCwEWi8KAzuKVf/7qSHlIW2",
	"kYmTc4ScqpTglgk7vl6hhh8nPOghEuhR6QmBnVw7TFmgJvRjTvUQ6ItFNootc26mXtjwsZe9psxTkZzC",
	"lDMfhT5Ws9W6wMWumnNpIO0hF4fYJXKhHp6avXtIx7k24ixSsfOtD3PwFTmuZtoWRK6MOKA55kSRJglF",
	"ciKpxdj0DGj2JD5lyYIYyqlfcZJh9Q502VWDpxWBiI/C6r1X1saAqkd16ulHAsaM5f2j8Kz7G5VXuGGk",
	"JY27MyJBw2z1rE8H3dtu27It41d7zXtzTpgXw0aFvdqy06+gm98a/H5HDX6FYGDr5r5mr915qea+go94",
	"bHNftRPVay618hXGFjv48q/WNu4VBpe+IvJiLSzKS8Y9Hdt3s5wZt6E3Rw7ymNEgzIVuyzCFhsiVKMA0",
	"Ugr5cAfM4O7kTf2RHTCFMDtrujBneslpm9HxBF+kD6M0UtowbHFwn88OnrdjJmuJWuL246taCT1eiQKd",
	"RrRY4UKJI9+kyrVFEpZ14z0Qyurufy1oJh6XmE9Bisc3JcwTKpbSs2LJO+tre6m6d9EIrmypsewkOzWA",
	"31TlBwLciBO50OU0IxVjwBz4UWRkw/z1OrGp//jXlbVUCvzXVayxbKxDrVy1OQkawUNqRZRcvrXii586",
	"kNBbFO+kmqujhE5YciEXu9KUSJY7JvrHJ2mLaNxUiY7Oh4nn1U1RcUpBfgUP3eGFkmljLUe0oOmmwTWu",
	"d1Cv0OZisjlCJxxn4Viu+hxHwGrrSebK0Y56MKAzTOPGTxXzMIF9sZvCpZce0fR0kXGiT+iQB4JMqV78",
	"L39BF1kAqiLH777L2Q3x3Xc91DfZgoQg9LWlVRB7ZKKrmjJOH9hkFRIjitDOu5MVmcuP0Rg4BbVsOYlB",
	"c+ZHAdjaSudSlV0DZq5tT4N5rNII8FLjkXTMCdMhV8wJSk1YCkbNmazqrHXCJy5QoRU0jlCPQuzOADVr",
	"dcu2Iu7nThbv7u5qWL/WNd14rth7OzwenF4OnGatXpvJwM+1BFgrxEwpWFK6yQoo97bFQqA4JFbPatXq",
	"tXasj1rH9lZ06/c+W1OQVUZNO1styiGeEqqp5xMhV3aki3ztPC03qIyqunFax6CWhtoQeuhZPUuFCRV9",
	"5EIjk3177v2T4oTkI2TaaWZfIcs5tvy186XQ7fNSlVRX0GNLqqVdK69UjlpGnKIQuIZhxcYB/mS8qvJN",
	"hb3TY6xGZTtJVruvq/f56n25XL8M9mvNoxXMXOKbZpc+QDE4iRjJuxlwc9BUK7U4o6xVJvGJS5WY0ofv",
	"SnRZ7plezZWb0nfdmvX6Bp9W2OzjAquunVR8buAy0oWASeSn3UFKNdsGmqpNUqj3cl9I01Ma66cUv26g",
	"JrXWTyp816qzCWRVn2bS3tz0I8V6u0KUdBWQiQorc6xLsMrGULhb2YufMysq1nGylHjYFyot1nr+atWt",
	"pVeonDRrp+pBEDIJ1F1UmSEDWdWVmTV26CxO3cugrrKB26hDSQNKKfSW30G8MUEcCPk98xYvqSrJRxfz",
	"n3S8X9LWxsuDUBK+So4kpwIi1WN/kVPgZwHwgW90FZvuxsxboKRzGxln/uUsQ7veXT+j9K0lPe1w/bTi",
	"VzfVrGZzg80K3x/Ss9qbglj8RNQzWT1jJlbdXtOD97a7QW2MpA8SqnqefDDm8oFrS0U7ZqZsZMeqaJEN",
	"2Vv9KdwK19uusPWV6mZQrVK3LyTiG8hP+oG855Mbw5bVcmOvj8rNJaAVfmW8QESKFSH2DyC/uEDUfxvW",
	"Pf3m3x9cvn4A+ZxGqcdhtvBUBq3jjspY7oqT6RS4QMnY+AATU/P9R5WPVfCuNqI/5I4mVByYP4Uwl5h8",
	"mJoqLlt5o3VJyi8SkP+ssp7yrMq6bimW30KBtSqXytvmivcc5ZfVVZdS18C6Ssu3CssXqbCICtZcVBRU",
	"MF1UHHqY8/a4rlLZiFGFfPk88WvXUL7VTtbUTh5VMtm8UvJcNZFnqYX8oUsgX7H0sTZQ+FbpyIXpj4lT",
	"XrKGUBEslD8Mun2lYKMCwZNi40cXBH5vdYCNJKbwLyNeuHjw6JrBFqWClxGN+lexfn/eSkDclO1W/Ucn",
	"3UInSsfh5rpEUWoi/Z8z9MWoE+BTQOe6E0k3zu23Dru7Oho5ZRLMVzFyDW46p09z/KwlYIfnG2mEXeyT",
	"EDZa/kbHru5aJw/eNSgKtMHwJWR6kzgiUKRyNPH/9sIxxdfRKtOD+ZVjCgNE+i9d/vg6boS6MoIodnY+",
	"rtywql2p8q5kPJ3oK2vKRujCgE75xaoqRL6n6FmrELURPVvqECv1MMYhpzZxIYc5YZFI08+4ofKrVDLM",
	"vTn9/1ySzMnOPugkGWrU66vh+yIFj5d05uXW4W/1gmK9oOAcN60XrFDl5y4dxPc9h31ExOorCXfE99N7",
	"CYhRWF10yHcrP7LoMOxX39kY0ZNIyLh/EvVPL51Go9nKvnkQYIl2fHYH3MUCkO62o1EAnLimd3C2CGdA",
	"xW7pOwjVdy9oGmhvULf7PRQ7Cn3kX7bYsbR15X0yI+u/yWJHdn0//j9Ff7aKR+H/xC7HK+WrnxvFL3GO",
	"W7B063LcB83Lmnxg+R/lfim3uFbo/1w5bkmYcncNNBvztwze3ygeGetsmGyatfdwSPayjuqb+/8PAAD/",
	"/w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
