// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3pcttIkv+rVGAmwlYPQPGWxH9M/EMt0W1O6xod3tm2tIoikCTLBqrQVQXJbAe/7gPsI+6TbNSBk6BI",
	"yZLdPe1vMlFHVlaev0zAnx2fRTGjQKVwBp+dGHMcgQSu/3WAJQ7ZdCQhGgVnWM7UjwEIn5NYEkadgXNF",
	"ya8JIBIAlWRCgKMJ40jOAPlmMiISIsd14BOO4hCcgSMiHIbenfqRqCVitbDrUBypp35xT8d1OPyaEA6B",
	"M5A8AdcR/gwibGiVErha4b/eY++3prd389r+4d18brr91iL9fev//9VxHTmP9f6SEzp1Fgu3dEAqJKY+",
	"fNlBEbHLPPHEGREvffIL4HfEh8t5/IQTCzMZ6WWLB111RFHc7WWPtlCri5hRAVqG90MOOJgPPxFhRNxn",
	"VAKV6k8cxyHxsTrv9gehDv05P4xih8QkdAZFZqF7ImeIBOjVXeSpywowD14hbHZBYLZRTLByMHCafn9n",
	"OuvPvB3Y63s7PR886Mx2PWhN+7ud2aS7t6tYJSSWiXAG3eae60giNUPPQbCE+7C8gT33/tH5cP/wP2+H",
	"/xpdXF44iyIv/8ph4gycv2znOr5tnortIeeMG3aVb93yC1mGLVznRxycw68JCPlE9r0hEAbolRWCW0X5",
	"KxQlQiLKJBoDgiiW8zLTdvY63WDSAa877ne8bntv7I2bk5433g06vSb4rX4PSkxr5kwb0TsckgBxQzUq",
	"GLWMb6OTd/tHo8Pb/fOfro6HJ5fPwLkfcYBSRi1c5w3jYxIEQJ/ItSsBHAUMhObSDN8BioFHRAjCKJIM",
	"Yd8HIZCcEYG4lZMyE3dxtweT7sTr+Ttdr9fBvue3Jn3P34NuvzUJ2jv9SYmJnZyJ+2b1SXaKjHVnw/Pj",
	"0cXF6PTk9nB4MhoePgPvcmYtXOctFqkhfKrGFgx7RVNnWGRG+iUUtbq+Zdqb/dHR8PD27Hx4cHpyOLoc",
	"nZ48A9veYoFyVi1cZ0SV9cShsljAzbyncXCfooTCpxh8CQECtRJivp9wDgG6n5EQUMyZkhFCp9orWHUr",
	"87QNu3vkw+4Hb2/a2vX2dmDqTXsfmt60Q3abvQ+zfqv5ocDTXlmPzWG0vwFuiCiq8OXw/GT/6Bn4mO1k",
	"+IbsQNc5YfINS2jwDI6jLIaZYmuDXubZ3rjXn0x7U68f7Pa8fncceEF7uuMFzUlvpz2Fzu7OtCSH3Ro5",
	"VGtPNOkZw05OL2/fnF6dPIfCnjCJDGcWrnPGQuLPDyEGGgD150/kllkGwR0OEz0aicT3AQII0DiRCKM0",
	"bkBBthe6x4aRAksiJgSCMjM7frcXQH/i7Ux397xma0a8D+1O1/vYC/s7uxHda7ZYkZntAjMtQflmL63P",
	"dsMCJzPunsMHrYpP5K11TIjbZdB4juxuQzoltOI5WrjdGfvdwOtBf8fb3ZtMvVmz1fZI50O31/8Y7uzu",
	"RSUR7C9xLd3pK/Es44/iGGd3JPgy+3dxdn6sLJxeKDM9Rcs27nT9oAdef7Kz6+01pzOPtNod70P3Y6+/",
	"E0a7e01aEqx2gUXVdV+WQ+lumVm7ojiRM8bJb08WqHc6xFLLqPTATEA+B50t4FAgzCHX143Clb7f7gTQ",
	"DrwO7rW9bnsXe7jf7Hl4J2h3m8G42esGJaFrFcKVMiFZgpGx9upk/+ry7fDkcnSwf/ksMUuJiYtsvWrm",
	"rLMazmLgkph4Bsfk9g64IIa75VXfmQeITbRTLQYyZn1EpIBwgl5DY9pw0V0Lh/EMt7Ya13QURYnE4xAQ",
	"nkjg6jo0OxrXtJym2TmOW8y37t6rrOpvKr26+Zv5uybBch29KtxKEsEy+ZckAiFxFKP7GdDl/FhZa7NA",
	"gF6fvzlAnU5nb6tEXbvZ7nvNltfqXLa6g3Zz0Gz+4rjOhPEIS2fgBFiCp3dXqR4OTmk4TxPJJWIDIuIQ",
	"z29NIrqU4grg3oQToEE4R3YsUmNrs/vGNT1OGUyD3IdTMCI+BpTopLnK8IsIhyE6hDsIWRwBlejdseM6",
	"Ef50BHSqku9+x3UiQtN/tmqOEtdm6ZnDV48RMSw3vBqkxHuKeLH9uYStLCo0lscWIIuCiJTHbJagr70i",
	"EYO/TgkLanChhi9cJyHBU1GaBrpUVmii81IiEEtknEiP0XCuLvaaklWKhC5ngEaHyMdU3TbT++IwnCN1",
	"CrVjgO4Ivqa/JsDneeaJjHHUi/w/RCZabKx3CdwMVAGOpkCBYwkCYXR1NTpsXNNr+oaFIbsXaH945rXa",
	"7cx+alIYvVOnZVRUxa7fa8Jut9n0QOXP3VbQ9fBOq+91u/1+r9ftNpvN1joxfDQgs/a+kzj4MvsRYiFR",
	"xALD7g2sSG/Q+hIrssh+YWMVZDiu88nDEHuZG8uBK+EM3jv1aner/nlLgoVz4zpxmHAcVtVOeTdCp0mI",
	"eeVRbojTXyNM8RR4I/CjBmHbpcErsM1nc0Xpgt9d0rd2SRnW8If2TV6GmJSdVAaHP+SsCpPXe63C4Gcy",
	"Z6kRuH2cP8pMuGXLWYh90Ow/top9TR/0UkiAVFlcwXcEiSJqpY5t4A7aL+Cw01t8BsedS/t3D/7dgz/K",
	"g+clp/clr1exx1a6b77E5ddYM+v77e8PBgFeET1eEQ14hTLj5mFBPmtFfHBETI2nHCNQ+CRvYzyFW8k+",
	"Qk2ccKl+1vrKQXICdykirGYiNbNxTYdRLOfIXAgiNFCZOlg4gAg9XEuFHV6SBJj/4+6X6JfffvnXP8np",
	"h6v7yT///nen3hQnoanyVYpanOO5imNqjUmmjLoeoOOwx1s3J48SsdptSehS4twlhi4JW/3tXFizWz7a",
	"hbFaFvdQl4DrT+miACaEpndTGsNhAhyoD9dUeRZjVn1GJ2SacFywTGXJqAS2NZKRh41mo9GhufFV92DJ",
	"EI+JHJW3XxOeJAL47R0OE3hIONQoZEZZ77OKUkPDRqKi4rl3as21AlLlZpnsNULyJ1PdL9HYl9PUp2lo",
	"RTGLzRVPVUw97iFm1i1UL/Pq/rE/K481FINQvwrJMaFSmLQDJljxTq9lqLimNsItHUwUmfIIddK9BAdF",
	"WtQdRISOzOxW9W5dp9h3UG+iLoqULWv9C5mlRY0wZRWLMpH6Z5T2taCJDiaVwKjIaWe3uYPOOBuHEKFD",
	"jc8b/r+9vDxD+2cjYYRHh557HVMFQOdpk0zdVZSlKcX8q1S9TSJMPRV6aX7ApzjE1Bbu7Joq89QMtaVj",
	"ZeUtnKBLHyprxXMlRhITmpaQvWx6YI8jGZpBGKMAxolREyLEci67cafJkv0hBYhks8yE5Jwrl8eNfzgw",
	"+UUiIDATOPY/qiszajJOplNCp9UDbNj2ksXACSdeJp5150qLJUt3p2TDPEQ+CwC9jrD0ZyDS5NRImhlR",
	"ist1q01GAKGy0843JlTCFHSNyVZmlqzhjHHpollZdkQSRZjPS7Kh1bFxTS9mLAkDxUxlbYiQKknGPmei",
	"KFYinStwVFmgxOFNmoNy9tXbjGPszwiFgujr7RQfG+hK6dT+UHNXF/sLT9P8jiaRcjRLTUjuUpnKLVTt",
	"3Wq3l1vTi+M658OL06vzg+Ht8F9v968uzCp1lUXX2f/x9Nw8P726vD19c3u+f/LTUJMxOj47Giqi9OOs",
	"10JT+G5/dLT/45EaeDjcPzwanajNDobDw+Gh8pEFbi+fcFPZrThl22to5TkVrzqHXOMilgIj66eWr/bQ",
	"PDBhYK7p2pU1rqnu5DD9AAIxC2ipZ69EioW+tsiCOYeLaBKNgbtozFgImLrIUOoi7aA0RjpBEBDtVP4+",
	"waEAtxRbTcgnCAxBlcE61y2NJZRIgsNtkUynIGRhXlEJ2q5DkzBUa5iEWdc29aFuDbce54JNv4I4pZvC",
	"m9hXljDEYwgrPEaEoqvR9sHRyJyVRURKCFSMxMmdsqWcRfqoGlO0iPO1ztobd36cNHyWUHntoP/97/9B",
	"1847P07Qgflpq2oLDs6uzLNlCGXJEqRML0mPua3KEf9jBnIGHAENdEohNNak0Y558aRGxDRIYo2RYor1",
	"XcIcPxMHyLEuIw/asUIacNVecwkKseK3Gqz9x8XpiWGqXTq7D5mHSJdp7IYS3fcVMO1a09BhaLYWg7ob",
	"ya4pgojxeUOQ3+B2OjYPIpA4wBI3tFCIhiTAr53KfVWWXJ/3aVOvibvNi/04CIgB/c4KNsEwq4YlF0at",
	"i5GuEtl0aR21Z3f6OuB4IlG72W56rbYSuFMNSZqmCuUq9H2XNFi5uCSOGZci9xnFrT/C/J7xQAy0Q3NR",
	"RCiJkshFEf6k/7imFopykXIteoRhix6T/gnS11jkeWp0B2gmZSwG27rTwzMsajA+3dbH2LbHKD71cpaW",
	"L6cqTifa7CmnrLTMZxwEet3yWv0to2yKcGfQ6us7tP9wnSgJJYlDOJ0UL7QYVZStfcVJaMnezCfkNmuJ",
	"9ANGUwnJ9EuFd7HJtwrQ8ythtbjgEjBlWv1Tl+GhNzoXUkprMqIBwip+h0DjAuL9zzep+U5300JSaCj9",
	"OVsnlZy1S+E01bNk1655DoKFyqr6IQEqPUECQGOsYlZGDR4iIAR/ZaJpdy9gK/Xa9TnL7hbLCVo1uIqN",
	"kbe0Fo3lawtCfIQ5+nlLGar0dEueejQpGDEsjWWDXxMcCjPdLYx/JbKFMAc1vHyw9z/fpM6fCBTh+L0h",
	"5Ob9DabzgVrQzDQ/CzeFkfRq6pw6PMV0bjxWOk6LlRZSYZ3TkuSuM9aseE6TatGSPFoXyWFKGN1qrA20",
	"7JsblZutU6qCT/iyynIZGbBhVLmWrP4agzR//H4Ly1lZ55FF5eag82VF5dR/Ll+EcagPqeZyhbp0zJ9h",
	"7hn1izHhRtV8LGHKOPnNpPsGmwolcJPT/sjkzCoFDYq6YOW+UfUddr25M3AoyHvGP5YSsKK931BDHqw9",
	"W4Hz1Fpi+3Pp9aSFrbtaO+pjyijxcfhQEbcqdOX1C43fZSksD3uudqoH4a6DEAuRo5E1Cti4pgcsihhN",
	"741QP0wCGKC7yE2RGpXQKHFTvsJFfpgIqSvW+4Hy5ipQkowrSzm3UCHyEyFV5K6OisYwZ1SZKxBQC5yt",
	"rDlvHrxZ65RjSWUEMzUzqenbauT3jiliMf5V+XWifR/mGUZViNH1YfL1jUfWEVYaB6PxvDR4oNz4u+MB",
	"UkGsi0wg7CIhGcdTcNFUZQG3TLi2W1YNP0g5PkAk0qMy8NtNX8FwkdUaNeHQ3ssAge7sdpG1w4WZemFz",
	"a4P8MWWBitLUSTkLURxiNVutC1xsqYNdzrQOJ75MOKA7zIk6ZBowFERJi59pU9CMTn3BkuYbHqi/bD7g",
	"DHY1bqVZogWYiI/CGbxXViLGPpFzParXzF4vHDMmC0IjAmdxo6J/P060zHB/RiRomp2B82m3f9vvOq5j",
	"kohBe2EQ5KJAtWrszCP7Fko69b1d4Q/UrlBy4o9uVWgPur2XalUo2fantirUOz+95lJjQmlsuR+h+Ght",
	"G0JpcOX94xcrXSrvZmt5j69inhoHoDdHHgqY0SDMBSCN5lJjB1GEaaIU8uHK5/D++G3ziZXPSkXQmnBb",
	"OkmLGkbH0/MijebrQ2nD8IgKWzGqf95KaV4KX7rtDSGpvEKfRnSl9yN+P7hUHRKV1Fifd2WYOT/fS2HN",
	"ZbO1Kvkz1C7f4UJXyiYsfWcI+9Kk9Ms11cOD46z1w3Y0ov2zUeqDlLdJg2LyGwToHs/VLRu7cU1LMm/q",
	"4zY/p0GpOmvyEUInHOeBSQFEtVGd2nqSOzX0Wv0wpDNMbdel8v5M4FBsZXTppa9pqnEe4wSo1G8fCjKl",
	"evG//AWd50GVCqt++KGgQeKHHwbo0ETAEqI41DZHURyQiUbhpA2J2WTVIa4pQq/fHa+IvX9OxsApqGVt",
	"GO5q+1QIt7cMWQVV0WQdqFAYgsy8MEWQRiX0Nw7KcW2lV0DRpG8iR0W1bIXEByq0oNvYbD/G/gxQu9F0",
	"XCfhyqmkoOP9/X0D68cac7RzxfbR6GB4cjH02o1mYyajsFBNdFaIlZLZFGzIU/6F67AYKI6JM3A6jWaj",
	"a/KvmbY52yu67gafnSnIuoxSuxktujGeEqq5FxIhV3aWiSK2myXIKiuob4DS0ZejqTaMHgXOwFEOsqYf",
	"TOjD5N9ref9FHjL9cId2F/mXOwomvfjC3FLQslwi1QivtUhaurWySuWiZMIpioFrGlZsHOFPxp8oc1za",
	"O6u+tGor0Tm23FTPi+hyFU5eJvuNvqMVl7l0b/q6NMBvziTsIe9nwE2ZpFFp6kJ5lZ2I2qLN0sdiKnxZ",
	"7hJbfSs3lW+htJvNDd723Oy1yFXtozUvSl4kOpmdJGHWWKBUs2uoqdsko3q78PERPaW1fkr5vUw1qbN+",
	"UukDFL1NKKv71IJ+C9S0Mli9XSFKGrdiosbKHGjQUNkYCvcruw8LZkXFDF6eDI4OhUoItZ6/WtV9/ApV",
	"00XtRAOIYiaB+vM6M2Qoq2t9XWOHTm3SWiV1lQ18jDpUNKCSPD7y20E3JhgCIX9kwfwlVSX9UFHxM0iL",
	"JW1tvTwJFeGrvZEUxxaZHofzggI/C4EPfJqj3K8zZsEcpc2FyDjzr2cZus3++hmVDzboaXvrp5W/VKVm",
	"tdsbbFb61oGe1d2UxPJ3Jp7J6hkzsaoLXQ/efty7X8ZIhiChrl8nBGMuH2jULtsxM2UjO1bHi3zI9urP",
	"x9W43m6Nra9VN3PUOnX7SiK+gfxk38V5Prkx17Jabtz1UblK/cMVb4yp4I1IsSLE/gnkVxeI5u/Duk/S",
	"e/w3l6+fQD6nURpwmM0DlUHruKM2lrvkZDoFLlA61pbcMDWffVL5WM3dNa7pTwVQXsWBRfzdNBCHMDX4",
	"JVv5+uiSlJ+nJP9ZZT27szrr+kix/B4KrFW5TN42V7zngF9Woy6VOvc6pOU7wvJVEBZRczUPoyqlIvN6",
	"SGVl9litp31rJOU7grIGQXkScLI5XvJcyMizICL/1kDINwRA1oYL3/GOQrD+lGjlJZGEmpCh+mGzx+MF",
	"G8EEXxQhPxkW+KOhARtJTOkLzy8MITwZOXgEYPAyotH8Jtbvz4sH2GZiv+7/QtAtZKJSFDdN/WWpMf0n",
	"unPlGPgU0JnuxNGNYzudvf6WjkZOmAQkZ1iiQoOXaZdcim8xB0Qe7HYvi6ah9SWkc5OIIFKH9jQb//bC",
	"0cG30Q/TTfiNowNDRPbJ9X9/bTVCXRsLlHsUnwYfrGo3qn03z04n+hUppe060dcpvFiFKhR7gp4VVVC5",
	"8li3BRXeja1049ngURurmMMdYYnIEknbGvhNkAnznpb+enuaA7n5N0QkQ61mczV9XwXAeEm3XG2C/Z75",
	"lzP/olZunPmvUOXnBgHs+4WjQ0TE6ub6exKGWYc9YhRWwwfFvtsnwgejw/q3D67pcSKk7X9EhycXXqvV",
	"7uTv30dYotchuwfuYwFId8/RJAJOfNMLOJvHM6Biq/JOfv1bBDQLmTdA4P4IsEWpI/rrwhZLW9e+42Rk",
	"/XcJW+Svi9v/6+DPhl2U/q+05Xil+vLhRvGLzVZLlm5dtvqgeVmTDyz/Z3Ffyy2uFfo/V7ZaESb7tmd6",
	"i6a7ehvHZDtvgb5Z/F8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
