// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H3pchs3uuiroHqmylKmm+IuibembikSnXBiLaPFkxtTVwN2f03C7gY6AJoy49Lf8wDnEc+TnALQO5si",
	"KUt2MvE/isTy7Rs+QJ8sl4URo0ClsAafrAhzHIIErv86xhIHbDqSEI68Cyxn6ksPhMtJJAmj1sC6oeTX",
	"GBDxgEriE+DIZxzJGSDXTEZEQmjZFnzEYRSANbBEiIPAmasviVoiUgvbFsWh+tUt7mnZFodfY8LBswaS",
	"x2Bbwp1BiA2sUgJXK/z/d9j5rekc3u4kH5zbT02733pIv9/9v3+1bEsuIr2/5IROrYcHu4QgFRJTFz4P",
	"UUSSZZ6IcQbES2N+BXxOXLheRE/AWJjJSC9bRHQViqK428ui9qBWFxGjArQMHwUcsLcYfiTCiLjLqAQq",
	"1UccRQFxscJ3771QSH/KkVHkkJgE1qBILHRP5AwRD72ah45iloe59wphswsCs40iQiIHA2sPOGdc7DXd",
	"/v501p85+3DYd/Z7LjjQmR040Jr2Dzozv3t4oEgmJJaxsAbd5qFtSSI1YS9BsJi7sLxRgv9MykgM9vY8",
	"N2wkKDRcFqZ7J9OcZNpDkeR/5eBbA+sve7kp2DO/ir2hmm6oWhaOhKxomC34PfYu4dcYhHwilV8TCDz0",
	"KpGVO4XYKxTGQiLKJJoAgjCSi3ra7h92up7fAac76Xecbvtw4kyafs+ZHHidXhPcVr8HJdo2c9qO6BwH",
	"xEPcQI8KNnBT8hKzhIP5NA4V2p9P4O+xh1J6PtjWa8YnxPOAPpG4NwI48hgITcwZngOKgIdECMIokgxh",
	"1wUhkJwRgXgibfW0PsDdHvhd3+m5+12n18Gu47b8vuMeQrff8r32ft8v0bqT0/rI7OJn2GxK4RxYxwNK",
	"wHsGEuc0fbCtH7FIre9TzUTBm1TMwwyLzDO8pHWo7rMZbX1MAvCciIPLqEc0dT6fuj9igXKKPtjWiCrL",
	"jgNlTYGbeU8j9BFFMYWPEbgSPKSxQMx1Y87BQ/czEgCKOFOSRuhUe6xEt+tJ34aDQ/L+4L1zOG0dOIf7",
	"MHWmvfdNZ9ohB83e+1m/1XxfIH2vbDwMUtonAjfAbGE3zOxnIHcGiCEvSgba1hmTr1lMvWfwfWWhzqyJ",
	"dir1pD2c9Pr+tDd1+t5Bz+l3J57jtaf7jtf0e/vtKXQO9qclqe7WSLXaw9cobEpXyqRjZnw+Yc+YRK/T",
	"tS5YQNzFCURAPaDu4olENcsgmOMg1qORiF0XwAMPTWKJMEojJORle6F7bOgtsCTCVzawluYdt9vzoO87",
	"+9ODQ6fZmhHnfbvTdT70gv7+QUgPmy1WpHm7QPMEsHzTr2xEEngKBM+YcAnvtf4/kQWJb0U8WQZNFijZ",
	"bUinhK5wfi3c7kzcruf0oL/vHBz6U2fWbLUd0nnf7fU/BPsHh2FJoPtLxE13/H2QNiOjIixnc+J9nm2+",
	"urg8VdZXL5SZwzqrO+l0Xa8HTt/fP3AOm9OZQ1rtjvO++6HX3w/Cg8MmLYlpu0DJ6vpflZApMJnJvaE4",
	"ljPGyW9PFs+3OiRVy6jsy0xALgedjOFAIMwhNxJbxW99t93xoO05HdxrO932AXZwv9lz8L7X7ja9SbPX",
	"9Uoi3CrEb2WAsjxuUw7EtIDSswRxJVo/ZOtV6xc6t+QsAi6JCfBwRO7mwAUxTCiv+tb8gJivw4diZGfW",
	"R0QKCHy0A41pw0bzFg6iGW7tNsZ0FIaxxJMAEPYlcMU1Ta3GmJaT5WSOZRez3vk7ldv+TSW5t38zn2vS",
	"XNvSq8KdJCEsg39NQhAShxG6nwFdrlIoT2IW8NDO5etj1Ol0DndL0LWb7b7TbDmtznWrO2g3B83mL5Zt",
	"+YyHWFoDy8MSHL27Srixd06DRZrOLwHrEREFeHFnygFLhQYB3PE5AeoFC5SMRWpsbY2lMaanKYGpl4ch",
	"FIwmTADFunRRJfhViIMAncAcAhapNA29PbVsK8Qf3wCdypk16HdsKyQ0/bNVg0pUWyvJYhX1MyKG5IZW",
	"gxR4RwEv9j6VKlwPFRjLYwuFo4KIlMdsViZZyyIRgbtOCQtqcKWGP9hWTLyn1soa6FoZK1+n/UQgFsso",
	"lg6jwUIxdkzJKkVC1zNAoxPkYqq4zfS+OAgWSGGhdvTQnOAx/TUGvsgTemRsqF7k/yDia7FJfJVnZ6Ut",
	"4GgKFDiWIBBGNzejk8aYjulrFgTsXqCj4YXTarczM6tBYXSusGVUVMWu32vCQbfZdKB9OHG6La/r4P1W",
	"3+l2+/1er9ttNputdWK4dVlsLb/jyPs8+xFgIVHIPEPuDaxIb9D6HCvykH3DJipksWzro4MhcjJvl5cP",
	"hTV4Z9Wr3Z368454D9atbUVBzHFQVTvl/AidxgHmlZ9yQ5x+G2KKp8Abyt8RtlcavKLC/GyuKF3wm0v6",
	"2i4pK7r8oX2Tk5WOyk4qO5R4zFkVJq/3WoXBz2TOUiNwRzyxTIKrwoFFxis0OslFbrLQZIkC7IImP4+V",
	"dpwXfBIzlDu6GFWY98463Pd64LstB7cmbafrdjznALq+08P9yb574B1C07dsa9Jt9yftjuv4LWg7Ha/r",
	"Or1JHzv7B4dNPHE98FttZZaMFRp8qkOzlg6Yc6xTYx7TuzqPfFHECxGvgTbCzNp3u3Dgt7HTmnQ8pws9",
	"3znE/YnTdFteGzp+F/cmVlUunzvWSAXwGWKOXFG/BR/fgo+tgo/8zPJdyWFXXEki3befE63UGOIkbEm+",
	"fzR+cYonACsCGadwTr15RJPPWhHavCHm9K8c3lD4KO8iPIU7yT5ATYhzrb7W+spBcgLztGyvZiI1szGm",
	"wzCSC2QYggj1dAUhKXgQoYdrqUiGlyQBFv+Y/xL+8tsvP/+TnL+/uff/+fe/W/VeJA5kjQM5UgZWhWC1",
	"xiRTRn22kxrvLa2b9VA15xWhS4Gzlwi6JGz13LlKzG7FNxqrlVR0FBNwPZY28sAnNOVNaQwHHzhQF8ZU",
	"xT3GrLqM+mQac1ywTGXJqMTkNZKRR7xmo9GJ4fgqPiRgiG2C3tBaG1nFAvjdHAcxPCYcahQyoxLvswpS",
	"A8NGoqJC0bdqzbUCUqVmGew1QvInU93P0diX09SnaWgDDecq1Cgh6IEbYA5iTBkFxDgKGQedwXg58mjn",
	"39nnf9soJBS1dhvoCCm3EUDmrMaU+T5o9sUCBCrMMg0xag+gki/qtDyn9RJqZ2V4GmiI3ZlZKcMA4VLD",
	"kZ2FXGNaOBxj3NMA2uhxA7QNs9PMSXEpJHRkprbWcz9B9xFuXxbCgIq8VpikCUxolec1dNZIP6YBdVTJ",
	"DVW6oVJYxYXSOGP7QahvheSYUClMigs+VsKu1zEQjGmSZBbZlkbHbsEGb8QL3RZ0XIRlWf/SRrNNk4IC",
	"til5qy5tTJM6ihYscTKxEY6i3ap5Sn9d70ISERF3a9RBKE4xOVMeK4En11c5w9L0RHFQPLrUTVhCYglj",
	"OgFf6XgZPSJMkqFiVfCWMtcM/mLauQaTKu2LHVv1LryUf9cJ3CO+emce2krqJCYUuI08LPEEC7CRG8RC",
	"qq+EZBxPwUYU5D3jH3a3d/EVHU5D+SJmddqcnZSWcdZfo7QPEfk6d1PWUyUq+wfNfXTB2SSAEJ3oAz+j",
	"PT9eX1+oJFyYIEpneocdc6yILtOmxjpFKtuB9BCxCtWPcYipozIdTWn4GAWYJu0HyZpIMsObpJ1GBVVJ",
	"4VGf4DXG9BQvUnakbTVONt1L0JEMzSCIkAeT2MQDRIjlqtfGLX9LMkgKxdSKzl+O8jgwF7YMxFK7kI5Y",
	"SyBt2VGYJZMxJ062bR3E6XnqElcU182PyGUeoJ0QS3cGImlcSmTIjCgluLqLMQOAUNlp5xsTKmEK+jg6",
	"ObxdCitmjEsbzcpSIeIwxHxR4rrW28aYXs1YHHiKL8oLECGBSoRdzkRRYEQ6V+CwskCJ0pv0XVaNzuPM",
	"Tuz8Io1B873N1jQOlXJv28xpb3uqbW/en2Rv2blrb98ouXZKaocd+DjDyqRuMKeulWI9LhPGN1qdxdJh",
	"vsMxncIm5CfqK8WrTRbPmu424esck0DpxfrBHmAvIFRR0XRyKYeRS/v2QrehabGtj46SbGeOuXJbupo0",
	"Ont79GZ0cnT5w83p8Ozasq2bs6Ob6x+HZ9ej46Pr4YllW2fn16/Pb87Ux6M3l8Ojk/83/Hl0dX1l2dbF",
	"8PJ0dHU1Oj87GZ6N9OjL4dX5zeXxcPjzj0c3V2aF10ejN8OTi8vh8fnZyeh6dH6m1vr+/NL8fH5zff76",
	"8ujsh6Hef3R68WaooNE/js6uh5dnR28MaG+PRm+Ovn+jBp4Mj07ejM6Gw5+Ph8OT4Yl1W3XOybWDxKCm",
	"9q3OPdfEjkspbhLALtuWE/ODSehzR6Jj3MaY6o5Ik4CItIKuf3sl0gO5naRGbDhlIxqHExWvTBgLAFMb",
	"GUhtpEMpfVDnI/CIjoT+7uNARTnFLNknH8EzAFUG66plaSyhRBIc7Il4OgWl1Nm8ohVu2xaNAyPiuvSp",
	"G2w0UneGWtvF5qZTT5zTTc/YsKusdYAnEFRojAhFN6O94zcjgysLiZTg2UglenPwkM9ZaE5tsJylx55j",
	"a+5GccNlMZVjC/3Pf/03Gltv3ShGx+arpeDw+OLG/LZcB1/yQim9S4JjGFXB7l8z0DE8UE/XhYQ+MNAl",
	"60URSSNdutKdOEJFjyQiEgbzTBIgP7AwoqDDNUiTsFoOl+rZieStPiw8YdKhTJqoUNNVMoRzhqxN64aN",
	"6aDCBMWUEELGFw1BfoO76ST9TmIVzTc090VDEuBjqxq6ZwutT7G0CdWA3OVdZdgz7gkHFwW9N1Qp4/6P",
	"q/MzdGVUt5jmKrFMl9aRRca8HY9jX6J2s910Wm0lWef6AMk0+alwSjO2pKUqjoqjiHEpUNpMjYpbf4DF",
	"PeOeGCTljpBQEsahjUL8UX8Y0+TgwEbK8OsRhix6TPoRpKtPji5T1zFAqRN6Lxh1DIkajE/3NBp7CRrF",
	"X52cpGW+LGWu2rSpyE+pk8s4CLTTclr9XaNVCnBr0OprHiZ/2FYYB5JEAZz7RYYWQ9eyRa84Ai3Cm9n9",
	"3C4tgX6cBjA4yBRJZQiRqRoVDgpfiURdC2YfU5Orp27BQa91IURppymHDBBW6R94uoor3v10m5rodDct",
	"JIUrHD9l66SSs3YpnNZ4ErBr17wEwQJlOd2AAJWOIB4glUt7ChNdvRYQgLuyXp/sXqiE12vXp6yWUFMu",
	"KFP/FEfGkCewFq3iTlIy/gAL9NOuskQpdkveeOQXzCOWxnTBrzEOhJluF8a/EtlCmIMaXkbs3U+3qYMn",
	"AoU4emcAuX13i+lioBY0M83Xwk6L/no1hafOgTBdGK+UjtNipYVUJF5oSXK3sMo5viZjp0W5bDxmRh+v",
	"fSRXNyu8rlOzwt2Qz2tqKnuUJHgqtzGpTxOQ5sPvt6cpLytu18/UHHQ+r58pdabLjDDe9TFlXW6OKqH5",
	"Eywco5ARJtwon0p0p4yT34xMmpp7IHUJvjGm3zM5S9SEekXtSDShUfUmyXoLa2AlRbxysbHgATbUmUfb",
	"nhKBc9RaYu9T6X7yw5heF+JoF1NGiYuDut6SQgmzfOO7tH7h2lRZCsvDnquT99Fy7HGAhchPk2oUsDGm",
	"xywMGU35RqgbxB4M0PaV2MaYHnnK46tgSjKurOkiOUtAbiykiuAV8mgCC0aVKQMBteXblV1Emwd4ib3K",
	"y5XlI47U8KTGUFmZVBIwRSzCvyrfT7R/xDwrgxYCdo1Mvr7x2joKGxpsBJosSoMHytW/PR0gZaFtZOLk",
	"AiGnKiW4Y8JObnio4ccpDwaIhHpUdkJgpzcfMxaoCScJpwYI9N0mGyWWuTBTL2z4OMh/psxTkZzClLMA",
	"RQFWs9W6wMWumnNlIB0gF0fYJXKhvjwzew+QjnNtxFmsYue7AOYQKHJcz7QtiF0Zc0BzzIkiTRqKFERS",
	"i7G2IoY9qU9ZsiCGcupTkmRYgwNddtXgaUUg4oOwBu+UtTGg6lG9ZvZOwYSxon8UnvVwq/IKN4q1pHF3",
	"RiRomK2B9fGgf9fvWrZl/Oqg/WDOCYti2KqxV1v2r5V081vb2h+oba0UDGzdstYedHsv1bJW8hFPbVmr",
	"d6J6zaUGtdLYcl9a8ae17WilwZWHTF6shUV5yaSnY/tulnPjNvTmyEEeMxqEudBtGabQELsShZjGSiEf",
	"74AZ3p/+2HxiB0wpzM6bLsyZXnraZnQ8xRfpwyiNlDYMWxzcF7OD5+2YyVuilrj99KpWSo9XokSnMS1X",
	"uFDqyDepcm2RhOUt7I+EsvoCghY0E49LzKcgxdObEuYpFSvpWbnknfe1vVTdu2wEV7bUWHaanRrAb+vy",
	"AwFuzIlc6HKakYoJYA78KDayYf56ndrUf/zr2loqBf7rOtFYNtGhVqHanAaN4CG1Ikrv/1rJ3VMdSOgt",
	"ytdize1VQn2W3gnGrjQlkuWOiZPj06zx8dSYQHR0MUo9r26KSlIK8ht46B4vlEwbazmmJU03bZtJvYN6",
	"pTYXk80R6nOch2OF6nMSAaut/dyVox31xZDOME2uFaiYhwkciN0MLr30mGani4wTfUKHPBBkSvXif/kL",
	"uswDUBU5fvddwW6I774boBOTLUgIo0BbWgWxR3xd1ZRJ+sD8VUiMKUI7b09XZC4/xRPgFNSy1SQGzVkQ",
	"h2BrK11IVXYNmIW2PQ3msUojwMuMR9oxJ0yHXDknqDRhKRg1Z/Kqs9aJgLhAhVbQJEI9irA7A9RuNC3b",
	"inlQOFm8v79vYP2zrukmc8Xem9Hx8Oxq6LQbzcZMhkGhJcBaIWZKwdLSTV5AebAtFgHFEbEGVqfRbHQT",
	"fdQ6treiB33wyZqCrDNq2tlqUY7wlFBNvYAIubLPWhRr51m5QWVU9e3AOga1NNSG0CPPGlgqTKjpjhYa",
	"mfz5u3efFSek76Bpp5k/hFZwbMWb70uh26elKqmuoCeWVEu7Vl6pHLWMOUURcA3Dio1D/NF4VeWbSntn",
	"x1it2naSvHbfVL8Xq/fVcv0y2K81j1Ywc4lvml36AMXgJBIk72fAzUFTo9LijPJWmdQnLlViKm/vVeiy",
	"3DO9miu3lafl2s3mBq87bPa+warLFDUvHlzFuhDgx0HWHaRUs2ugqdskg3qv8EibntJaP6X8wIKa1Fk/",
	"qfS0Vm8TyOpeh9Le3PQjJXq7QpR0FZCJGitzrEuwysZQuF/Zi18wKyrWcfKUeHQiVFqs9fzVqrs4r1A1",
	"adZO1YMwYhKou6gzQwayuosga+zQeZK6V0FdZQO3UYeKBlRS6C2fYrw1QRwI+T3zFi+pKum7j8VXJR+W",
	"tLX18iBUhK+WI+mpgMj0OFgUFPhZAHzkmbBy092EeQuUdm4j48y/nGXoNvvrZ1See9LTDtdPKz/8qWa1",
	"2xtsVnoCSc/qbgpi+ZWqZ7J6xkysupOlB+9td4nbGMkAJNT1PAVgzOUj15bKdsxM2ciO1dEiH7K3+jXe",
	"GtfbrbH1tepmUK1Tty8k4hvIT/ZG3/PJjWHLarmx10fl5hLQCr8yWSAixYoQ+weQX1wgmr8P6549O/gf",
	"Ll8/gHxOozTgMFt4KoPWcUdtLHfNyXQKXKB0bHKAial5glLlYzW8a4zpD4WjCRUHFk8hzCWmAKamimv6",
	"KvL3EpKsuE7KL1OQ/6yynvGszrpuKZbfQoG1KpfJ2+aK9xzll9VVl0rXwLpKy7cKyxepsIga1lzWFFQw",
	"XdQcepjz9qSuUtuIUYd89Tzxa9dQvtVO1tROnlQy2bxS8lw1kWephfxHl0C+YuljbaDwrdJRCNOfEqe8",
	"ZA2hJliovk26faVgowLBZ8XGTy4I/NHqABtJTOm/Vrxw8eDJNYMtSgUvIxrNr2L9/ryVgKQp2637p1K6",
	"hU5UjsPNdYmy1MT6n3foi1GnwKeALnQnkm6c2+8c9nd1NHLGJJhXMQoNbjqnz3L8vCVghxcbaYRd7pMQ",
	"Nlp+o2NXd62TR+8alAXaYPgSMr1JHBEqUjma+H974Zji62iV6cH8yjGFASL7rzL/+TpuhLo2gih3dj6t",
	"3LCqXan2rmQynegra8pG6MKATvnFqipEsafoWasQjTE9X+oQq/QwJiGnNnERhzlhscjSz6Sh8qtUMsy9",
	"Of0vZdLMyc4fdJIMtZrN1fB9kYLHSzrzauvwt3pBuV5Qco6b1gtWqPJzlw6S+56jE0TE6isJ9yQIsnsJ",
	"iFFYXXQodis/segwOqm/szGmp7GQSf8kOjm7clqtdid/8yDEEu0E7B64iwUg3W1H4xA4cU3v4GwRzYCK",
	"3co7CPV3L2gWaG9Qt/sjFDtKfeRfttixtPUjz4r/Losd+fX95F8l/dkqHqV/Vbscr1Svfm4UvyQ5bsnS",
	"rctxHzUva/KB5f/V+6Xc4lqh/3PluBVhKtw10Gws3jJ4d6t4ZKyzYbJp1t7DEdnLO6pvH/43AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
