// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ft7c+M2kv8qKGarbNeJMiVbfmhr6kqx5Il2PbbWj1w20ZwNkU0JCQkwAGhbM6XvftUA+JI048mMk9q6",
	"v2yReDa6f/3rbvCjF4o0Exy4Vl7/o5dRSVPQIM2viUhYuBxHE6oX+DsCFUqWaSa41/duF0AkKJHLEAiL",
	"gGsWM5AkFpLoBZDM9G6Td7nSZAaEkkeasMg9J+PhlOsF1SQUPBYyVUQLMhhN/E63SyT8njMJKa6rP+U+",
	"6fhHByRcUElDXB1JBJ/j8wvxBDKkCkgCGt+0CM/TmfmH8ogsltkCuCKCJ0tsbxajNJWaPDG9INT1K98B",
	"j5pviJBuyCn3Wh480zRLwOt780TMaOLTXC98uyev5TGUTIbyanmcptguc1L0Wp7bVuT1tcyh5alwASlF",
	"0ab0+QL4HOV8dNDyUsaLn50WjqdB4sj/+wv1PwT+6ftd94///mPQOuqsiud7//03r+XpZYYzKy0Zn3ur",
	"1QqnVpngCszBDhIJNFqOnpmy5x4KroFr/JdmWcJCioe8/6vCk/5YbRp1QFOWeH2nHFZW4yHZ2RTHDqF2",
	"HgJ2IhSP0pSHuLggPDo+Co4C/xhOj/yjXgg+nAQnPnTo0cnBLD48PZl5LU9pqnPl9Q+D05anmTaivy7U",
	"bmMCt/PBxfVoMPz3/ein8c3tjbeqi/pvEmKv7323X6n+vn2r9kdSCmkF1lT2T824annf0+gafs9B6a+U",
	"5DmDJCI7EubiPhQR7JAUNZELYzaQZnrZFN3x6cFhFB+Afzg7OvAPu6czfxbEPX92Eh30Agg7Rz1oiC6o",
	"RDfm1gqlXTKpWXwpvfHlj4OL8fB+cP327t3o8vYV5PeZaVct71zIGYsi4F8pwX+LnETCSGxBH4GoPI5Z",
	"yIBrkoFMmVJMcAMwGUgEG6IXTBGRgTSDN8U764YH0SH0/PiIHvsnp0HHn4UR+HGne3DYOzrGJw3xHlTi",
	"nZTTkQg4g6iS6mR0/W58czO+urwfji7Ho+EriBUxGC0OwTekGiKSK5AkEqAqaVQi+IwEVi1vzBFlaHID",
	"8hGknfPrzmPASc7hOYMQlwQ4EhFhmEsJEXlasARIJkUISjE+N87C6UXzIDrR8UkQHAf+SUyP/eOjKPbj",
	"0+DUj7uz49PDkPaC07B2EL2mntvNEGV2YxdRV/Hb0fXl4OJVVHvbTKuWdyn0uch59G0AuxVYywM2MNSU",
	"2umsdxQHPeofRSc9v3c4i/zomB77URD3jrsUDk6OaUN9D7cAK44dm8WXIru8ur0/v7q7HL4mnFbzrFre",
	"HcdNCsk+wNcK7UeDMjWTQK0PJRh6QhNFqISCXURoDjRENbTWULCZpjxpxwKCD734yEfr9+ksjHyo4UFD",
	"np1KnoPmQkr/Xwr17nJwd/vD6PJ2fDa4fRVIWJvSbMttd5Zr8kSt4mRSPLIIIqQ3TBFm8RnnNyI0nb8F",
	"AgrAv4a5IGrJNX0mjDe8XIx+rynrLpycdjrHHf80pif+yXEc+AHtUL8bnp4GvXB2FJxGdVl3u5Wsq3Wv",
	"G/v5YHwxGt5PrkdnV5fD8e346vIVBL0x36oc03CqUnrNbuYxKegYiUWSiCeEwevzM3J8EhyTiRSzBFIy",
	"NLJUhscaYnx60J7yKZ/Yo1NEaZmHOpclxjLDpO2akIYPJmMSU5bkElTb0NdMIuRrZnlgcVrra/whTyn3",
	"kejQWQIEnrOEcjusyiBkMQvRdqwLsbjOQyAitsTfrr895TcLkSdRoWuEhjiEGXJ9pRE8QoJLc+usaPYm",
	"O3pJpTcJcF3H1vd6x9nv+ZYAhqlqrw0PxkNokzsFcZ5g0ynXkoa/4QniQUUwy+dzxufr+/hC0mbF4vW9",
	"XDJfQgxmwm1bKoxg4/BubyfEviQosPoqDBUsp2BcH3SroRnXMAfjupxNvaAXKk9TKpdr507McPWtfwnn",
	"rPZlH2wc0/WYlOIoTmtZ0If61G1yi4fHlHkTUi44C2ky5fYUUSTubHieev1fNuluq+brWuuxRMu7Ht1c",
	"3V2fje5HP/0wuLtB2G5txZiWN/j+6tq+v7q7vb86v78eXL4deS3v7nL8bnIxwunM65KP4KvBj4PxxeD7",
	"C2w4HA2GF+NLnOxsNBqaxutOo7WFW75vHMDmDr9Uz1b1qPUXz52t071CUd6X3cTsVwg1HqOlL5sHeQ2Z",
	"BIUQSygnV5MB2b3KgBNHdwZz4HqvSBIUHtniHj5joEgEMeOW+CJZcL41T0CR3DBK43TwoI1JhpRjIKVC",
	"kUE05VqQiMVmw5okiDuK7L69uPp+cIHO8O5mdL2HOgRLQxZSqsMFRITOKYLIlDstLuZK6AyQ+yUQaiEt",
	"WsMjTXJDxxknmWRCMr0kQkYgzU7uFEQGZmZCL5CeUA1kd3J1c7tn+udZZJ8Mbs9+2GuTK+4atUjEVJbQ",
	"5T2nKbSm3MrpHqVvEx4lTjaZzi4g4IaImEtjF0hWWQhm8Cm3E7ZMmsT6ZUXcMeEWagydzETkBANyjiMb",
	"v3VwerS3zcPYZd9rlm6x6VuWgtI0zcjTAngtaWQg3XaNnDmbRaFRi1xnufZtQgd3THMt0JOENEmWRIGu",
	"b7ESuCLjmytychR0iNV9m7rAlX0Q3ERJ1sseBuvQ3Q26R37Q8YPT207QPwj6QfBz3YRQdr7ZIhoLja54",
	"sixSPBvw1hDBukSuzD80IdYzA/qT8n2JszYIUCTLZSaUVfIZLOgjE7jdmzzLhNSKpFT+Fokn7jast3il",
	"kVULtU6Z6wk4QkMplCI0SQq1UYVWZFJEeWhJEH9kUnDs4rXqCa1ucHiyTRA1TX7R1WCjjcxiifPLrDj9",
	"BW6XoUZjHIweTcbU7I9H+BbpyAwqqT7CukTemnCLrNHoSZHgq++r11vP1G1sEgzdiez+YponulCM5nb/",
	"ZwF6AfXt4cYs39DJ0lCnR2iTIVNmQNsIwRBNkQs95RXoRLk0dKSBjxGEzKRB1jbcUNOZEAlQkw1g0Zdz",
	"pbUj2WareABTztI01+ZAaaxBWhtnghu8JeNhgdXC2QEeqSVhEJFHRqf89xzksmIQRPBykL8TFjeIYKsG",
	"A2QOHCTVKDFydzceGlw4N+xb1fLOLi7FpQj+iPvcFNn21O/rpnBfxBHjd+4Lv2NCsyhiVmyTBgZ/HoK8",
	"f8LSR9UBklEm0a3ZyNg4PkuEnUY6F0gYD0WKGla4wvaU3zYUt9JFc/YsNuBhlqzKgSufYuLLZ92e8jGe",
	"4JpPxQGbR7ptItREnKS2pik/E2kquBvvN1jaYkINqfo1BGsha0bq3irCEWyBHRBM7lnUt9m1Sv3xnUPE",
	"fvGPgSp8IWHOBO+TOYi5pNkCIco9xNeagaw64S+yG0pm/JhZCY+ojFoEdNjea+rfR6+OtX2v2oJRnLk9",
	"11z5QJX2O4amgfT6XjF+RbNrhC3bWuUpMzX4ukB950CnXoFC+x+LKsdq6hlt+AwMfMJHf9IWzcyfscZy",
	"EVvNsmZ5ZcNXMsEa+doU3A3SzabLJrXkyTpUfhIZp0ZbLD/tkwGOACaVXVf2wkUbkS6VhhQ7IZVtdCmb",
	"G2Op4ltU6wbDRqfSILELBpLK0CqxIbJ94jylP82D4AAwJJaNuMquGeOVm9F1MyApX23K1LHlhsc0md2m",
	"eCcFq7bQhRtyQnbrNoTJMG5bJCzqgiYnPuULNkd/W5JzwyQbu46ZVNqI3yYVJeVz6JOO3wmCwNYkO0HQ",
	"J2fOqPat4EvPbJoEHb+HjW6cPTfe9gI7WB9X6JdLqZrU1byzNXRP6TNLUdw4jnE67ue2qL6MDbYXczEW",
	"M5GTE6SJlK2amoAC4fYZwlybJH6DsE95HYurmu9GDtDIEyczIzpCVsRzJKPhb3QOLpFi+YoN7NrEQbkz",
	"Zwvkw6Kj0xS0CfG0HwE3xd4xSg4xEtGj8I0kEXMWkhlVxjsRxrPcgPx1mV2IqKYkliKt2y7wOeNQLL+K",
	"MJmyu3TerojmamFcWWTZRK5iv7lefMChG/sgb0hME2XmtA8+TjmxC26jybabpZ83bwgC1VobKRLAV1OP",
	"RinjU2/KV2YZdb7S6x0cvchl7Xa+KpZLqNJOHH80oHO9mg4DBU35kqQiQgCrkPL1Ar1e/7D3DYHehodt",
	"ec8+hcwviwzmuoVVZkTLdVd6z6IVgmaW5JImNTfntTzF+DxPqCxvF1RIan/7KeV0DrIdhWmbiX3XalXm",
	"ZS6YLVdvOHublU5BKVRMhNWEKYwcS1gyci5Ny/nrgy7BIUveQlLQCxE14sht+QEOz/o+o3O41+I32BIR",
	"3+Jjsw4JWjJ4LFJ+2JNgT/SxElSeaNUm49gWzM2tDYyKXBbD8EYJLloiqTDJEdvJ2jTGkWYuUxalGOfU",
	"YkZXjM+oVFYXw4RVe6o0CJb/ePw5/fnDzz/9i139evcU/+vNG+9T1KHMwtc3bMQo4vUMmKPNa/VSgowO",
	"JKNey2MaUvVSNcPFsZV2UinpciPNVy5vM7O3Mtn0WBR1IRqiIm2WoUYTH+dPGOWaXI9ubm01QkhidBM3",
	"8tnkH6uSDMOzd0WLd06vyzOzg1rmiG3x94gvKA8t8mMoJBRNFNkdjCZ76wqqbAq/kLIvJB6rzbuwOW+5",
	"wANXe3Z9N6xhudnKZO2QzLq++478E5bkHKjOpfX053mSbB3AnbI11yLccAkc08DqmV9FwZZAIwj6RUgb",
	"kfHQTpPAM0MOGbME1cLVJDIUt5kUG02o1IwmDliVyzKSfZvQ28MmzcOzefMF5VHC+NwofMJC4MpgmLvl",
	"NMhouADSbQdey8slAtZC60z19/efnp7a1LxuCznfd33V/sX4bHR5M/K77aC90GlSKzx4zePGU/Va3iNI",
	"ZbXrsUOTbEE72EVkwGnGvL530A7aB5byL4wl7NfNbA56u7WpSuGMp1A18Veia1VCtZlWQy5tSs2c+Xnx",
	"2ngho4wPtstDLV9hZjgbXfhKL21pTYK9nmIYzUMtpnizY2nyzoN541JJb9DdPGy2RZK9QwaXQ7LW0Czu",
	"yi22tjaz/vvZsrY6t4SSE6vwgew6TrLXfIditKuo5/FMF/O0lvgt2nrmrKz2jyMn/Enl1eqXD3/5Rj9w",
	"AfTR3Z1yRToMW5HRm7amgGfFsOaBHmrET8IjE7ky8GD9ohZkDro57xe6AHMz0GSvalcDK8dXL0dvUIl1",
	"YbyzrN+FNKW3KKM8nUtueI7dq73QQ1K6dO+mPAYMiepuM+clxrQKPm2G6wVtUkxogy2mCIYb7S0ByrZd",
	"pvTZClixD9DYaC3A+7bYZlNE1hpr9mVC5ixLlrZyDYbXtEmZLK8gc7bcMMWHPmlWiOoW+dA3vBtflXx9",
	"ZKXyrUbt2m4z680UyEudPqGEduN/TAExGKO+AjRZ9D+JIy2udKSFRUcyW7bJiIYLx/ZtdnfKrcO2RGqH",
	"qnAHZbeDU+y0MagrdW+njkU7BmndgZkAHSczEi6a4f91PMLfNSTacjJ1rNuEswrl1vGstdazeRy1d5+Q",
	"eoG+2+1hfYT1A3m/dqG3GwRfcE/nyy681AKELbdeGvQUcXvV8g7t7NsGLVe5X7sma7p0Xu7SuA9mOh28",
	"3Km6S7pqeb0vWdm2e4/mLo+93lBsuhZ/aTo3MVvpvN4bSr8tpDozeqMIJRyeNsrapuyBca6D5426x5LQ",
	"KXcckCqkpIbtkUdGrfti0QNZq4kYON+og0y5C52fWJKU1ZCqGLLhne3KJ1Ue9TPeuaxbbtDV8XCjRvQ1",
	"q5vy63pFcrcM4rvdvc9+IHBT3fVP1r4VwNdnGMEwbssUyZd9TID9RsVnAl/9kcAaHrDI+9rvAf7gxwDv",
	"bagHSn8vouUrw0bxsUH9O4fVBlh1/pRZ1xLELolpbxEQlZuLnnGeJCj1BdDIfeVyIezM2+8cuQR+MUzt",
	"imi1wOq4i5CHZqztnrZDke4/dvY/X6WoX8fZ9gHHfzTKHganL/dofnOCvbrdl3utX0Z9PUw/c3naGi5v",
	"R/ZVq4oja3Uuqy4J6C3J0KF5jqDfqIuX+OoKPhCxIlUcUu5STDmPBAcHeUjWFekGh+RSGKwCrongNW0m",
	"Zg1lCb2awsGrmnKlpeBzEgqumNLAwyXxCUJImpnEngkZaOTySsUHXcXykqWtSE15MZPFaBdlHJq1aWJu",
	"um9zI1YWn3Ij206xarLf+AJtC+s53JS9s3t7NE27J7tcEAc7e3+pfRy+3KP8WuD1VNyKvtTCTxGXrYmR",
	"axtlGyVWjM+TMp8/WxKmFXFu2Si2S/ay9aRwh7yFjZzwNiV5C/pP0pDgr3M1LjGx7mz+/+sZHvJLSpZR",
	"HW65XnDnkpCU209ZykLD0l2vzBrZSrJrk5Qvq94hsUNvaB8Za5IrUMSkPafcsLh/3Fxdknc4NJmY2ynI",
	"L4uLjW1yheyw/GLCBblUQlGc+vuUi5Rp3XyZQKxJzsMF5XOIbMrpgedJ8oCQGyZAZUn4Xb8il1jkaN0e",
	"dt+51OwNcHelxuazzFxLkZMnyrUZ1UxmfYFj1EZiNjluDmHKBXcpkFLkVUDinIx/u8zAfoeIAftD3WzM",
	"gL4Z67/QhB6KVY/LOwzm0r6ypdLqCwe33pqvc7W9XTbnQkJEWEwUgrMN6qle4F8WmV9VioPsVkM46a7d",
	"mtjbCPx9UitfbkEgK+nXA6EvIdjrgvxzyPZfiIDFeW7i338udf2DkPl1XPeVgNbBweex1nQxQ1jdtcUY",
	"DEn2q7LJ+7LrZijfKFA1inW1FIgLW8t5V+9X/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
