// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"3Ht7U+M41vdXUXm3Cqg3Dk4gQLLV9VYGQk9machy2ZmdTj+NYp8kmrEljyQD6a5896eOJN+SNLdmprae",
	"vyC2Lkfn+jvnyF+9UCSp4MC18npfvZRKmoAGaX6NRMzCxTAaUT3H3xGoULJUM8G9nnc9ByJBiUyGQFgE",
	"XLMpA0mmQhI9B5Ka2U3yIVOaTIBQckdjFrnnZHgy5npONQkFnwqZKKIF6Q9GfqvdJhL+yJiEBOnqjblP",
	"Wv7BHgnnVNIQqSOx4DN8fibuQYZUAYlB45sG4VkyMf9QHpH5Ip0DV0TweIHjDTFKU6nJPdNzQt284h3w",
	"qP6GCOmWHHOv4cEDTdIYvJ43i8WExj7N9Ny3Z/IaHkPOpMivhsdpguNSx0Wv4bljRV5PywwangrnkFBk",
	"bUIfzoDPkM8Hew0vYTz/2Wrgehokrvw/H6n/JfC7n7bdP/6nr0HjoLXMn+/8/797DU8vUtxZacn4zFsu",
	"l7i1SgVXYATbjyXQaDF4YMrKPRRcA9f4L03TmIUUhbz7m0JJfy0PjTqgKYu9nlMOy6vhCdlaZ8cWoXYf",
	"AnYjZI/SlIdI3C5IKaTaDcKDw4PgIPAPoXvgH3RC8OEoOPKhRQ+O9ibT/e7RxGt4SlOdKa+3H3Qbnmba",
	"iOAyV7+1jRwH5lqnqre7G4WJn0rxG4S6OWN6nk2aTOymUkxiSNSum+676cuqZP4uYer1vL/tlpaya9+q",
	"3QEewfK3bhvfImzZ8H6g0SX8kYHSr2T8KYM4IlsSZuJzKCLYIgkqLhfGyiBJ9WIzpw+7e/vRdA/8/cnB",
	"nr/f7k78STDt+JOjaK8TQNg66ECN00HJ6SG3xist6aTiKF7KbGaX8qmcZWjgb8DuR6hbNrxTIScsioC/",
	"kuH/ERmJhGHwnN4BUdl0ykIGXJMUZMKUYoIb95WCRFdG9JwpIlKQZvHN0pi0w71oHzr+9IAe+kfdoOVP",
	"wgj8aau9t985OMQnNWnsldIYFduSCDiD6MVCKAn33QrfLwUMCGj+GAlCqiEimQJJIgGqZF658SMMWza8",
	"IUeXR+MrkHcg7Z6vE1+fk4zDQwohkmS4T0QYZlJCRO7nLAaSShGCUozPTORyarRZbq3o8CgIDgP/aEoP",
	"/cODaOpPu0HXn7Ynh939kHaCbliRW6duRfZQRJlTWWJeYUB2lTcxnE0ELRveudCnIuPR9wWHjUGh0Afj",
	"EzczuTvpHEyDDvUPoqOO39mfRH50SA/9KJh2DtsU9o4Oac049jcEBdxjag7xUg5zoX078w1DQUnOsuHd",
	"cOSJkOwLvJbH/zYur2JwaFOhBIPEaKwIlZADqQiNjYao5NbWcuC2mf20Zb2TD53pgY+uyKeTMPKh4pxq",
	"7G+V7O/XCSogz0tlkPGaL3kDSaxQZrjguDPJNLmnVi1TKe5YBBECP6aIC1e4v+G4mfw9/igPVpcwE0Qt",
	"uKYPhPFaQJ9iiN8smjYcdVutw5bfndIj/+hwGvgBbVG/HXa7QSecHATdqCqadrsUTUn/Kz3PlLIYIj+V",
	"EAoesdxXf6dc1shaFmsacFowuz7NPCY5riVTEcfiHl345ekx6e53DsnI0k1ODOuVSQhMhtHda475mI+s",
	"pBVRWmahzmQRH5hJSSxNmM/0R0OCh88kqKbJA1KJ4UozC6hz4a7S+GOWUO4jBKSTGAg8pDHldlmVQsim",
	"LETLtOHPxiQeAhFTm0FZ+ptjfjUXWRzlqkloiEuYJVcpjeAOYiTN0VnmK+u48SkLWM8kqiq5etabyyGR",
	"MAV7BJsFMlWesxZ5eQgr5L0QpdpTez0vk8wvtt1EcW4Ka7K5vh4R+5IgP6rUGOxbbMG43mt7DUzSWJIl",
	"Xq/T7Zoczf5qmRBvt8XYPAMTQp3VPaESKksSKhcrIidmuSp7ngPAyzPbB49LyKXsixz1WPngTCsZjmf7",
	"+GpU33h5sG28Ml979rw86vnwMKeZ0vCCPTf5vucTPBHyRbuJTPti6kvKZ/D8WRlnqC7I/5dsVgDKF2xE",
	"7yiLUYOfPykCGsWMI/dDgOglFK6Cgcbr85xPVat6vXI/0/80vAcfLcm/o5LTBKPFR294/u/+2fCkf/n+",
	"5sPg/NpreOcX16cXN+cnXsPrn10O+if/GfwyvLq+8hre5eDq4ubyeDD45cf+zdX1AMec9odng5PR5eD4",
	"4vxkeD28OMeJP1xc2tcXN9cXp5f98/cDr+HdnA8/jM4GuJF5OTy/Hlye98/Mq/6/+8Oz/g9nOPBk0D85",
	"G54PBr8cDwYnZuzNef/m+sfB+fXwuG9njwaXH4ZXV8OL85PB+XBw4n2yxaW8rvXRc57Led3cDX4qGCMm",
	"yGV0UjZJWHdTl5BKUIgdCOXkYtQn2xcpcOKSiv4MuN7Jy4i5SduAjs8YKBLBlHGbjSLGdlA0i0GRzKR5",
	"Bnyh1zegIKScTICoUKQQjbkWJGJTI1JNYgyoimy/P7v4oX+GoPDmanC50yTXc1gYjJ1QHc4hInRGMTqO",
	"ufPR+V4xnQBmWDGEWkgLQ+COxpnJkRknqWRCMr0gQkYgzUluFEQmhk6EniOqpxrI9uji6nrHzM/SyD7p",
	"Xx//uNMkF9wNapCIqTSmi8+obo0xt3z6jNy3JdECANQThG1AJBEiFFiYeIApIQvBLD7mdsOGKaRafKqI",
	"ExMeoZI2k4mIHGNAznBlBGSHe92DnU3QyZL9WbNkQ8S6ZgkoTZOU3M+BV8rKBqvYqRGKgilLFGIakekU",
	"3acp+eKJaaYFQqSQxvGCKNDVI5YMV2R4dUGODoIWsdZti5tI2RfBTenCwsf9YBVbtYP2gR+0/KB73Qp6",
	"e0EvCH6tOgnknW+OiMZCowseL/Ii8FrwrrFglSMX5h8aEws5ISKV9wWKsKm2ImkmU6Gskk9gTu+YwONe",
	"ZWkqpFYkofL3SNxzd2DN+Gz1aAOrFmo106yW6AkNpVCK0DjO1UblWpFKEWWhRff8jknBnQetlLzbwf7R",
	"JkZUNPlJIIWD1noPRjGYQlSTS3+Ox2Wo0QoQ6GuQU2rOxyN8izh7AiVX72CVI+9NUYOspJOjvAVQPVen",
	"s1rLXzskGBwf2fNNaRbrXDHqx/15DnoO1ePhwSyY1vHC5AR30CQnTJkF7SB0hmiKXOgxL51OlOH2K/4x",
	"gpCZUubKgWtqOhEiBmrSPhZtgJic/ZE92g76pq2iAMacJUmmjUDpVIO0Ns4EN/6WDE9yXy2cHaBIbYYB",
	"EbljdMz/yEAuSnxMBC8W+Qdh01qG06i4ATIDDpJq5Bi5uRmeGL9watJKVelMuXIOkiL4HZ5znWWbm0Nv",
	"2+R50o+YuPM5jzumRBFZ4ErjUc0HP+6CvH/CwkfVAZJSJjGs2YKSCXw2y3Ma6UIgYTwUCWpYHgqbY35d",
	"U9xSF43s2dQ4D0OyKhYuY4qpszzo5pgPUYIrMRUXrIt000aoibhJhaYxPxZJIrhb73dY2HZjxVP1Kh6s",
	"gfnijPFZI8+zcQROQGfymUU9W/Iu1R/fOY/Yy/8xrgpfSJgxwXtkBmImaTpHF+Ue4mvNQJaT8BfZDiUz",
	"ccxQwiMqowYBHTZ36vr31av62p5XHsEozszKNVM+UKX9loFpIL2el69fJpEVwJZu7AMXBU58nXt9F0DH",
	"Xu6Fdr/mfdDl2DPa8Igb+EaM/qYtmp0fscaCiI1mWbG8YuAbmWAFfK0z7grhZj1kk0oRcdVVftMzjo22",
	"WHzaI31cAUw7qqrseYg2LF0oDQlOQihbm1IMN8ZSFm9QrWsIG4NKDcTOGUgqQ6vEBsj2iIuU/jgLgj0g",
	"NypvorvagqUZE42rwWU9MyterfPUoeVaxDRtljp7Rzmqtq4LD+SY7Og2gMkgbnuNIL85YBpVYz5nM4y3",
	"BTg3SLJ26imTShv221q8ydZ7pOW3giCwtxZaQdAjx86odi3ji8hshgQtv4ODrpw91952ArtYDyn0C1LK",
	"IVU1bz1etMJ1qlWrTTWrIjfYfN0DczGTOTlG4kinpiahQHf7AGGmTWetBtjHvOqLy1sha7Vww0/czKzo",
	"AFmez5GUhr/TmQW0lNwmlPFbk9gRc5dEgs4kV4TmeU8Baoh1Y2Qb9cCxjNxK+M20BW8b5NYGE4g+u0gi",
	"bzFfOc6LPTQmsZixkCR0geZAymBapcPiyFunmMS8KI5UZp1M2ZO7CJhneJXUruiGrnuznAeZnn/Bpaub",
	"kd478nXs5Qcbez2CvmmJ477xfkpjBUsMwV/HnBDG00w30eCbUsRA3r0jY49GCeNjb8yXhpgqkul09g6e",
	"RLn2UK/K8mKqtGPKS1M9N6seSpDdlC9IIiJ0baUPfbsUsNPb73xHCrgWexveg08h9YuunbmqZaKWKSit",
	"BtnPLFqiO03jTNK4EgC9hqcYn2UxlcXNpNLH2t9+QjmdgWxGYWKqYHbUsqjYnDF7d2UNBthGTAJKoXqi",
	"ocVMYU5ZOCzD52Feo3SRfK9NcMkC0ZAE9FxEtQxzU+WAw4P+nNIZfNbid9iQK1/jY0OHBC0Z3OWlbpxJ",
	"cCZGXwkqi7VqkuHU3p4xN74wX3L1DYMoJbg8iiTClE3sJGvZmGGavcwtBooZUCWbdDdzUiqV1cUwZuWZ",
	"Sg2CxU93vya/fvn1l3+xi99u7qf/evfO+xaoKBpP1QMbNorpam3MAeqV6w0EsR5IRr2GxzQk6qkGnstw",
	"S+2kUlKrGNUCYEHees1v2fAUhBnGsCtc1J5hAlSCxHS6/HWam81PP197q5H9p5+vHb/FRFPGMRRLkZjD",
	"hYJP2cy08nBF4np80nMtRZPDmi3q3U/bmGR8KvK2Lg1Ry9e7yIORj8yJGeWaXA6urm13UEhiDAe5/GjN",
	"kpW1kZPjD/mID87oCoWyi1rAi2Px94DPKQ+NReDBUqForMh2fzDaWbUeg+DGvOh4CMlMV4BEoNiMN1y+",
	"hNQeX96cVMKNOcpoRYMMXX/7G/knLMgpUJ1JC1BOszjeuIBTQetL8izJ1Z3MAGsEfpm8W9yPHtrPM/GI",
	"DE/sNjE8MIS+UxajzvKZGZ4iu82mOGhEpWY0dl5fueIo2bV1yB0cUhee7XjNKY9ixmfGGmMWAlfGwbrr",
	"m/2UhnMg7WbgNbxMxpWuwf39fZOa100hZ7turto9Gx4Pzq8GfrsZNOc6iSvdQK8ubpSq1/DuQCqrXXct",
	"Gqdz2sIpIgVOU+b1vL1m0NyzmcrcmMxu1QfMQG92BapUOBPGVIX9JesaJVNtgdhgYlsJNDI/zV+bEGmU",
	"8dZOua2UWcwOx4MzX+mFbXVLsDfjTEZ9W0mF3m1ZdL91a964Ctg7jIW362MxN9gi/fMTsjLQEHfhiK3Q",
	"Zuj/PFlUqHMkFFBehbdk28Gmnfo7ZKOlolp+NFPM00q9Oh/rGVlZ7R9GjvmjMuRWb1V//M4gdQb0zt3y",
	"tBZusm1MRMzYJinYsBIeb0sfmUq4YyJTxj3YoK0FmYGu7/vM+GSuPJuiW+XOcxmVq9dD1nDOKjM+2GTF",
	"ZWJFKCuSU0T3BoTZs9rLgQaR23djPgXM5KoxPeOFj2kQJ3OzXCdoknxDmyMyRTBLam7IqzadMqEPlsGK",
	"fYHaQSt56felZOssstZYsS+T6adpvLA3ScCAriYpavyly5ws1kzxtkfqja2qRd7a3AFfmRwBTW5gufK9",
	"Ru3GbjLr9crNU5O+oYT24C9TwGORJNRXgCaL8Sd2iMp1vLSw3pFMFk0yoOHcpSK2KD3mNmBblLdFVbiF",
	"vNvCLbaa5KSie1tVX7RlPK0TmKkr4GaGw/kw/L/qj/B3xRNtkEzV1627s9LLrfqzxsrMujgq777B9dz7",
	"braH1RVWBfJp5UuFdhA845rd8y6gVbKXDbfQatgZ/fay4e3b3TctWlC5W7nQb6a0np5Su/1pJu09Pam8",
	"xr5seJ3nULbpDrXB4PbOUX7oSnKo6cwklEXw+mTyjU353rHRG0Uo4XC/1o033RpMwp17XmvXLAgdc4cB",
	"qUJIatAeuWPUhi8W3ZKVVo5x52vtmzF3ef09i+OiiVP2cNais6V8VJZ/H4nORbt1Da4OT9ZaW6+hbswv",
	"q43U7aLC0G7vPPrl01X5EVO88hEUvj7GDIZx212Jn/eVFM4b5N8/vfrrpxV/wCLvtR86vfArp082DwWl",
	"fxDR4o3dRv4VVfUDruWas2r9Kbuu1LVd7dVefiAqM9e6p1kcI9fnQCP3+d6ZsDtvvgjo+g75MpUL4SWB",
	"6xelaMqa7mkzFMnuXWv38eZK9Z7Upi/T/qu97H7QfXpG/WM6nNVuPz1r9S752/n0Y1dKrvjlzZ592Sjz",
	"yEp7zqpLDHpDpfbEPEenX2vnF/7V9akgYnk1O6Tc1b8yHgkOzuXZMn072Cfnwvgq4JoIXtFmYmgoOv/l",
	"Fs69qjFXWgo+I6HgiikNPFwQn6ALSVJTdTQpA41c0Sv/UjUnL17YRtqY5ztZH+2yjH1DmybmM5hNYcTy",
	"4lthZJMUyyG7tU9rN6Ce/XXej/KGBm5bt3uyzQVxbmfnL7WP/adnFJ8SvZ2KW9YXWvgt4LKxMHJps2yj",
	"xIrxWVw0GyYLwrQiLiwbxXaVaLZasW6R97BWsN6kJO9B/0kaEvx1ocYVJlaDzf99PUMhP6VkKdXhhlsR",
	"N64ISbn9zq3ogizcrdC0Vq0k27ZI+bTq7RO79Jr2kaEmmQJFTNlzzA2K++nq4px8wKXJyFyqQXyZ38ds",
	"kgtEh8UHTy7JpRLyztk/xlwkTOv6yximmmQ8nFM+g8iWnG55Fse36HLDGKgsAL+bl9cS8xqtO8P2B1ea",
	"vQLubgLZepbZayEyck+5NquazWwscIjacMwWx40QxlxwVwIpWF4mJC7I+NeLFOwX05iw31bNxizom7X+",
	"H5rQbU71sLh6YT6iUbabW35x5OitxDrXeNxmMy4kRIRNiULnbJN6quf4l0XmV1niINvlEo67K5c9dtYS",
	"f59UeqsbPJDl9Ns5oecA7FVG/jlg+y/0gLk81/3ffy90faHLfB3WfSNH69zB47622j40ylttHH78hOpp",
	"PYNVbdurwYxlt+yqfCpWXs/0a/2rWi+vUiFxWW1B1vLT8n8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
