// Package database provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package database

import (
	"encoding/json"
	"fmt"
	"time"

	externalRef0 "github.com/dcm-project/control-plane/api/catalog/v1alpha1/servicetypes"
)

// DatabaseResources Resource allocation for the database
type DatabaseResources struct {
	// Cpu CPU cores
	Cpu int `json:"cpu"`

	// Memory Memory with unit suffix
	Memory string `json:"memory"`

	// Storage Storage size with unit suffix
	Storage              string                 `json:"storage"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// DatabaseSpec defines model for DatabaseSpec.
type DatabaseSpec struct {
	// ConnectionDetails Database connection URI (response-only).
	// Format: <scheme>://<username>:<password>@<hostname>:<port>/<database>
	// Empty until the database is running.
	ConnectionDetails *string `json:"connection_details,omitempty"`

	// CreateTime Timestamp when the resource was created (RFC 3339)
	CreateTime *time.Time `json:"create_time,omitempty"`

	// Engine Database engine type.
	//
	// Common engines include:
	// - Relational: postgresql, mysql, mariadb, cockroachdb
	// - Document: mongodb, couchdb
	// - Key-Value: redis, memcached, etcd
	// - Search: elasticsearch, opensearch
	// - Time-series: influxdb, timescaledb
	// - Graph: neo4j
	// - Wide-column: cassandra, scylladb
	Engine string `json:"engine"`

	// Id Unique identifier for the resource.
	Id *string `json:"id,omitempty"`

	// Metadata Resource metadata for identification and governance.
	// Used by all service type specifications.
	Metadata externalRef0.ServiceMetadata `json:"metadata"`

	// Path Resource path or location within the system hierarchy.
	Path *string `json:"path,omitempty"`

	// ProviderHints Optional provider-specific configuration.
	//
	// Allows platform-specific settings without breaking portability.
	// Providers use hints they recognize and ignore unknown hints.
	//
	// Keys are provider identifiers (e.g., kubevirt, vmware, aws).
	// Values are provider-specific configuration objects.
	ProviderHints *externalRef0.ProviderHints `json:"provider_hints,omitempty"`

	// Resources Resource allocation for the database
	Resources DatabaseResources `json:"resources"`

	// ServiceType Service type identifier.
	// Makes the payload self-describing and enables routing/validation.
	ServiceType externalRef0.ServiceType `json:"service_type"`

	// Status Current status of the resource.
	Status *string `json:"status,omitempty"`

	// StatusMessage Human-readable message providing details about the current status
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdateTime Timestamp when the resource was last updated (RFC 3339)
	UpdateTime *time.Time `json:"update_time,omitempty"`

	// Version Database engine version.
	// Providers map this to their supported versions.
	Version              string                 `json:"version"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// Getter for additional properties for DatabaseResources. Returns the specified
// element and whether it was found
func (a DatabaseResources) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseResources
func (a *DatabaseResources) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseResources to handle AdditionalProperties
func (a *DatabaseResources) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["cpu"]; found {
		err = json.Unmarshal(raw, &a.Cpu)
		if err != nil {
			return fmt.Errorf("error reading 'cpu': %w", err)
		}
		delete(object, "cpu")
	}

	if raw, found := object["memory"]; found {
		err = json.Unmarshal(raw, &a.Memory)
		if err != nil {
			return fmt.Errorf("error reading 'memory': %w", err)
		}
		delete(object, "memory")
	}

	if raw, found := object["storage"]; found {
		err = json.Unmarshal(raw, &a.Storage)
		if err != nil {
			return fmt.Errorf("error reading 'storage': %w", err)
		}
		delete(object, "storage")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseResources to handle AdditionalProperties
func (a DatabaseResources) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["cpu"], err = json.Marshal(a.Cpu)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'cpu': %w", err)
	}

	object["memory"], err = json.Marshal(a.Memory)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory': %w", err)
	}

	object["storage"], err = json.Marshal(a.Storage)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'storage': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// Getter for additional properties for DatabaseSpec. Returns the specified
// element and whether it was found
func (a DatabaseSpec) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for DatabaseSpec
func (a *DatabaseSpec) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for DatabaseSpec to handle AdditionalProperties
func (a *DatabaseSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["connection_details"]; found {
		err = json.Unmarshal(raw, &a.ConnectionDetails)
		if err != nil {
			return fmt.Errorf("error reading 'connection_details': %w", err)
		}
		delete(object, "connection_details")
	}

	if raw, found := object["create_time"]; found {
		err = json.Unmarshal(raw, &a.CreateTime)
		if err != nil {
			return fmt.Errorf("error reading 'create_time': %w", err)
		}
		delete(object, "create_time")
	}

	if raw, found := object["engine"]; found {
		err = json.Unmarshal(raw, &a.Engine)
		if err != nil {
			return fmt.Errorf("error reading 'engine': %w", err)
		}
		delete(object, "engine")
	}

	if raw, found := object["id"]; found {
		err = json.Unmarshal(raw, &a.Id)
		if err != nil {
			return fmt.Errorf("error reading 'id': %w", err)
		}
		delete(object, "id")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["path"]; found {
		err = json.Unmarshal(raw, &a.Path)
		if err != nil {
			return fmt.Errorf("error reading 'path': %w", err)
		}
		delete(object, "path")
	}

	if raw, found := object["provider_hints"]; found {
		err = json.Unmarshal(raw, &a.ProviderHints)
		if err != nil {
			return fmt.Errorf("error reading 'provider_hints': %w", err)
		}
		delete(object, "provider_hints")
	}

	if raw, found := object["resources"]; found {
		err = json.Unmarshal(raw, &a.Resources)
		if err != nil {
			return fmt.Errorf("error reading 'resources': %w", err)
		}
		delete(object, "resources")
	}

	if raw, found := object["service_type"]; found {
		err = json.Unmarshal(raw, &a.ServiceType)
		if err != nil {
			return fmt.Errorf("error reading 'service_type': %w", err)
		}
		delete(object, "service_type")
	}

	if raw, found := object["status"]; found {
		err = json.Unmarshal(raw, &a.Status)
		if err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if raw, found := object["status_message"]; found {
		err = json.Unmarshal(raw, &a.StatusMessage)
		if err != nil {
			return fmt.Errorf("error reading 'status_message': %w", err)
		}
		delete(object, "status_message")
	}

	if raw, found := object["update_time"]; found {
		err = json.Unmarshal(raw, &a.UpdateTime)
		if err != nil {
			return fmt.Errorf("error reading 'update_time': %w", err)
		}
		delete(object, "update_time")
	}

	if raw, found := object["version"]; found {
		err = json.Unmarshal(raw, &a.Version)
		if err != nil {
			return fmt.Errorf("error reading 'version': %w", err)
		}
		delete(object, "version")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for DatabaseSpec to handle AdditionalProperties
func (a DatabaseSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.ConnectionDetails != nil {
		object["connection_details"], err = json.Marshal(a.ConnectionDetails)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'connection_details': %w", err)
		}
	}

	if a.CreateTime != nil {
		object["create_time"], err = json.Marshal(a.CreateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'create_time': %w", err)
		}
	}

	object["engine"], err = json.Marshal(a.Engine)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'engine': %w", err)
	}

	if a.Id != nil {
		object["id"], err = json.Marshal(a.Id)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id': %w", err)
		}
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	if a.Path != nil {
		object["path"], err = json.Marshal(a.Path)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'path': %w", err)
		}
	}

	if a.ProviderHints != nil {
		object["provider_hints"], err = json.Marshal(a.ProviderHints)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider_hints': %w", err)
		}
	}

	object["resources"], err = json.Marshal(a.Resources)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'resources': %w", err)
	}

	object["service_type"], err = json.Marshal(a.ServiceType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'service_type': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	if a.StatusMessage != nil {
		object["status_message"], err = json.Marshal(a.StatusMessage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status_message': %w", err)
		}
	}

	if a.UpdateTime != nil {
		object["update_time"], err = json.Marshal(a.UpdateTime)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'update_time': %w", err)
		}
	}

	object["version"], err = json.Marshal(a.Version)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'version': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
